// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

// Package ip holds adcgen-generated ISR secular-matrix element evaluators
// for single ionization (ip, classes 1h | 2h1p | 3h2p).
//
// Generated with schemes adc22f, adc22m, adc22x, strict:3; blocks B00<=3, B01<=2, B11<=2, B12<=1, B22<=1.
// Regenerate with
//
//	python3.12 scripts/codegen/generate_adc.py --variant ip --schemes adc22f,adc22m,adc22x,strict:3 \
//	    --outdir internal/adc/isrgen/ip
//
// fidelity_test.go (generated) replays testdata/adcgen_ref.json, an independent
// numpy evaluation of adcgen's fully expanded expressions.
package ip
