// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package ip

// b11o0t0: \delta_{i k} \delta_{j l} {f^{a}_{b}}
func (el *Elem) b11o0t0(a, i, j, b, k, l int) float64 {
	var acc float64
	var sv18 float64
	if i == k {
		if j == l {
			sv18 += 1
		}
	}
	if sv18 != 0 {
		fv19 := el.fock(el.nocc+a, el.nocc+b)
		if fv19 != 0 {
			acc += sv18 * fv19
		}
	}
	return acc
}

func (el *Elem) b11o0g0(a, i, j, b, k, l int) float64 {
	return el.b11o0t0(a, i, j, b, k, l)
}

// b11o0t1: \delta_{a b} \delta_{j k} {f^{i}_{l}}
func (el *Elem) b11o0t1(a, i, j, b, k, l int) float64 {
	var acc float64
	var sv20 float64
	fv21 := el.fock(i, l)
	if fv21 != 0 {
		if j == k {
			sv20 += fv21
		}
	}
	if sv20 != 0 {
		if a == b {
			acc += sv20
		}
	}
	return acc
}

func (el *Elem) b11o0g1(a, i, j, b, k, l int) float64 {
	return el.b11o0t1(a, i, j, b, k, l)
}

// b11o0 is the order-0 part of block phh,phh, <a,i,j|M|b,k,l>.
func (el *Elem) b11o0(a, i, j, b, k, l int) float64 {
	var v float64
	// (1 - P_ij)
	v += el.b11o0g0(a, i, j, b, k, l)
	v -= el.b11o0g0(a, j, i, b, k, l)
	// (1 - P_ij - P_kl + P_ijP_kl)
	v += el.b11o0g1(a, i, j, b, k, l)
	v -= el.b11o0g1(a, j, i, b, k, l)
	v -= el.b11o0g1(a, i, j, b, l, k)
	v += el.b11o0g1(a, j, i, b, l, k)
	return v
}

// b11o1t0: \delta_{j k} {V^{ib}_{la}}
func (el *Elem) b11o1t0(a, i, j, b, k, l int) float64 {
	var acc float64
	fv22 := el.asym(i, el.nocc+b, l, el.nocc+a)
	if fv22 != 0 {
		if j == k {
			acc += fv22
		}
	}
	return acc
}

func (el *Elem) b11o1g0(a, i, j, b, k, l int) float64 {
	return el.b11o1t0(a, i, j, b, k, l)
}

// b11o1t1: \delta_{a b} {V^{ij}_{kl}}
func (el *Elem) b11o1t1(a, i, j, b, k, l int) float64 {
	var acc float64
	fv23 := el.asym(i, j, k, l)
	if fv23 != 0 {
		if a == b {
			acc += fv23
		}
	}
	return acc
}

func (el *Elem) b11o1g1(a, i, j, b, k, l int) float64 {
	return el.b11o1t1(a, i, j, b, k, l)
}

// b11o1 is the order-1 part of block phh,phh, <a,i,j|M|b,k,l>.
func (el *Elem) b11o1(a, i, j, b, k, l int) float64 {
	var v float64
	// (1 - P_ij - P_kl + P_ijP_kl)
	v += el.b11o1g0(a, i, j, b, k, l)
	v -= el.b11o1g0(a, j, i, b, k, l)
	v -= el.b11o1g0(a, i, j, b, l, k)
	v += el.b11o1g0(a, j, i, b, l, k)
	// (1)
	v += el.b11o1g1(a, i, j, b, k, l)
	return v
}

// b11o2t0: \frac{{t1^{ac}_{ij}} {V^{kl}_{bc}}}{2}
func (el *Elem) b11o2t0(a, i, j, b, k, l int) float64 {
	var acc float64
	for c := 0; c < el.nvir; c++ {
		fv24 := el.get_t2_1(i, j, a, c)
		if fv24 != 0 {
			fv25 := el.asym(k, l, el.nocc+b, el.nocc+c)
			if fv25 != 0 {
				acc += fv24 * fv25
			}
		}
	}
	return 0.5 * acc
}

// b11o2t1: - \frac{\delta_{a b} {t1^{cd}_{ij}} {V^{kl}_{cd}}}{4}
func (el *Elem) b11o2t1(a, i, j, b, k, l int) float64 {
	var acc float64
	var sv26 float64
	for c := 0; c < el.nvir; c++ {
		for d := 0; d < el.nvir; d++ {
			fv27 := el.get_t2_1(i, j, c, d)
			if fv27 != 0 {
				fv28 := el.asym(k, l, el.nocc+c, el.nocc+d)
				if fv28 != 0 {
					sv26 += fv27 * fv28
				}
			}
		}
	}
	if sv26 != 0 {
		if a == b {
			acc += sv26
		}
	}
	return -0.25 * acc
}

func (el *Elem) b11o2g0(a, i, j, b, k, l int) float64 {
	return el.b11o2t0(a, i, j, b, k, l) +
		el.b11o2t1(a, i, j, b, k, l)
}

// b11o2t2: \frac{\delta_{j k} {t1^{ac}_{im}} {V^{lm}_{bc}}}{2}
func (el *Elem) b11o2t2(a, i, j, b, k, l int) float64 {
	var acc float64
	var sv29 float64
	for m := 0; m < el.nocc; m++ {
		for c := 0; c < el.nvir; c++ {
			fv30 := el.get_t2_1(i, m, a, c)
			if fv30 != 0 {
				fv31 := el.asym(l, m, el.nocc+b, el.nocc+c)
				if fv31 != 0 {
					sv29 += fv30 * fv31
				}
			}
		}
	}
	if sv29 != 0 {
		if j == k {
			acc += sv29
		}
	}
	return 0.5 * acc
}

// b11o2t3: - \frac{\delta_{a b} \delta_{j k} {t1^{cd}_{im}} {V^{lm}_{cd}}}{4}
func (el *Elem) b11o2t3(a, i, j, b, k, l int) float64 {
	var acc float64
	var sv32 float64
	var sv33 float64
	for m := 0; m < el.nocc; m++ {
		for c := 0; c < el.nvir; c++ {
			for d := 0; d < el.nvir; d++ {
				fv34 := el.get_t2_1(i, m, c, d)
				if fv34 != 0 {
					fv35 := el.asym(l, m, el.nocc+c, el.nocc+d)
					if fv35 != 0 {
						sv33 += fv34 * fv35
					}
				}
			}
		}
	}
	if sv33 != 0 {
		if j == k {
			sv32 += sv33
		}
	}
	if sv32 != 0 {
		if a == b {
			acc += sv32
		}
	}
	return -0.25 * acc
}

func (el *Elem) b11o2g1(a, i, j, b, k, l int) float64 {
	return el.b11o2t2(a, i, j, b, k, l) +
		el.b11o2t3(a, i, j, b, k, l)
}

// b11o2t4: - \frac{\delta_{i l} \delta_{j k} {t1^{ac}_{mn}} {V^{mn}_{bc}}}{4}
func (el *Elem) b11o2t4(a, i, j, b, k, l int) float64 {
	var acc float64
	var sv36 float64
	if i == l {
		if j == k {
			sv36 += 1
		}
	}
	if sv36 != 0 {
		var sv37 float64
		for m := 0; m < el.nocc; m++ {
			for n := 0; n < el.nocc; n++ {
				for c := 0; c < el.nvir; c++ {
					fv38 := el.get_t2_1(m, n, a, c)
					if fv38 != 0 {
						fv39 := el.asym(m, n, el.nocc+b, el.nocc+c)
						if fv39 != 0 {
							sv37 += fv38 * fv39
						}
					}
				}
			}
		}
		if sv37 != 0 {
			acc += sv36 * sv37
		}
	}
	return -0.25 * acc
}

func (el *Elem) b11o2g2(a, i, j, b, k, l int) float64 {
	return el.b11o2t4(a, i, j, b, k, l)
}

// b11o2 is the order-2 part of block phh,phh, <a,i,j|M|b,k,l>.
func (el *Elem) b11o2(a, i, j, b, k, l int) float64 {
	var v float64
	// (1 + P_ikP_jlP_ab)
	v += el.b11o2g0(a, i, j, b, k, l)
	v += el.b11o2g0(b, k, l, a, i, j)
	// (1 - P_ij - P_kl + P_ijP_kl + P_ikP_jlP_ab + P_ilP_jkP_ab - P_ijP_ikP_jlP_ab - P_ijP_ilP_jkP_ab)
	v += el.b11o2g1(a, i, j, b, k, l)
	v -= el.b11o2g1(a, j, i, b, k, l)
	v -= el.b11o2g1(a, i, j, b, l, k)
	v += el.b11o2g1(a, j, i, b, l, k)
	v += el.b11o2g1(b, k, l, a, i, j)
	v += el.b11o2g1(b, l, k, a, j, i)
	v -= el.b11o2g1(b, l, k, a, i, j)
	v -= el.b11o2g1(b, k, l, a, j, i)
	// (1 - P_ij + P_ikP_jlP_ab - P_ijP_ikP_jlP_ab)
	v += el.b11o2g2(a, i, j, b, k, l)
	v -= el.b11o2g2(a, j, i, b, k, l)
	v += el.b11o2g2(b, k, l, a, i, j)
	v -= el.b11o2g2(b, l, k, a, i, j)
	return v
}

// B11 is block phh,phh of the secular matrix,
// <a,i,j|M|b,k,l>, summed over the orders the scheme keeps.
func (el *Elem) B11(a, i, j, b, k, l int) float64 {
	var v float64
	if el.maxOrder[2] >= 0 {
		v += el.b11o0(a, i, j, b, k, l)
	}
	if el.maxOrder[2] >= 1 {
		v += el.b11o1(a, i, j, b, k, l)
	}
	if el.maxOrder[2] >= 2 {
		v += el.b11o2(a, i, j, b, k, l)
	}
	return v
}
