// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package ip

// b00o0t0: - {f^{i}_{j}}
func (el *Elem) b00o0t0(i, j int) float64 {
	var acc float64
	fv1 := el.fock(i, j)
	if fv1 != 0 {
		acc += fv1
	}
	return -1.0 * acc
}

func (el *Elem) b00o0g0(i, j int) float64 {
	return el.b00o0t0(i, j)
}

// b00o0 is the order-0 part of block h,h, <i|M|j>.
func (el *Elem) b00o0(i, j int) float64 {
	var v float64
	// (1)
	v += el.b00o0g0(i, j)
	return v
}

// h,h vanishes at order 1.

// b00o2t0: \frac{{t1^{ab}_{ik}} {V^{jk}_{ab}}}{4}
func (el *Elem) b00o2t0(i, j int) float64 {
	var acc float64
	for k := 0; k < el.nocc; k++ {
		for a := 0; a < el.nvir; a++ {
			for b := 0; b < el.nvir; b++ {
				fv2 := el.get_t2_1(i, k, a, b)
				if fv2 != 0 {
					fv3 := el.asym(j, k, el.nocc+a, el.nocc+b)
					if fv3 != 0 {
						acc += fv2 * fv3
					}
				}
			}
		}
	}
	return 0.25 * acc
}

func (el *Elem) b00o2g0(i, j int) float64 {
	return el.b00o2t0(i, j)
}

// b00o2 is the order-2 part of block h,h, <i|M|j>.
func (el *Elem) b00o2(i, j int) float64 {
	var v float64
	// (1 + P_ij)
	v += el.b00o2g0(i, j)
	v += el.b00o2g0(j, i)
	return v
}

// b00o3t0: \frac{{t1^{ab}_{ik}} {t2eri4_{jkba}}}{2}
func (el *Elem) b00o3t0(i, j int) float64 {
	var acc float64
	for k := 0; k < el.nocc; k++ {
		for a := 0; a < el.nvir; a++ {
			for b := 0; b < el.nvir; b++ {
				fv4 := el.get_t2_1(i, k, a, b)
				if fv4 != 0 {
					fv5 := el.get_t2eri_4(j, k, b, a)
					if fv5 != 0 {
						acc += fv4 * fv5
					}
				}
			}
		}
	}
	return 0.5 * acc
}

// b00o3t1: - {t2^{a}_{k}} {V^{ik}_{ja}}
func (el *Elem) b00o3t1(i, j int) float64 {
	var acc float64
	for k := 0; k < el.nocc; k++ {
		for a := 0; a < el.nvir; a++ {
			fv6 := el.get_t1_2(k, a)
			if fv6 != 0 {
				fv7 := el.asym(i, k, j, el.nocc+a)
				if fv7 != 0 {
					acc += fv6 * fv7
				}
			}
		}
	}
	return -1.0 * acc
}

// b00o3t2: - \frac{{t1^{ab}_{ik}} {t2eri3^{jk}_{ab}}}{8}
func (el *Elem) b00o3t2(i, j int) float64 {
	var acc float64
	for k := 0; k < el.nocc; k++ {
		for a := 0; a < el.nvir; a++ {
			for b := 0; b < el.nvir; b++ {
				fv8 := el.get_t2_1(i, k, a, b)
				if fv8 != 0 {
					fv9 := el.get_t2eri_3(j, k, a, b)
					if fv9 != 0 {
						acc += fv8 * fv9
					}
				}
			}
		}
	}
	return -0.125 * acc
}

// b00o3t3: \frac{{t2^{ab}_{ik}} {V^{jk}_{ab}}}{4}
func (el *Elem) b00o3t3(i, j int) float64 {
	var acc float64
	for k := 0; k < el.nocc; k++ {
		for a := 0; a < el.nvir; a++ {
			for b := 0; b < el.nvir; b++ {
				fv10 := el.get_t2_2(i, k, a, b)
				if fv10 != 0 {
					fv11 := el.asym(j, k, el.nocc+a, el.nocc+b)
					if fv11 != 0 {
						acc += fv10 * fv11
					}
				}
			}
		}
	}
	return 0.25 * acc
}

func (el *Elem) b00o3g0(i, j int) float64 {
	return el.b00o3t0(i, j) +
		el.b00o3t1(i, j) +
		el.b00o3t2(i, j) +
		el.b00o3t3(i, j)
}

// b00o3t4: - {V^{ia}_{jb}} {p2^{a}_{b}}
func (el *Elem) b00o3t4(i, j int) float64 {
	var acc float64
	for a := 0; a < el.nvir; a++ {
		for b := 0; b < el.nvir; b++ {
			fv12 := el.asym(i, el.nocc+a, j, el.nocc+b)
			if fv12 != 0 {
				fv13 := el.get_p0_2_vv(a, b)
				if fv13 != 0 {
					acc += fv12 * fv13
				}
			}
		}
	}
	return -1.0 * acc
}

// b00o3t5: - {V^{il}_{jk}} {p2^{k}_{l}}
func (el *Elem) b00o3t5(i, j int) float64 {
	var acc float64
	for k := 0; k < el.nocc; k++ {
		for l := 0; l < el.nocc; l++ {
			fv14 := el.asym(i, l, j, k)
			if fv14 != 0 {
				fv15 := el.get_p0_2_oo(k, l)
				if fv15 != 0 {
					acc += fv14 * fv15
				}
			}
		}
	}
	return -1.0 * acc
}

func (el *Elem) b00o3g1(i, j int) float64 {
	return el.b00o3t4(i, j) +
		el.b00o3t5(i, j)
}

// b00o3 is the order-3 part of block h,h, <i|M|j>.
func (el *Elem) b00o3(i, j int) float64 {
	var v float64
	// (1 + P_ij)
	v += el.b00o3g0(i, j)
	v += el.b00o3g0(j, i)
	// (1)
	v += el.b00o3g1(i, j)
	return v
}

// B00 is block h,h of the secular matrix,
// <i|M|j>, summed over the orders the scheme keeps.
func (el *Elem) B00(i, j int) float64 {
	var v float64
	if el.maxOrder[0] >= 0 {
		v += el.b00o0(i, j)
	}
	if el.maxOrder[0] >= 2 {
		v += el.b00o2(i, j)
	}
	if el.maxOrder[0] >= 3 {
		v += el.b00o3(i, j)
	}
	return v
}
