// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package ip

// b22o0t0: \delta_{b d} \delta_{i l} \delta_{j m} \delta_{k n} {f^{a}_{c}}
func (el *Elem) b22o0t0(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv44 := el.fock(el.nocc+a, el.nocc+c)
	if fv44 != 0 {
		if b == d {
			if i == l {
				if j == m {
					if k == n {
						acc += fv44
					}
				}
			}
		}
	}
	return acc
}

// b22o0t1: \delta_{b d} \delta_{i m} \delta_{j n} \delta_{k l} {f^{a}_{c}}
func (el *Elem) b22o0t1(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv45 := el.fock(el.nocc+a, el.nocc+c)
	if fv45 != 0 {
		if b == d {
			if i == m {
				if j == n {
					if k == l {
						acc += fv45
					}
				}
			}
		}
	}
	return acc
}

// b22o0t2: \delta_{b d} \delta_{i n} \delta_{j l} \delta_{k m} {f^{a}_{c}}
func (el *Elem) b22o0t2(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv46 := el.fock(el.nocc+a, el.nocc+c)
	if fv46 != 0 {
		if b == d {
			if i == n {
				if j == l {
					if k == m {
						acc += fv46
					}
				}
			}
		}
	}
	return acc
}

// b22o0t3: \delta_{b c} \delta_{i l} \delta_{j n} \delta_{k m} {f^{a}_{d}}
func (el *Elem) b22o0t3(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv47 := el.fock(el.nocc+a, el.nocc+d)
	if fv47 != 0 {
		if b == c {
			if i == l {
				if j == n {
					if k == m {
						acc += fv47
					}
				}
			}
		}
	}
	return acc
}

// b22o0t4: \delta_{b c} \delta_{i m} \delta_{j l} \delta_{k n} {f^{a}_{d}}
func (el *Elem) b22o0t4(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv48 := el.fock(el.nocc+a, el.nocc+d)
	if fv48 != 0 {
		if b == c {
			if i == m {
				if j == l {
					if k == n {
						acc += fv48
					}
				}
			}
		}
	}
	return acc
}

// b22o0t5: \delta_{b c} \delta_{i n} \delta_{j m} \delta_{k l} {f^{a}_{d}}
func (el *Elem) b22o0t5(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv49 := el.fock(el.nocc+a, el.nocc+d)
	if fv49 != 0 {
		if b == c {
			if i == n {
				if j == m {
					if k == l {
						acc += fv49
					}
				}
			}
		}
	}
	return acc
}

// b22o0t6: \delta_{a d} \delta_{i l} \delta_{j n} \delta_{k m} {f^{b}_{c}}
func (el *Elem) b22o0t6(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv50 := el.fock(el.nocc+b, el.nocc+c)
	if fv50 != 0 {
		if a == d {
			if i == l {
				if j == n {
					if k == m {
						acc += fv50
					}
				}
			}
		}
	}
	return acc
}

// b22o0t7: \delta_{a d} \delta_{i m} \delta_{j l} \delta_{k n} {f^{b}_{c}}
func (el *Elem) b22o0t7(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv51 := el.fock(el.nocc+b, el.nocc+c)
	if fv51 != 0 {
		if a == d {
			if i == m {
				if j == l {
					if k == n {
						acc += fv51
					}
				}
			}
		}
	}
	return acc
}

// b22o0t8: \delta_{a d} \delta_{i n} \delta_{j m} \delta_{k l} {f^{b}_{c}}
func (el *Elem) b22o0t8(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv52 := el.fock(el.nocc+b, el.nocc+c)
	if fv52 != 0 {
		if a == d {
			if i == n {
				if j == m {
					if k == l {
						acc += fv52
					}
				}
			}
		}
	}
	return acc
}

// b22o0t9: \delta_{a c} \delta_{i l} \delta_{j m} \delta_{k n} {f^{b}_{d}}
func (el *Elem) b22o0t9(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv53 := el.fock(el.nocc+b, el.nocc+d)
	if fv53 != 0 {
		if a == c {
			if i == l {
				if j == m {
					if k == n {
						acc += fv53
					}
				}
			}
		}
	}
	return acc
}

// b22o0t10: \delta_{a c} \delta_{i m} \delta_{j n} \delta_{k l} {f^{b}_{d}}
func (el *Elem) b22o0t10(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv54 := el.fock(el.nocc+b, el.nocc+d)
	if fv54 != 0 {
		if a == c {
			if i == m {
				if j == n {
					if k == l {
						acc += fv54
					}
				}
			}
		}
	}
	return acc
}

// b22o0t11: \delta_{a c} \delta_{i n} \delta_{j l} \delta_{k m} {f^{b}_{d}}
func (el *Elem) b22o0t11(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv55 := el.fock(el.nocc+b, el.nocc+d)
	if fv55 != 0 {
		if a == c {
			if i == n {
				if j == l {
					if k == m {
						acc += fv55
					}
				}
			}
		}
	}
	return acc
}

// b22o0t12: \delta_{a c} \delta_{b d} \delta_{j n} \delta_{k m} {f^{i}_{l}}
func (el *Elem) b22o0t12(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv56 := el.fock(i, l)
	if fv56 != 0 {
		if a == c {
			if b == d {
				if j == n {
					if k == m {
						acc += fv56
					}
				}
			}
		}
	}
	return acc
}

// b22o0t13: \delta_{a d} \delta_{b c} \delta_{j m} \delta_{k n} {f^{i}_{l}}
func (el *Elem) b22o0t13(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv57 := el.fock(i, l)
	if fv57 != 0 {
		if a == d {
			if b == c {
				if j == m {
					if k == n {
						acc += fv57
					}
				}
			}
		}
	}
	return acc
}

// b22o0t14: \delta_{a c} \delta_{b d} \delta_{j l} \delta_{k n} {f^{i}_{m}}
func (el *Elem) b22o0t14(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv58 := el.fock(i, m)
	if fv58 != 0 {
		if a == c {
			if b == d {
				if j == l {
					if k == n {
						acc += fv58
					}
				}
			}
		}
	}
	return acc
}

// b22o0t15: \delta_{a d} \delta_{b c} \delta_{j n} \delta_{k l} {f^{i}_{m}}
func (el *Elem) b22o0t15(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv59 := el.fock(i, m)
	if fv59 != 0 {
		if a == d {
			if b == c {
				if j == n {
					if k == l {
						acc += fv59
					}
				}
			}
		}
	}
	return acc
}

// b22o0t16: \delta_{a c} \delta_{b d} \delta_{j m} \delta_{k l} {f^{i}_{n}}
func (el *Elem) b22o0t16(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv60 := el.fock(i, n)
	if fv60 != 0 {
		if a == c {
			if b == d {
				if j == m {
					if k == l {
						acc += fv60
					}
				}
			}
		}
	}
	return acc
}

// b22o0t17: \delta_{a d} \delta_{b c} \delta_{j l} \delta_{k m} {f^{i}_{n}}
func (el *Elem) b22o0t17(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv61 := el.fock(i, n)
	if fv61 != 0 {
		if a == d {
			if b == c {
				if j == l {
					if k == m {
						acc += fv61
					}
				}
			}
		}
	}
	return acc
}

// b22o0t18: \delta_{a c} \delta_{b d} \delta_{i m} \delta_{k n} {f^{j}_{l}}
func (el *Elem) b22o0t18(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv62 := el.fock(j, l)
	if fv62 != 0 {
		if a == c {
			if b == d {
				if i == m {
					if k == n {
						acc += fv62
					}
				}
			}
		}
	}
	return acc
}

// b22o0t19: \delta_{a d} \delta_{b c} \delta_{i n} \delta_{k m} {f^{j}_{l}}
func (el *Elem) b22o0t19(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv63 := el.fock(j, l)
	if fv63 != 0 {
		if a == d {
			if b == c {
				if i == n {
					if k == m {
						acc += fv63
					}
				}
			}
		}
	}
	return acc
}

// b22o0t20: \delta_{a c} \delta_{b d} \delta_{i n} \delta_{k l} {f^{j}_{m}}
func (el *Elem) b22o0t20(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv64 := el.fock(j, m)
	if fv64 != 0 {
		if a == c {
			if b == d {
				if i == n {
					if k == l {
						acc += fv64
					}
				}
			}
		}
	}
	return acc
}

// b22o0t21: \delta_{a d} \delta_{b c} \delta_{i l} \delta_{k n} {f^{j}_{m}}
func (el *Elem) b22o0t21(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv65 := el.fock(j, m)
	if fv65 != 0 {
		if a == d {
			if b == c {
				if i == l {
					if k == n {
						acc += fv65
					}
				}
			}
		}
	}
	return acc
}

// b22o0t22: \delta_{a c} \delta_{b d} \delta_{i l} \delta_{k m} {f^{j}_{n}}
func (el *Elem) b22o0t22(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv66 := el.fock(j, n)
	if fv66 != 0 {
		if a == c {
			if b == d {
				if i == l {
					if k == m {
						acc += fv66
					}
				}
			}
		}
	}
	return acc
}

// b22o0t23: \delta_{a d} \delta_{b c} \delta_{i m} \delta_{k l} {f^{j}_{n}}
func (el *Elem) b22o0t23(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv67 := el.fock(j, n)
	if fv67 != 0 {
		if a == d {
			if b == c {
				if i == m {
					if k == l {
						acc += fv67
					}
				}
			}
		}
	}
	return acc
}

// b22o0t24: \delta_{a c} \delta_{b d} \delta_{i n} \delta_{j m} {f^{k}_{l}}
func (el *Elem) b22o0t24(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv68 := el.fock(k, l)
	if fv68 != 0 {
		if a == c {
			if b == d {
				if i == n {
					if j == m {
						acc += fv68
					}
				}
			}
		}
	}
	return acc
}

// b22o0t25: \delta_{a d} \delta_{b c} \delta_{i m} \delta_{j n} {f^{k}_{l}}
func (el *Elem) b22o0t25(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv69 := el.fock(k, l)
	if fv69 != 0 {
		if a == d {
			if b == c {
				if i == m {
					if j == n {
						acc += fv69
					}
				}
			}
		}
	}
	return acc
}

// b22o0t26: \delta_{a c} \delta_{b d} \delta_{i l} \delta_{j n} {f^{k}_{m}}
func (el *Elem) b22o0t26(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv70 := el.fock(k, m)
	if fv70 != 0 {
		if a == c {
			if b == d {
				if i == l {
					if j == n {
						acc += fv70
					}
				}
			}
		}
	}
	return acc
}

// b22o0t27: \delta_{a d} \delta_{b c} \delta_{i n} \delta_{j l} {f^{k}_{m}}
func (el *Elem) b22o0t27(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv71 := el.fock(k, m)
	if fv71 != 0 {
		if a == d {
			if b == c {
				if i == n {
					if j == l {
						acc += fv71
					}
				}
			}
		}
	}
	return acc
}

// b22o0t28: \delta_{a c} \delta_{b d} \delta_{i m} \delta_{j l} {f^{k}_{n}}
func (el *Elem) b22o0t28(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv72 := el.fock(k, n)
	if fv72 != 0 {
		if a == c {
			if b == d {
				if i == m {
					if j == l {
						acc += fv72
					}
				}
			}
		}
	}
	return acc
}

// b22o0t29: \delta_{a d} \delta_{b c} \delta_{i l} \delta_{j m} {f^{k}_{n}}
func (el *Elem) b22o0t29(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv73 := el.fock(k, n)
	if fv73 != 0 {
		if a == d {
			if b == c {
				if i == l {
					if j == m {
						acc += fv73
					}
				}
			}
		}
	}
	return acc
}

// b22o0t30: - \delta_{b d} \delta_{i l} \delta_{j n} \delta_{k m} {f^{a}_{c}}
func (el *Elem) b22o0t30(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv74 := el.fock(el.nocc+a, el.nocc+c)
	if fv74 != 0 {
		if b == d {
			if i == l {
				if j == n {
					if k == m {
						acc += fv74
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t31: - \delta_{b d} \delta_{i m} \delta_{j l} \delta_{k n} {f^{a}_{c}}
func (el *Elem) b22o0t31(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv75 := el.fock(el.nocc+a, el.nocc+c)
	if fv75 != 0 {
		if b == d {
			if i == m {
				if j == l {
					if k == n {
						acc += fv75
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t32: - \delta_{b d} \delta_{i n} \delta_{j m} \delta_{k l} {f^{a}_{c}}
func (el *Elem) b22o0t32(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv76 := el.fock(el.nocc+a, el.nocc+c)
	if fv76 != 0 {
		if b == d {
			if i == n {
				if j == m {
					if k == l {
						acc += fv76
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t33: - \delta_{b c} \delta_{i l} \delta_{j m} \delta_{k n} {f^{a}_{d}}
func (el *Elem) b22o0t33(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv77 := el.fock(el.nocc+a, el.nocc+d)
	if fv77 != 0 {
		if b == c {
			if i == l {
				if j == m {
					if k == n {
						acc += fv77
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t34: - \delta_{b c} \delta_{i m} \delta_{j n} \delta_{k l} {f^{a}_{d}}
func (el *Elem) b22o0t34(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv78 := el.fock(el.nocc+a, el.nocc+d)
	if fv78 != 0 {
		if b == c {
			if i == m {
				if j == n {
					if k == l {
						acc += fv78
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t35: - \delta_{b c} \delta_{i n} \delta_{j l} \delta_{k m} {f^{a}_{d}}
func (el *Elem) b22o0t35(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv79 := el.fock(el.nocc+a, el.nocc+d)
	if fv79 != 0 {
		if b == c {
			if i == n {
				if j == l {
					if k == m {
						acc += fv79
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t36: - \delta_{a d} \delta_{i l} \delta_{j m} \delta_{k n} {f^{b}_{c}}
func (el *Elem) b22o0t36(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv80 := el.fock(el.nocc+b, el.nocc+c)
	if fv80 != 0 {
		if a == d {
			if i == l {
				if j == m {
					if k == n {
						acc += fv80
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t37: - \delta_{a d} \delta_{i m} \delta_{j n} \delta_{k l} {f^{b}_{c}}
func (el *Elem) b22o0t37(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv81 := el.fock(el.nocc+b, el.nocc+c)
	if fv81 != 0 {
		if a == d {
			if i == m {
				if j == n {
					if k == l {
						acc += fv81
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t38: - \delta_{a d} \delta_{i n} \delta_{j l} \delta_{k m} {f^{b}_{c}}
func (el *Elem) b22o0t38(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv82 := el.fock(el.nocc+b, el.nocc+c)
	if fv82 != 0 {
		if a == d {
			if i == n {
				if j == l {
					if k == m {
						acc += fv82
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t39: - \delta_{a c} \delta_{i l} \delta_{j n} \delta_{k m} {f^{b}_{d}}
func (el *Elem) b22o0t39(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv83 := el.fock(el.nocc+b, el.nocc+d)
	if fv83 != 0 {
		if a == c {
			if i == l {
				if j == n {
					if k == m {
						acc += fv83
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t40: - \delta_{a c} \delta_{i m} \delta_{j l} \delta_{k n} {f^{b}_{d}}
func (el *Elem) b22o0t40(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv84 := el.fock(el.nocc+b, el.nocc+d)
	if fv84 != 0 {
		if a == c {
			if i == m {
				if j == l {
					if k == n {
						acc += fv84
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t41: - \delta_{a c} \delta_{i n} \delta_{j m} \delta_{k l} {f^{b}_{d}}
func (el *Elem) b22o0t41(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv85 := el.fock(el.nocc+b, el.nocc+d)
	if fv85 != 0 {
		if a == c {
			if i == n {
				if j == m {
					if k == l {
						acc += fv85
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t42: - \delta_{a c} \delta_{b d} \delta_{j m} \delta_{k n} {f^{i}_{l}}
func (el *Elem) b22o0t42(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv86 := el.fock(i, l)
	if fv86 != 0 {
		if a == c {
			if b == d {
				if j == m {
					if k == n {
						acc += fv86
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t43: - \delta_{a d} \delta_{b c} \delta_{j n} \delta_{k m} {f^{i}_{l}}
func (el *Elem) b22o0t43(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv87 := el.fock(i, l)
	if fv87 != 0 {
		if a == d {
			if b == c {
				if j == n {
					if k == m {
						acc += fv87
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t44: - \delta_{a c} \delta_{b d} \delta_{j n} \delta_{k l} {f^{i}_{m}}
func (el *Elem) b22o0t44(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv88 := el.fock(i, m)
	if fv88 != 0 {
		if a == c {
			if b == d {
				if j == n {
					if k == l {
						acc += fv88
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t45: - \delta_{a d} \delta_{b c} \delta_{j l} \delta_{k n} {f^{i}_{m}}
func (el *Elem) b22o0t45(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv89 := el.fock(i, m)
	if fv89 != 0 {
		if a == d {
			if b == c {
				if j == l {
					if k == n {
						acc += fv89
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t46: - \delta_{a c} \delta_{b d} \delta_{j l} \delta_{k m} {f^{i}_{n}}
func (el *Elem) b22o0t46(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv90 := el.fock(i, n)
	if fv90 != 0 {
		if a == c {
			if b == d {
				if j == l {
					if k == m {
						acc += fv90
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t47: - \delta_{a d} \delta_{b c} \delta_{j m} \delta_{k l} {f^{i}_{n}}
func (el *Elem) b22o0t47(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv91 := el.fock(i, n)
	if fv91 != 0 {
		if a == d {
			if b == c {
				if j == m {
					if k == l {
						acc += fv91
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t48: - \delta_{a c} \delta_{b d} \delta_{i n} \delta_{k m} {f^{j}_{l}}
func (el *Elem) b22o0t48(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv92 := el.fock(j, l)
	if fv92 != 0 {
		if a == c {
			if b == d {
				if i == n {
					if k == m {
						acc += fv92
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t49: - \delta_{a d} \delta_{b c} \delta_{i m} \delta_{k n} {f^{j}_{l}}
func (el *Elem) b22o0t49(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv93 := el.fock(j, l)
	if fv93 != 0 {
		if a == d {
			if b == c {
				if i == m {
					if k == n {
						acc += fv93
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t50: - \delta_{a c} \delta_{b d} \delta_{i l} \delta_{k n} {f^{j}_{m}}
func (el *Elem) b22o0t50(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv94 := el.fock(j, m)
	if fv94 != 0 {
		if a == c {
			if b == d {
				if i == l {
					if k == n {
						acc += fv94
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t51: - \delta_{a d} \delta_{b c} \delta_{i n} \delta_{k l} {f^{j}_{m}}
func (el *Elem) b22o0t51(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv95 := el.fock(j, m)
	if fv95 != 0 {
		if a == d {
			if b == c {
				if i == n {
					if k == l {
						acc += fv95
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t52: - \delta_{a c} \delta_{b d} \delta_{i m} \delta_{k l} {f^{j}_{n}}
func (el *Elem) b22o0t52(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv96 := el.fock(j, n)
	if fv96 != 0 {
		if a == c {
			if b == d {
				if i == m {
					if k == l {
						acc += fv96
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t53: - \delta_{a d} \delta_{b c} \delta_{i l} \delta_{k m} {f^{j}_{n}}
func (el *Elem) b22o0t53(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv97 := el.fock(j, n)
	if fv97 != 0 {
		if a == d {
			if b == c {
				if i == l {
					if k == m {
						acc += fv97
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t54: - \delta_{a c} \delta_{b d} \delta_{i m} \delta_{j n} {f^{k}_{l}}
func (el *Elem) b22o0t54(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv98 := el.fock(k, l)
	if fv98 != 0 {
		if a == c {
			if b == d {
				if i == m {
					if j == n {
						acc += fv98
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t55: - \delta_{a d} \delta_{b c} \delta_{i n} \delta_{j m} {f^{k}_{l}}
func (el *Elem) b22o0t55(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv99 := el.fock(k, l)
	if fv99 != 0 {
		if a == d {
			if b == c {
				if i == n {
					if j == m {
						acc += fv99
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t56: - \delta_{a c} \delta_{b d} \delta_{i n} \delta_{j l} {f^{k}_{m}}
func (el *Elem) b22o0t56(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv100 := el.fock(k, m)
	if fv100 != 0 {
		if a == c {
			if b == d {
				if i == n {
					if j == l {
						acc += fv100
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t57: - \delta_{a d} \delta_{b c} \delta_{i l} \delta_{j n} {f^{k}_{m}}
func (el *Elem) b22o0t57(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv101 := el.fock(k, m)
	if fv101 != 0 {
		if a == d {
			if b == c {
				if i == l {
					if j == n {
						acc += fv101
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t58: - \delta_{a c} \delta_{b d} \delta_{i l} \delta_{j m} {f^{k}_{n}}
func (el *Elem) b22o0t58(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv102 := el.fock(k, n)
	if fv102 != 0 {
		if a == c {
			if b == d {
				if i == l {
					if j == m {
						acc += fv102
					}
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o0t59: - \delta_{a d} \delta_{b c} \delta_{i m} \delta_{j l} {f^{k}_{n}}
func (el *Elem) b22o0t59(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv103 := el.fock(k, n)
	if fv103 != 0 {
		if a == d {
			if b == c {
				if i == m {
					if j == l {
						acc += fv103
					}
				}
			}
		}
	}
	return -1.0 * acc
}

func (el *Elem) b22o0g0(a, b, i, j, k, c, d, l, m, n int) float64 {
	return el.b22o0t0(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t1(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t2(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t3(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t4(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t5(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t6(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t7(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t8(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t9(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t10(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t11(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t12(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t13(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t14(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t15(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t16(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t17(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t18(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t19(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t20(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t21(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t22(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t23(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t24(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t25(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t26(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t27(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t28(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t29(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t30(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t31(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t32(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t33(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t34(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t35(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t36(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t37(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t38(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t39(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t40(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t41(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t42(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t43(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t44(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t45(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t46(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t47(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t48(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t49(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t50(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t51(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t52(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t53(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t54(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t55(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t56(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t57(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t58(a, b, i, j, k, c, d, l, m, n) +
		el.b22o0t59(a, b, i, j, k, c, d, l, m, n)
}

// b22o0 is the order-0 part of block pphhh,pphhh, <a,b,i,j,k|M|c,d,l,m,n>.
func (el *Elem) b22o0(a, b, i, j, k, c, d, l, m, n int) float64 {
	var v float64
	// (1)
	v += el.b22o0g0(a, b, i, j, k, c, d, l, m, n)
	return v
}

// b22o1t0: \delta_{i l} \delta_{j m} \delta_{k n} {V^{ab}_{cd}}
func (el *Elem) b22o1t0(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv104 := el.asym(el.nocc+a, el.nocc+b, el.nocc+c, el.nocc+d)
	if fv104 != 0 {
		if i == l {
			if j == m {
				if k == n {
					acc += fv104
				}
			}
		}
	}
	return acc
}

// b22o1t1: \delta_{i m} \delta_{j n} \delta_{k l} {V^{ab}_{cd}}
func (el *Elem) b22o1t1(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv105 := el.asym(el.nocc+a, el.nocc+b, el.nocc+c, el.nocc+d)
	if fv105 != 0 {
		if i == m {
			if j == n {
				if k == l {
					acc += fv105
				}
			}
		}
	}
	return acc
}

// b22o1t2: \delta_{i n} \delta_{j l} \delta_{k m} {V^{ab}_{cd}}
func (el *Elem) b22o1t2(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv106 := el.asym(el.nocc+a, el.nocc+b, el.nocc+c, el.nocc+d)
	if fv106 != 0 {
		if i == n {
			if j == l {
				if k == m {
					acc += fv106
				}
			}
		}
	}
	return acc
}

// b22o1t3: \delta_{b d} \delta_{j n} \delta_{k m} {V^{ic}_{la}}
func (el *Elem) b22o1t3(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv107 := el.asym(i, el.nocc+c, l, el.nocc+a)
	if fv107 != 0 {
		if b == d {
			if j == n {
				if k == m {
					acc += fv107
				}
			}
		}
	}
	return acc
}

// b22o1t4: \delta_{a d} \delta_{j m} \delta_{k n} {V^{ic}_{lb}}
func (el *Elem) b22o1t4(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv108 := el.asym(i, el.nocc+c, l, el.nocc+b)
	if fv108 != 0 {
		if a == d {
			if j == m {
				if k == n {
					acc += fv108
				}
			}
		}
	}
	return acc
}

// b22o1t5: \delta_{b d} \delta_{j l} \delta_{k n} {V^{ic}_{ma}}
func (el *Elem) b22o1t5(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv109 := el.asym(i, el.nocc+c, m, el.nocc+a)
	if fv109 != 0 {
		if b == d {
			if j == l {
				if k == n {
					acc += fv109
				}
			}
		}
	}
	return acc
}

// b22o1t6: \delta_{a d} \delta_{j n} \delta_{k l} {V^{ic}_{mb}}
func (el *Elem) b22o1t6(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv110 := el.asym(i, el.nocc+c, m, el.nocc+b)
	if fv110 != 0 {
		if a == d {
			if j == n {
				if k == l {
					acc += fv110
				}
			}
		}
	}
	return acc
}

// b22o1t7: \delta_{b d} \delta_{j m} \delta_{k l} {V^{ic}_{na}}
func (el *Elem) b22o1t7(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv111 := el.asym(i, el.nocc+c, n, el.nocc+a)
	if fv111 != 0 {
		if b == d {
			if j == m {
				if k == l {
					acc += fv111
				}
			}
		}
	}
	return acc
}

// b22o1t8: \delta_{a d} \delta_{j l} \delta_{k m} {V^{ic}_{nb}}
func (el *Elem) b22o1t8(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv112 := el.asym(i, el.nocc+c, n, el.nocc+b)
	if fv112 != 0 {
		if a == d {
			if j == l {
				if k == m {
					acc += fv112
				}
			}
		}
	}
	return acc
}

// b22o1t9: \delta_{b c} \delta_{j m} \delta_{k n} {V^{id}_{la}}
func (el *Elem) b22o1t9(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv113 := el.asym(i, el.nocc+d, l, el.nocc+a)
	if fv113 != 0 {
		if b == c {
			if j == m {
				if k == n {
					acc += fv113
				}
			}
		}
	}
	return acc
}

// b22o1t10: \delta_{a c} \delta_{j n} \delta_{k m} {V^{id}_{lb}}
func (el *Elem) b22o1t10(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv114 := el.asym(i, el.nocc+d, l, el.nocc+b)
	if fv114 != 0 {
		if a == c {
			if j == n {
				if k == m {
					acc += fv114
				}
			}
		}
	}
	return acc
}

// b22o1t11: \delta_{b c} \delta_{j n} \delta_{k l} {V^{id}_{ma}}
func (el *Elem) b22o1t11(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv115 := el.asym(i, el.nocc+d, m, el.nocc+a)
	if fv115 != 0 {
		if b == c {
			if j == n {
				if k == l {
					acc += fv115
				}
			}
		}
	}
	return acc
}

// b22o1t12: \delta_{a c} \delta_{j l} \delta_{k n} {V^{id}_{mb}}
func (el *Elem) b22o1t12(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv116 := el.asym(i, el.nocc+d, m, el.nocc+b)
	if fv116 != 0 {
		if a == c {
			if j == l {
				if k == n {
					acc += fv116
				}
			}
		}
	}
	return acc
}

// b22o1t13: \delta_{b c} \delta_{j l} \delta_{k m} {V^{id}_{na}}
func (el *Elem) b22o1t13(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv117 := el.asym(i, el.nocc+d, n, el.nocc+a)
	if fv117 != 0 {
		if b == c {
			if j == l {
				if k == m {
					acc += fv117
				}
			}
		}
	}
	return acc
}

// b22o1t14: \delta_{a c} \delta_{j m} \delta_{k l} {V^{id}_{nb}}
func (el *Elem) b22o1t14(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv118 := el.asym(i, el.nocc+d, n, el.nocc+b)
	if fv118 != 0 {
		if a == c {
			if j == m {
				if k == l {
					acc += fv118
				}
			}
		}
	}
	return acc
}

// b22o1t15: \delta_{a c} \delta_{b d} \delta_{k n} {V^{ij}_{lm}}
func (el *Elem) b22o1t15(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv119 := el.asym(i, j, l, m)
	if fv119 != 0 {
		if a == c {
			if b == d {
				if k == n {
					acc += fv119
				}
			}
		}
	}
	return acc
}

// b22o1t16: \delta_{a d} \delta_{b c} \delta_{k m} {V^{ij}_{ln}}
func (el *Elem) b22o1t16(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv120 := el.asym(i, j, l, n)
	if fv120 != 0 {
		if a == d {
			if b == c {
				if k == m {
					acc += fv120
				}
			}
		}
	}
	return acc
}

// b22o1t17: \delta_{a c} \delta_{b d} \delta_{k l} {V^{ij}_{mn}}
func (el *Elem) b22o1t17(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv121 := el.asym(i, j, m, n)
	if fv121 != 0 {
		if a == c {
			if b == d {
				if k == l {
					acc += fv121
				}
			}
		}
	}
	return acc
}

// b22o1t18: \delta_{a d} \delta_{b c} \delta_{j n} {V^{ik}_{lm}}
func (el *Elem) b22o1t18(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv122 := el.asym(i, k, l, m)
	if fv122 != 0 {
		if a == d {
			if b == c {
				if j == n {
					acc += fv122
				}
			}
		}
	}
	return acc
}

// b22o1t19: \delta_{a c} \delta_{b d} \delta_{j m} {V^{ik}_{ln}}
func (el *Elem) b22o1t19(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv123 := el.asym(i, k, l, n)
	if fv123 != 0 {
		if a == c {
			if b == d {
				if j == m {
					acc += fv123
				}
			}
		}
	}
	return acc
}

// b22o1t20: \delta_{a d} \delta_{b c} \delta_{j l} {V^{ik}_{mn}}
func (el *Elem) b22o1t20(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv124 := el.asym(i, k, m, n)
	if fv124 != 0 {
		if a == d {
			if b == c {
				if j == l {
					acc += fv124
				}
			}
		}
	}
	return acc
}

// b22o1t21: \delta_{b d} \delta_{i m} \delta_{k n} {V^{jc}_{la}}
func (el *Elem) b22o1t21(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv125 := el.asym(j, el.nocc+c, l, el.nocc+a)
	if fv125 != 0 {
		if b == d {
			if i == m {
				if k == n {
					acc += fv125
				}
			}
		}
	}
	return acc
}

// b22o1t22: \delta_{a d} \delta_{i n} \delta_{k m} {V^{jc}_{lb}}
func (el *Elem) b22o1t22(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv126 := el.asym(j, el.nocc+c, l, el.nocc+b)
	if fv126 != 0 {
		if a == d {
			if i == n {
				if k == m {
					acc += fv126
				}
			}
		}
	}
	return acc
}

// b22o1t23: \delta_{b d} \delta_{i n} \delta_{k l} {V^{jc}_{ma}}
func (el *Elem) b22o1t23(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv127 := el.asym(j, el.nocc+c, m, el.nocc+a)
	if fv127 != 0 {
		if b == d {
			if i == n {
				if k == l {
					acc += fv127
				}
			}
		}
	}
	return acc
}

// b22o1t24: \delta_{a d} \delta_{i l} \delta_{k n} {V^{jc}_{mb}}
func (el *Elem) b22o1t24(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv128 := el.asym(j, el.nocc+c, m, el.nocc+b)
	if fv128 != 0 {
		if a == d {
			if i == l {
				if k == n {
					acc += fv128
				}
			}
		}
	}
	return acc
}

// b22o1t25: \delta_{b d} \delta_{i l} \delta_{k m} {V^{jc}_{na}}
func (el *Elem) b22o1t25(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv129 := el.asym(j, el.nocc+c, n, el.nocc+a)
	if fv129 != 0 {
		if b == d {
			if i == l {
				if k == m {
					acc += fv129
				}
			}
		}
	}
	return acc
}

// b22o1t26: \delta_{a d} \delta_{i m} \delta_{k l} {V^{jc}_{nb}}
func (el *Elem) b22o1t26(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv130 := el.asym(j, el.nocc+c, n, el.nocc+b)
	if fv130 != 0 {
		if a == d {
			if i == m {
				if k == l {
					acc += fv130
				}
			}
		}
	}
	return acc
}

// b22o1t27: \delta_{b c} \delta_{i n} \delta_{k m} {V^{jd}_{la}}
func (el *Elem) b22o1t27(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv131 := el.asym(j, el.nocc+d, l, el.nocc+a)
	if fv131 != 0 {
		if b == c {
			if i == n {
				if k == m {
					acc += fv131
				}
			}
		}
	}
	return acc
}

// b22o1t28: \delta_{a c} \delta_{i m} \delta_{k n} {V^{jd}_{lb}}
func (el *Elem) b22o1t28(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv132 := el.asym(j, el.nocc+d, l, el.nocc+b)
	if fv132 != 0 {
		if a == c {
			if i == m {
				if k == n {
					acc += fv132
				}
			}
		}
	}
	return acc
}

// b22o1t29: \delta_{b c} \delta_{i l} \delta_{k n} {V^{jd}_{ma}}
func (el *Elem) b22o1t29(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv133 := el.asym(j, el.nocc+d, m, el.nocc+a)
	if fv133 != 0 {
		if b == c {
			if i == l {
				if k == n {
					acc += fv133
				}
			}
		}
	}
	return acc
}

// b22o1t30: \delta_{a c} \delta_{i n} \delta_{k l} {V^{jd}_{mb}}
func (el *Elem) b22o1t30(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv134 := el.asym(j, el.nocc+d, m, el.nocc+b)
	if fv134 != 0 {
		if a == c {
			if i == n {
				if k == l {
					acc += fv134
				}
			}
		}
	}
	return acc
}

// b22o1t31: \delta_{b c} \delta_{i m} \delta_{k l} {V^{jd}_{na}}
func (el *Elem) b22o1t31(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv135 := el.asym(j, el.nocc+d, n, el.nocc+a)
	if fv135 != 0 {
		if b == c {
			if i == m {
				if k == l {
					acc += fv135
				}
			}
		}
	}
	return acc
}

// b22o1t32: \delta_{a c} \delta_{i l} \delta_{k m} {V^{jd}_{nb}}
func (el *Elem) b22o1t32(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv136 := el.asym(j, el.nocc+d, n, el.nocc+b)
	if fv136 != 0 {
		if a == c {
			if i == l {
				if k == m {
					acc += fv136
				}
			}
		}
	}
	return acc
}

// b22o1t33: \delta_{a c} \delta_{b d} \delta_{i n} {V^{jk}_{lm}}
func (el *Elem) b22o1t33(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv137 := el.asym(j, k, l, m)
	if fv137 != 0 {
		if a == c {
			if b == d {
				if i == n {
					acc += fv137
				}
			}
		}
	}
	return acc
}

// b22o1t34: \delta_{a d} \delta_{b c} \delta_{i m} {V^{jk}_{ln}}
func (el *Elem) b22o1t34(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv138 := el.asym(j, k, l, n)
	if fv138 != 0 {
		if a == d {
			if b == c {
				if i == m {
					acc += fv138
				}
			}
		}
	}
	return acc
}

// b22o1t35: \delta_{a c} \delta_{b d} \delta_{i l} {V^{jk}_{mn}}
func (el *Elem) b22o1t35(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv139 := el.asym(j, k, m, n)
	if fv139 != 0 {
		if a == c {
			if b == d {
				if i == l {
					acc += fv139
				}
			}
		}
	}
	return acc
}

// b22o1t36: \delta_{b d} \delta_{i n} \delta_{j m} {V^{kc}_{la}}
func (el *Elem) b22o1t36(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv140 := el.asym(k, el.nocc+c, l, el.nocc+a)
	if fv140 != 0 {
		if b == d {
			if i == n {
				if j == m {
					acc += fv140
				}
			}
		}
	}
	return acc
}

// b22o1t37: \delta_{a d} \delta_{i m} \delta_{j n} {V^{kc}_{lb}}
func (el *Elem) b22o1t37(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv141 := el.asym(k, el.nocc+c, l, el.nocc+b)
	if fv141 != 0 {
		if a == d {
			if i == m {
				if j == n {
					acc += fv141
				}
			}
		}
	}
	return acc
}

// b22o1t38: \delta_{b d} \delta_{i l} \delta_{j n} {V^{kc}_{ma}}
func (el *Elem) b22o1t38(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv142 := el.asym(k, el.nocc+c, m, el.nocc+a)
	if fv142 != 0 {
		if b == d {
			if i == l {
				if j == n {
					acc += fv142
				}
			}
		}
	}
	return acc
}

// b22o1t39: \delta_{a d} \delta_{i n} \delta_{j l} {V^{kc}_{mb}}
func (el *Elem) b22o1t39(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv143 := el.asym(k, el.nocc+c, m, el.nocc+b)
	if fv143 != 0 {
		if a == d {
			if i == n {
				if j == l {
					acc += fv143
				}
			}
		}
	}
	return acc
}

// b22o1t40: \delta_{b d} \delta_{i m} \delta_{j l} {V^{kc}_{na}}
func (el *Elem) b22o1t40(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv144 := el.asym(k, el.nocc+c, n, el.nocc+a)
	if fv144 != 0 {
		if b == d {
			if i == m {
				if j == l {
					acc += fv144
				}
			}
		}
	}
	return acc
}

// b22o1t41: \delta_{a d} \delta_{i l} \delta_{j m} {V^{kc}_{nb}}
func (el *Elem) b22o1t41(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv145 := el.asym(k, el.nocc+c, n, el.nocc+b)
	if fv145 != 0 {
		if a == d {
			if i == l {
				if j == m {
					acc += fv145
				}
			}
		}
	}
	return acc
}

// b22o1t42: \delta_{b c} \delta_{i m} \delta_{j n} {V^{kd}_{la}}
func (el *Elem) b22o1t42(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv146 := el.asym(k, el.nocc+d, l, el.nocc+a)
	if fv146 != 0 {
		if b == c {
			if i == m {
				if j == n {
					acc += fv146
				}
			}
		}
	}
	return acc
}

// b22o1t43: \delta_{a c} \delta_{i n} \delta_{j m} {V^{kd}_{lb}}
func (el *Elem) b22o1t43(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv147 := el.asym(k, el.nocc+d, l, el.nocc+b)
	if fv147 != 0 {
		if a == c {
			if i == n {
				if j == m {
					acc += fv147
				}
			}
		}
	}
	return acc
}

// b22o1t44: \delta_{b c} \delta_{i n} \delta_{j l} {V^{kd}_{ma}}
func (el *Elem) b22o1t44(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv148 := el.asym(k, el.nocc+d, m, el.nocc+a)
	if fv148 != 0 {
		if b == c {
			if i == n {
				if j == l {
					acc += fv148
				}
			}
		}
	}
	return acc
}

// b22o1t45: \delta_{a c} \delta_{i l} \delta_{j n} {V^{kd}_{mb}}
func (el *Elem) b22o1t45(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv149 := el.asym(k, el.nocc+d, m, el.nocc+b)
	if fv149 != 0 {
		if a == c {
			if i == l {
				if j == n {
					acc += fv149
				}
			}
		}
	}
	return acc
}

// b22o1t46: \delta_{b c} \delta_{i l} \delta_{j m} {V^{kd}_{na}}
func (el *Elem) b22o1t46(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv150 := el.asym(k, el.nocc+d, n, el.nocc+a)
	if fv150 != 0 {
		if b == c {
			if i == l {
				if j == m {
					acc += fv150
				}
			}
		}
	}
	return acc
}

// b22o1t47: \delta_{a c} \delta_{i m} \delta_{j l} {V^{kd}_{nb}}
func (el *Elem) b22o1t47(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv151 := el.asym(k, el.nocc+d, n, el.nocc+b)
	if fv151 != 0 {
		if a == c {
			if i == m {
				if j == l {
					acc += fv151
				}
			}
		}
	}
	return acc
}

// b22o1t48: - \delta_{i l} \delta_{j n} \delta_{k m} {V^{ab}_{cd}}
func (el *Elem) b22o1t48(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv152 := el.asym(el.nocc+a, el.nocc+b, el.nocc+c, el.nocc+d)
	if fv152 != 0 {
		if i == l {
			if j == n {
				if k == m {
					acc += fv152
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t49: - \delta_{i m} \delta_{j l} \delta_{k n} {V^{ab}_{cd}}
func (el *Elem) b22o1t49(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv153 := el.asym(el.nocc+a, el.nocc+b, el.nocc+c, el.nocc+d)
	if fv153 != 0 {
		if i == m {
			if j == l {
				if k == n {
					acc += fv153
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t50: - \delta_{i n} \delta_{j m} \delta_{k l} {V^{ab}_{cd}}
func (el *Elem) b22o1t50(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv154 := el.asym(el.nocc+a, el.nocc+b, el.nocc+c, el.nocc+d)
	if fv154 != 0 {
		if i == n {
			if j == m {
				if k == l {
					acc += fv154
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t51: - \delta_{b d} \delta_{j m} \delta_{k n} {V^{ic}_{la}}
func (el *Elem) b22o1t51(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv155 := el.asym(i, el.nocc+c, l, el.nocc+a)
	if fv155 != 0 {
		if b == d {
			if j == m {
				if k == n {
					acc += fv155
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t52: - \delta_{a d} \delta_{j n} \delta_{k m} {V^{ic}_{lb}}
func (el *Elem) b22o1t52(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv156 := el.asym(i, el.nocc+c, l, el.nocc+b)
	if fv156 != 0 {
		if a == d {
			if j == n {
				if k == m {
					acc += fv156
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t53: - \delta_{b d} \delta_{j n} \delta_{k l} {V^{ic}_{ma}}
func (el *Elem) b22o1t53(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv157 := el.asym(i, el.nocc+c, m, el.nocc+a)
	if fv157 != 0 {
		if b == d {
			if j == n {
				if k == l {
					acc += fv157
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t54: - \delta_{a d} \delta_{j l} \delta_{k n} {V^{ic}_{mb}}
func (el *Elem) b22o1t54(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv158 := el.asym(i, el.nocc+c, m, el.nocc+b)
	if fv158 != 0 {
		if a == d {
			if j == l {
				if k == n {
					acc += fv158
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t55: - \delta_{b d} \delta_{j l} \delta_{k m} {V^{ic}_{na}}
func (el *Elem) b22o1t55(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv159 := el.asym(i, el.nocc+c, n, el.nocc+a)
	if fv159 != 0 {
		if b == d {
			if j == l {
				if k == m {
					acc += fv159
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t56: - \delta_{a d} \delta_{j m} \delta_{k l} {V^{ic}_{nb}}
func (el *Elem) b22o1t56(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv160 := el.asym(i, el.nocc+c, n, el.nocc+b)
	if fv160 != 0 {
		if a == d {
			if j == m {
				if k == l {
					acc += fv160
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t57: - \delta_{b c} \delta_{j n} \delta_{k m} {V^{id}_{la}}
func (el *Elem) b22o1t57(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv161 := el.asym(i, el.nocc+d, l, el.nocc+a)
	if fv161 != 0 {
		if b == c {
			if j == n {
				if k == m {
					acc += fv161
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t58: - \delta_{a c} \delta_{j m} \delta_{k n} {V^{id}_{lb}}
func (el *Elem) b22o1t58(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv162 := el.asym(i, el.nocc+d, l, el.nocc+b)
	if fv162 != 0 {
		if a == c {
			if j == m {
				if k == n {
					acc += fv162
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t59: - \delta_{b c} \delta_{j l} \delta_{k n} {V^{id}_{ma}}
func (el *Elem) b22o1t59(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv163 := el.asym(i, el.nocc+d, m, el.nocc+a)
	if fv163 != 0 {
		if b == c {
			if j == l {
				if k == n {
					acc += fv163
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t60: - \delta_{a c} \delta_{j n} \delta_{k l} {V^{id}_{mb}}
func (el *Elem) b22o1t60(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv164 := el.asym(i, el.nocc+d, m, el.nocc+b)
	if fv164 != 0 {
		if a == c {
			if j == n {
				if k == l {
					acc += fv164
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t61: - \delta_{b c} \delta_{j m} \delta_{k l} {V^{id}_{na}}
func (el *Elem) b22o1t61(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv165 := el.asym(i, el.nocc+d, n, el.nocc+a)
	if fv165 != 0 {
		if b == c {
			if j == m {
				if k == l {
					acc += fv165
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t62: - \delta_{a c} \delta_{j l} \delta_{k m} {V^{id}_{nb}}
func (el *Elem) b22o1t62(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv166 := el.asym(i, el.nocc+d, n, el.nocc+b)
	if fv166 != 0 {
		if a == c {
			if j == l {
				if k == m {
					acc += fv166
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t63: - \delta_{a d} \delta_{b c} \delta_{k n} {V^{ij}_{lm}}
func (el *Elem) b22o1t63(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv167 := el.asym(i, j, l, m)
	if fv167 != 0 {
		if a == d {
			if b == c {
				if k == n {
					acc += fv167
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t64: - \delta_{a c} \delta_{b d} \delta_{k m} {V^{ij}_{ln}}
func (el *Elem) b22o1t64(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv168 := el.asym(i, j, l, n)
	if fv168 != 0 {
		if a == c {
			if b == d {
				if k == m {
					acc += fv168
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t65: - \delta_{a d} \delta_{b c} \delta_{k l} {V^{ij}_{mn}}
func (el *Elem) b22o1t65(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv169 := el.asym(i, j, m, n)
	if fv169 != 0 {
		if a == d {
			if b == c {
				if k == l {
					acc += fv169
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t66: - \delta_{a c} \delta_{b d} \delta_{j n} {V^{ik}_{lm}}
func (el *Elem) b22o1t66(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv170 := el.asym(i, k, l, m)
	if fv170 != 0 {
		if a == c {
			if b == d {
				if j == n {
					acc += fv170
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t67: - \delta_{a d} \delta_{b c} \delta_{j m} {V^{ik}_{ln}}
func (el *Elem) b22o1t67(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv171 := el.asym(i, k, l, n)
	if fv171 != 0 {
		if a == d {
			if b == c {
				if j == m {
					acc += fv171
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t68: - \delta_{a c} \delta_{b d} \delta_{j l} {V^{ik}_{mn}}
func (el *Elem) b22o1t68(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv172 := el.asym(i, k, m, n)
	if fv172 != 0 {
		if a == c {
			if b == d {
				if j == l {
					acc += fv172
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t69: - \delta_{b d} \delta_{i n} \delta_{k m} {V^{jc}_{la}}
func (el *Elem) b22o1t69(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv173 := el.asym(j, el.nocc+c, l, el.nocc+a)
	if fv173 != 0 {
		if b == d {
			if i == n {
				if k == m {
					acc += fv173
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t70: - \delta_{a d} \delta_{i m} \delta_{k n} {V^{jc}_{lb}}
func (el *Elem) b22o1t70(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv174 := el.asym(j, el.nocc+c, l, el.nocc+b)
	if fv174 != 0 {
		if a == d {
			if i == m {
				if k == n {
					acc += fv174
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t71: - \delta_{b d} \delta_{i l} \delta_{k n} {V^{jc}_{ma}}
func (el *Elem) b22o1t71(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv175 := el.asym(j, el.nocc+c, m, el.nocc+a)
	if fv175 != 0 {
		if b == d {
			if i == l {
				if k == n {
					acc += fv175
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t72: - \delta_{a d} \delta_{i n} \delta_{k l} {V^{jc}_{mb}}
func (el *Elem) b22o1t72(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv176 := el.asym(j, el.nocc+c, m, el.nocc+b)
	if fv176 != 0 {
		if a == d {
			if i == n {
				if k == l {
					acc += fv176
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t73: - \delta_{b d} \delta_{i m} \delta_{k l} {V^{jc}_{na}}
func (el *Elem) b22o1t73(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv177 := el.asym(j, el.nocc+c, n, el.nocc+a)
	if fv177 != 0 {
		if b == d {
			if i == m {
				if k == l {
					acc += fv177
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t74: - \delta_{a d} \delta_{i l} \delta_{k m} {V^{jc}_{nb}}
func (el *Elem) b22o1t74(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv178 := el.asym(j, el.nocc+c, n, el.nocc+b)
	if fv178 != 0 {
		if a == d {
			if i == l {
				if k == m {
					acc += fv178
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t75: - \delta_{b c} \delta_{i m} \delta_{k n} {V^{jd}_{la}}
func (el *Elem) b22o1t75(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv179 := el.asym(j, el.nocc+d, l, el.nocc+a)
	if fv179 != 0 {
		if b == c {
			if i == m {
				if k == n {
					acc += fv179
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t76: - \delta_{a c} \delta_{i n} \delta_{k m} {V^{jd}_{lb}}
func (el *Elem) b22o1t76(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv180 := el.asym(j, el.nocc+d, l, el.nocc+b)
	if fv180 != 0 {
		if a == c {
			if i == n {
				if k == m {
					acc += fv180
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t77: - \delta_{b c} \delta_{i n} \delta_{k l} {V^{jd}_{ma}}
func (el *Elem) b22o1t77(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv181 := el.asym(j, el.nocc+d, m, el.nocc+a)
	if fv181 != 0 {
		if b == c {
			if i == n {
				if k == l {
					acc += fv181
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t78: - \delta_{a c} \delta_{i l} \delta_{k n} {V^{jd}_{mb}}
func (el *Elem) b22o1t78(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv182 := el.asym(j, el.nocc+d, m, el.nocc+b)
	if fv182 != 0 {
		if a == c {
			if i == l {
				if k == n {
					acc += fv182
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t79: - \delta_{b c} \delta_{i l} \delta_{k m} {V^{jd}_{na}}
func (el *Elem) b22o1t79(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv183 := el.asym(j, el.nocc+d, n, el.nocc+a)
	if fv183 != 0 {
		if b == c {
			if i == l {
				if k == m {
					acc += fv183
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t80: - \delta_{a c} \delta_{i m} \delta_{k l} {V^{jd}_{nb}}
func (el *Elem) b22o1t80(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv184 := el.asym(j, el.nocc+d, n, el.nocc+b)
	if fv184 != 0 {
		if a == c {
			if i == m {
				if k == l {
					acc += fv184
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t81: - \delta_{a d} \delta_{b c} \delta_{i n} {V^{jk}_{lm}}
func (el *Elem) b22o1t81(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv185 := el.asym(j, k, l, m)
	if fv185 != 0 {
		if a == d {
			if b == c {
				if i == n {
					acc += fv185
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t82: - \delta_{a c} \delta_{b d} \delta_{i m} {V^{jk}_{ln}}
func (el *Elem) b22o1t82(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv186 := el.asym(j, k, l, n)
	if fv186 != 0 {
		if a == c {
			if b == d {
				if i == m {
					acc += fv186
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t83: - \delta_{a d} \delta_{b c} \delta_{i l} {V^{jk}_{mn}}
func (el *Elem) b22o1t83(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv187 := el.asym(j, k, m, n)
	if fv187 != 0 {
		if a == d {
			if b == c {
				if i == l {
					acc += fv187
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t84: - \delta_{b d} \delta_{i m} \delta_{j n} {V^{kc}_{la}}
func (el *Elem) b22o1t84(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv188 := el.asym(k, el.nocc+c, l, el.nocc+a)
	if fv188 != 0 {
		if b == d {
			if i == m {
				if j == n {
					acc += fv188
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t85: - \delta_{a d} \delta_{i n} \delta_{j m} {V^{kc}_{lb}}
func (el *Elem) b22o1t85(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv189 := el.asym(k, el.nocc+c, l, el.nocc+b)
	if fv189 != 0 {
		if a == d {
			if i == n {
				if j == m {
					acc += fv189
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t86: - \delta_{b d} \delta_{i n} \delta_{j l} {V^{kc}_{ma}}
func (el *Elem) b22o1t86(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv190 := el.asym(k, el.nocc+c, m, el.nocc+a)
	if fv190 != 0 {
		if b == d {
			if i == n {
				if j == l {
					acc += fv190
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t87: - \delta_{a d} \delta_{i l} \delta_{j n} {V^{kc}_{mb}}
func (el *Elem) b22o1t87(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv191 := el.asym(k, el.nocc+c, m, el.nocc+b)
	if fv191 != 0 {
		if a == d {
			if i == l {
				if j == n {
					acc += fv191
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t88: - \delta_{b d} \delta_{i l} \delta_{j m} {V^{kc}_{na}}
func (el *Elem) b22o1t88(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv192 := el.asym(k, el.nocc+c, n, el.nocc+a)
	if fv192 != 0 {
		if b == d {
			if i == l {
				if j == m {
					acc += fv192
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t89: - \delta_{a d} \delta_{i m} \delta_{j l} {V^{kc}_{nb}}
func (el *Elem) b22o1t89(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv193 := el.asym(k, el.nocc+c, n, el.nocc+b)
	if fv193 != 0 {
		if a == d {
			if i == m {
				if j == l {
					acc += fv193
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t90: - \delta_{b c} \delta_{i n} \delta_{j m} {V^{kd}_{la}}
func (el *Elem) b22o1t90(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv194 := el.asym(k, el.nocc+d, l, el.nocc+a)
	if fv194 != 0 {
		if b == c {
			if i == n {
				if j == m {
					acc += fv194
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t91: - \delta_{a c} \delta_{i m} \delta_{j n} {V^{kd}_{lb}}
func (el *Elem) b22o1t91(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv195 := el.asym(k, el.nocc+d, l, el.nocc+b)
	if fv195 != 0 {
		if a == c {
			if i == m {
				if j == n {
					acc += fv195
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t92: - \delta_{b c} \delta_{i l} \delta_{j n} {V^{kd}_{ma}}
func (el *Elem) b22o1t92(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv196 := el.asym(k, el.nocc+d, m, el.nocc+a)
	if fv196 != 0 {
		if b == c {
			if i == l {
				if j == n {
					acc += fv196
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t93: - \delta_{a c} \delta_{i n} \delta_{j l} {V^{kd}_{mb}}
func (el *Elem) b22o1t93(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv197 := el.asym(k, el.nocc+d, m, el.nocc+b)
	if fv197 != 0 {
		if a == c {
			if i == n {
				if j == l {
					acc += fv197
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t94: - \delta_{b c} \delta_{i m} \delta_{j l} {V^{kd}_{na}}
func (el *Elem) b22o1t94(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv198 := el.asym(k, el.nocc+d, n, el.nocc+a)
	if fv198 != 0 {
		if b == c {
			if i == m {
				if j == l {
					acc += fv198
				}
			}
		}
	}
	return -1.0 * acc
}

// b22o1t95: - \delta_{a c} \delta_{i l} \delta_{j m} {V^{kd}_{nb}}
func (el *Elem) b22o1t95(a, b, i, j, k, c, d, l, m, n int) float64 {
	var acc float64
	fv199 := el.asym(k, el.nocc+d, n, el.nocc+b)
	if fv199 != 0 {
		if a == c {
			if i == l {
				if j == m {
					acc += fv199
				}
			}
		}
	}
	return -1.0 * acc
}

func (el *Elem) b22o1g0(a, b, i, j, k, c, d, l, m, n int) float64 {
	return el.b22o1t0(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t1(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t2(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t3(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t4(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t5(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t6(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t7(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t8(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t9(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t10(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t11(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t12(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t13(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t14(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t15(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t16(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t17(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t18(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t19(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t20(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t21(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t22(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t23(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t24(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t25(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t26(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t27(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t28(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t29(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t30(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t31(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t32(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t33(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t34(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t35(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t36(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t37(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t38(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t39(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t40(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t41(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t42(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t43(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t44(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t45(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t46(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t47(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t48(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t49(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t50(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t51(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t52(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t53(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t54(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t55(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t56(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t57(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t58(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t59(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t60(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t61(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t62(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t63(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t64(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t65(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t66(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t67(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t68(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t69(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t70(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t71(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t72(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t73(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t74(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t75(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t76(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t77(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t78(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t79(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t80(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t81(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t82(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t83(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t84(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t85(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t86(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t87(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t88(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t89(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t90(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t91(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t92(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t93(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t94(a, b, i, j, k, c, d, l, m, n) +
		el.b22o1t95(a, b, i, j, k, c, d, l, m, n)
}

// b22o1 is the order-1 part of block pphhh,pphhh, <a,b,i,j,k|M|c,d,l,m,n>.
func (el *Elem) b22o1(a, b, i, j, k, c, d, l, m, n int) float64 {
	var v float64
	// (1)
	v += el.b22o1g0(a, b, i, j, k, c, d, l, m, n)
	return v
}

// B22 is block pphhh,pphhh of the secular matrix,
// <a,b,i,j,k|M|c,d,l,m,n>, summed over the orders the scheme keeps.
func (el *Elem) B22(a, b, i, j, k, c, d, l, m, n int) float64 {
	var v float64
	if el.maxOrder[5] >= 0 {
		v += el.b22o0(a, b, i, j, k, c, d, l, m, n)
	}
	if el.maxOrder[5] >= 1 {
		v += el.b22o1(a, b, i, j, k, c, d, l, m, n)
	}
	return v
}
