// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package ip

// h,phh vanishes at order 0.

// b01o1t0: {V^{jk}_{ia}}
func (el *Elem) b01o1t0(i, a, j, k int) float64 {
	var acc float64
	fv16 := el.asym(j, k, i, el.nocc+a)
	if fv16 != 0 {
		acc += fv16
	}
	return acc
}

func (el *Elem) b01o1g0(i, a, j, k int) float64 {
	return el.b01o1t0(i, a, j, k)
}

// b01o1 is the order-1 part of block h,phh, <i|M|a,j,k>.
func (el *Elem) b01o1(i, a, j, k int) float64 {
	var v float64
	// (1)
	v += el.b01o1g0(i, a, j, k)
	return v
}

// b01o2t0: - {t2eriA^{jk}_{ia}}
func (el *Elem) b01o2t0(i, a, j, k int) float64 {
	var acc float64
	fv17 := el.get_t2eri_A(j, k, i, a)
	if fv17 != 0 {
		acc += fv17
	}
	return -1.0 * acc
}

func (el *Elem) b01o2g0(i, a, j, k int) float64 {
	return el.b01o2t0(i, a, j, k)
}

// b01o2 is the order-2 part of block h,phh, <i|M|a,j,k>.
func (el *Elem) b01o2(i, a, j, k int) float64 {
	var v float64
	// (1)
	v += el.b01o2g0(i, a, j, k)
	return v
}

// B01 is block h,phh of the secular matrix,
// <i|M|a,j,k>, summed over the orders the scheme keeps.
func (el *Elem) B01(i, a, j, k int) float64 {
	var v float64
	if el.maxOrder[1] >= 1 {
		v += el.b01o1(i, a, j, k)
	}
	if el.maxOrder[1] >= 2 {
		v += el.b01o2(i, a, j, k)
	}
	return v
}
