// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package ip

// phh,pphhh vanishes at order 0.

// b12o1t0: \delta_{i m} \delta_{j l} {V^{ka}_{bc}}
func (el *Elem) b12o1t0(a, i, j, b, c, k, l, m int) float64 {
	var acc float64
	var sv40 float64
	if i == m {
		if j == l {
			sv40 += 1
		}
	}
	if sv40 != 0 {
		fv41 := el.asym(k, el.nocc+a, el.nocc+b, el.nocc+c)
		if fv41 != 0 {
			acc += sv40 * fv41
		}
	}
	return acc
}

func (el *Elem) b12o1g0(a, i, j, b, c, k, l, m int) float64 {
	return el.b12o1t0(a, i, j, b, c, k, l, m)
}

// b12o1t1: \delta_{a b} \delta_{j m} {V^{kl}_{ic}}
func (el *Elem) b12o1t1(a, i, j, b, c, k, l, m int) float64 {
	var acc float64
	var sv42 float64
	if a == b {
		if j == m {
			sv42 += 1
		}
	}
	if sv42 != 0 {
		fv43 := el.asym(k, l, i, el.nocc+c)
		if fv43 != 0 {
			acc += sv42 * fv43
		}
	}
	return acc
}

func (el *Elem) b12o1g1(a, i, j, b, c, k, l, m int) float64 {
	return el.b12o1t1(a, i, j, b, c, k, l, m)
}

// b12o1 is the order-1 part of block phh,pphhh, <a,i,j|M|b,c,k,l,m>.
func (el *Elem) b12o1(a, i, j, b, c, k, l, m int) float64 {
	var v float64
	// (1 - P_ij - P_kl - P_km + P_ijP_kl + P_ijP_km)
	v += el.b12o1g0(a, i, j, b, c, k, l, m)
	v -= el.b12o1g0(a, j, i, b, c, k, l, m)
	v -= el.b12o1g0(a, i, j, b, c, l, k, m)
	v -= el.b12o1g0(a, i, j, b, c, m, l, k)
	v += el.b12o1g0(a, j, i, b, c, l, k, m)
	v += el.b12o1g0(a, j, i, b, c, m, l, k)
	// (1 - P_ij - P_km - P_lm + P_ijP_km + P_ijP_lm - P_bc + P_ijP_bc + P_kmP_bc + P_lmP_bc - P_ijP_kmP_bc - P_ijP_lmP_bc)
	v += el.b12o1g1(a, i, j, b, c, k, l, m)
	v -= el.b12o1g1(a, j, i, b, c, k, l, m)
	v -= el.b12o1g1(a, i, j, b, c, m, l, k)
	v -= el.b12o1g1(a, i, j, b, c, k, m, l)
	v += el.b12o1g1(a, j, i, b, c, m, l, k)
	v += el.b12o1g1(a, j, i, b, c, k, m, l)
	v -= el.b12o1g1(a, i, j, c, b, k, l, m)
	v += el.b12o1g1(a, j, i, c, b, k, l, m)
	v += el.b12o1g1(a, i, j, c, b, m, l, k)
	v += el.b12o1g1(a, i, j, c, b, k, m, l)
	v -= el.b12o1g1(a, j, i, c, b, m, l, k)
	v -= el.b12o1g1(a, j, i, c, b, k, m, l)
	return v
}

// B12 is block phh,pphhh of the secular matrix,
// <a,i,j|M|b,c,k,l,m>, summed over the orders the scheme keeps.
func (el *Elem) B12(a, i, j, b, c, k, l, m int) float64 {
	var v float64
	if el.maxOrder[4] >= 1 {
		v += el.b12o1(a, i, j, b, c, k, l, m)
	}
	return v
}
