// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package ip

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/leiaSQ/ADCgo/backend"
	"github.com/leiaSQ/ADCgo/internal/adc/fcidump"
	"github.com/leiaSQ/ADCgo/internal/adc/integrals"
	"github.com/leiaSQ/ADCgo/internal/adc/khci"
	"github.com/leiaSQ/ADCgo/internal/adc/mp"
)

type adcgenRef struct {
	Variant string `json:"variant"`
	Fcidump string `json:"fcidump"`
	Entries []struct {
		Block string  `json:"block"`
		Order int     `json:"order"`
		Idx   []int   `json:"idx"`
		Value float64 `json:"value"`
	} `json:"entries"`
}

type refSystem struct {
	d    *fcidump.Data
	nocc int
	eps  []float64
	ints *integrals.Store
}

func loadRef(t *testing.T) (adcgenRef, refSystem) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "adcgen_ref.json"))
	if err != nil {
		t.Fatalf("read reference (regenerate with scripts/codegen/generate_adc.py): %v", err)
	}
	var ref adcgenRef
	if err := json.Unmarshal(raw, &ref); err != nil {
		t.Fatalf("parse reference: %v", err)
	}
	d, err := fcidump.Read(strings.NewReader(ref.Fcidump))
	if err != nil {
		t.Fatalf("reference fcidump: %v", err)
	}
	nocc := mp.NOcc(d)
	return ref, refSystem{d, nocc, mp.OrbitalEnergies(d, nocc), integrals.New(d, nocc, nil)}
}

// widestScheme is the generated scheme that keeps the most orders.
func widestScheme() string {
	best, bestSum := "", -1
	names := make([]string, 0, len(Schemes))
	for n := range Schemes {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		s := 0
		for _, o := range Schemes[n] {
			s += o + 1
		}
		if s > bestSum {
			best, bestSum = n, s
		}
	}
	return best
}

// TestMatchesAdcgenReference: every generated block and order reproduces adcgen's
// fully expanded expression, evaluated independently in numpy at probe
// configurations of a random canonical system.
func TestMatchesAdcgenReference(t *testing.T) {
	ref, sys := loadRef(t)
	if ref.Variant != Variant {
		t.Fatalf("reference is for %s, code for %s: regenerate", ref.Variant, Variant)
	}
	el, err := New(sys.ints, sys.eps, sys.nocc, widestScheme())
	if err != nil {
		t.Fatal(err)
	}
	type key struct {
		block string
		order int
	}
	worst := map[key]float64{}
	n := 0
	for _, e := range ref.Entries {
		got, ok := el.orderPart(e.Block, e.Order, e.Idx)
		if !ok {
			if math.Abs(e.Value) > 1e-13 {
				t.Fatalf("%s order %d vanishes in Go but reference %v = %g", e.Block, e.Order, e.Idx, e.Value)
			}
			continue
		}
		n++
		k := key{e.Block, e.Order}
		worst[k] = max(worst[k], math.Abs(got-e.Value))
	}
	if n == 0 {
		t.Fatal("no reference entries matched a generated order")
	}
	for k, w := range worst {
		if w > 1e-12 {
			t.Errorf("%s order %d: max deviation %g from the adcgen reference", k.block, k.order, w)
		}
	}
}

// TestSymmetricAndMsDegenerate: the matrix over the generated classes is symmetric,
// and the spin-flip partner sectors 2Ms = +s and -s have identical spectra.
func TestSymmetricAndMsDegenerate(t *testing.T) {
	_, sys := loadRef(t)
	be := backend.Gonum{}
	for _, scheme := range func() []string {
		names := make([]string, 0, len(Schemes))
		for n := range Schemes {
			names = append(names, n)
		}
		sort.Strings(names)
		return names
	}() {
		el, err := New(sys.ints, sys.eps, sys.nocc, scheme)
		if err != nil {
			t.Fatal(err)
		}
		ms := 2 - K%2 // 2Ms = 1 for odd K, 2 for even K
		var spectra [2][]float64
		for s, two := range []int{ms, -ms} {
			sp, err := khci.NewSpace(khci.Options{K: K, NOcc: sys.nocc, NVir: sys.d.NORB - sys.nocc,
				TwoMs: two, MaxClass: 2})
			if err != nil {
				t.Fatal(err)
			}
			M := el.BuildDense(sp)
			for r := range M.Rows {
				for c := range r {
					if d := math.Abs(M.At(r, c) - M.At(c, r)); d > 1e-12 {
						t.Fatalf("%s 2Ms=%d: M[%d,%d] asymmetric by %g", scheme, two, r, c, d)
					}
				}
			}
			spectra[s], _ = be.SymEig(M)
			sort.Float64s(spectra[s])
		}
		if len(spectra[0]) != len(spectra[1]) {
			t.Fatalf("%s: sector sizes differ", scheme)
		}
		for i := range spectra[0] {
			if d := math.Abs(spectra[0][i] - spectra[1][i]); d > 1e-10 {
				t.Fatalf("%s root %d: %g vs %g", scheme, i, spectra[0][i], spectra[1][i])
			}
		}
	}
}
