// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package ip

import "github.com/leiaSQ/ADCgo/internal/adc/parallel"

// itmdStore holds the dense intermediate tensors, row-major over their
// indices (occupied extent el.nocc, virtual extent el.nvir).
type itmdStore struct {
	x_t2_1    []float64 // t2_1[i,j,a,b]
	x_p0_2_oo []float64 // p0_2_oo[i,j]
	x_p0_2_vv []float64 // p0_2_vv[a,b]
	x_t1_2    []float64 // t1_2[i,a]
	x_t2_2    []float64 // t2_2[i,j,a,b]
	x_t2eri_1 []float64 // t2eri_1[i,j,k,a]
	x_t2eri_2 []float64 // t2eri_2[i,j,k,a]
	x_t2eri_3 []float64 // t2eri_3[i,j,a,b]
	x_t2eri_4 []float64 // t2eri_4[i,j,a,b]
	x_t2eri_A []float64 // t2eri_A[i,j,k,a]
}

// buildItmds fills every intermediate in dependency order.
func (el *Elem) buildItmds() {
	el.build_t2_1()
	el.build_p0_2_oo()
	el.build_p0_2_vv()
	el.build_t1_2()
	el.build_t2_2()
	el.build_t2eri_1()
	el.build_t2eri_2()
	el.build_t2eri_3()
	el.build_t2eri_4()
	el.build_t2eri_A()
}

// ---- t2_1 ----

func (el *Elem) get_t2_1(i, j, a, b int) float64 {
	return el.x_t2_1[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b]
}

func (el *Elem) build_t2_1() {
	el.x_t2_1 = make([]float64, el.nocc*el.nocc*el.nvir*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for a := 0; a < el.nvir; a++ {
				for b := 0; b < el.nvir; b++ {
					el.x_t2_1[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b] = el.def_t2_1(i, j, a, b)
				}
			}
		}
	})
}

// def_t2_1t0: \frac{{V^{ab}_{ij}}}{{e_{a}} + {e_{b}} - {e_{i}} - {e_{j}}}
func (el *Elem) def_t2_1t0(i, j, a, b int) float64 {
	var acc float64
	fv205 := el.asym(el.nocc+a, el.nocc+b, i, j)
	if fv205 != 0 {
		acc += fv205
	}
	return (1.0 / ((-1.0 * el.eps(i)) + (-1.0 * el.eps(j)) + el.eps(el.nocc+a) + el.eps(el.nocc+b))) * acc
}

func (el *Elem) def_t2_1g0(i, j, a, b int) float64 {
	return el.def_t2_1t0(i, j, a, b)
}

// def_t2_1 is adcgen's definition of intermediate t2_1[i,j,a,b].
func (el *Elem) def_t2_1(i, j, a, b int) float64 {
	var v float64
	// (1)
	v += el.def_t2_1g0(i, j, a, b)
	return v
}

// ---- p0_2_oo ----

func (el *Elem) get_p0_2_oo(i, j int) float64 {
	return el.x_p0_2_oo[(i)*el.nocc+j]
}

func (el *Elem) build_p0_2_oo() {
	el.x_p0_2_oo = make([]float64, el.nocc*el.nocc)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			el.x_p0_2_oo[(i)*el.nocc+j] = el.def_p0_2_oo(i, j)
		}
	})
}

// def_p0_2_oot0: - \frac{{t1^{g515h515}_{ij763}} {t1^{g515h515}_{jj763}}}{2}
func (el *Elem) def_p0_2_oot0(i, j int) float64 {
	var acc float64
	for j763 := 0; j763 < el.nocc; j763++ {
		for g515 := 0; g515 < el.nvir; g515++ {
			for h515 := 0; h515 < el.nvir; h515++ {
				fv230 := el.get_t2_1(i, j763, g515, h515)
				if fv230 != 0 {
					fv231 := el.get_t2_1(j, j763, g515, h515)
					if fv231 != 0 {
						acc += fv230 * fv231
					}
				}
			}
		}
	}
	return -0.5 * acc
}

func (el *Elem) def_p0_2_oog0(i, j int) float64 {
	return el.def_p0_2_oot0(i, j)
}

// def_p0_2_oo is adcgen's definition of intermediate p0_2_oo[i,j].
func (el *Elem) def_p0_2_oo(i, j int) float64 {
	var v float64
	// (1)
	v += el.def_p0_2_oog0(i, j)
	return v
}

// ---- p0_2_vv ----

func (el *Elem) get_p0_2_vv(a, b int) float64 {
	return el.x_p0_2_vv[(a)*el.nvir+b]
}

func (el *Elem) build_p0_2_vv() {
	el.x_p0_2_vv = make([]float64, el.nvir*el.nvir)
	parallel.HeavyRows(el.nvir, func(a int) {
		for b := 0; b < el.nvir; b++ {
			el.x_p0_2_vv[(a)*el.nvir+b] = el.def_p0_2_vv(a, b)
		}
	})
}

// def_p0_2_vvt0: \frac{{t1^{af515}_{o762i763}} {t1^{bf515}_{o762i763}}}{2}
func (el *Elem) def_p0_2_vvt0(a, b int) float64 {
	var acc float64
	for o762 := 0; o762 < el.nocc; o762++ {
		for i763 := 0; i763 < el.nocc; i763++ {
			for f515 := 0; f515 < el.nvir; f515++ {
				fv228 := el.get_t2_1(o762, i763, a, f515)
				if fv228 != 0 {
					fv229 := el.get_t2_1(o762, i763, b, f515)
					if fv229 != 0 {
						acc += fv228 * fv229
					}
				}
			}
		}
	}
	return 0.5 * acc
}

func (el *Elem) def_p0_2_vvg0(a, b int) float64 {
	return el.def_p0_2_vvt0(a, b)
}

// def_p0_2_vv is adcgen's definition of intermediate p0_2_vv[a,b].
func (el *Elem) def_p0_2_vv(a, b int) float64 {
	var v float64
	// (1)
	v += el.def_p0_2_vvg0(a, b)
	return v
}

// ---- t1_2 ----

func (el *Elem) get_t1_2(i, a int) float64 {
	return el.x_t1_2[(i)*el.nvir+a]
}

func (el *Elem) build_t1_2() {
	el.x_t1_2 = make([]float64, el.nocc*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for a := 0; a < el.nvir; a++ {
			el.x_t1_2[(i)*el.nvir+a] = el.def_t1_2(i, a)
		}
	})
}

// def_t1_2t0: \frac{{t1^{ad515}_{m762n762}} {V^{m762n762}_{id515}}}{- 2 {e_{a}} + 2 {e_{i}}}
func (el *Elem) def_t1_2t0(i, a int) float64 {
	var acc float64
	for m762 := 0; m762 < el.nocc; m762++ {
		for n762 := 0; n762 < el.nocc; n762++ {
			for d515 := 0; d515 < el.nvir; d515++ {
				fv224 := el.get_t2_1(m762, n762, a, d515)
				if fv224 != 0 {
					fv225 := el.asym(m762, n762, i, el.nocc+d515)
					if fv225 != 0 {
						acc += fv224 * fv225
					}
				}
			}
		}
	}
	return (1.0 / ((-2.0 * el.eps(el.nocc+a)) + (2.0 * el.eps(i)))) * acc
}

// def_t1_2t1: \frac{{t1^{d515e515}_{im762}} {V^{m762a}_{d515e515}}}{- 2 {e_{a}} + 2 {e_{i}}}
func (el *Elem) def_t1_2t1(i, a int) float64 {
	var acc float64
	for m762 := 0; m762 < el.nocc; m762++ {
		for d515 := 0; d515 < el.nvir; d515++ {
			for e515 := 0; e515 < el.nvir; e515++ {
				fv226 := el.get_t2_1(i, m762, d515, e515)
				if fv226 != 0 {
					fv227 := el.asym(m762, el.nocc+a, el.nocc+d515, el.nocc+e515)
					if fv227 != 0 {
						acc += fv226 * fv227
					}
				}
			}
		}
	}
	return (1.0 / ((-2.0 * el.eps(el.nocc+a)) + (2.0 * el.eps(i)))) * acc
}

func (el *Elem) def_t1_2g0(i, a int) float64 {
	return el.def_t1_2t0(i, a) +
		el.def_t1_2t1(i, a)
}

// def_t1_2 is adcgen's definition of intermediate t1_2[i,a].
func (el *Elem) def_t1_2(i, a int) float64 {
	var v float64
	// (1)
	v += el.def_t1_2g0(i, a)
	return v
}

// ---- t2_2 ----

func (el *Elem) get_t2_2(i, j, a, b int) float64 {
	return el.x_t2_2[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b]
}

func (el *Elem) build_t2_2() {
	el.x_t2_2 = make([]float64, el.nocc*el.nocc*el.nvir*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for a := 0; a < el.nvir; a++ {
				for b := 0; b < el.nvir; b++ {
					el.x_t2_2[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b] = el.def_t2_2(i, j, a, b)
				}
			}
		}
	})
}

// def_t2_2t0: \frac{{t1^{ab515}_{ik762}} {V^{k762b}_{jb515}}}{{e_{a}} + {e_{b}} - {e_{i}} - {e_{j}}}
func (el *Elem) def_t2_2t0(i, j, a, b int) float64 {
	var acc float64
	for k762 := 0; k762 < el.nocc; k762++ {
		for b515 := 0; b515 < el.nvir; b515++ {
			fv212 := el.get_t2_1(i, k762, a, b515)
			if fv212 != 0 {
				fv213 := el.asym(k762, el.nocc+b, j, el.nocc+b515)
				if fv213 != 0 {
					acc += fv212 * fv213
				}
			}
		}
	}
	return (1.0 / ((-1.0 * el.eps(i)) + (-1.0 * el.eps(j)) + el.eps(el.nocc+a) + el.eps(el.nocc+b))) * acc
}

// def_t2_2t1: \frac{{t1^{bb515}_{jk762}} {V^{k762a}_{ib515}}}{{e_{a}} + {e_{b}} - {e_{i}} - {e_{j}}}
func (el *Elem) def_t2_2t1(i, j, a, b int) float64 {
	var acc float64
	for k762 := 0; k762 < el.nocc; k762++ {
		for b515 := 0; b515 < el.nvir; b515++ {
			fv214 := el.get_t2_1(j, k762, b, b515)
			if fv214 != 0 {
				fv215 := el.asym(k762, el.nocc+a, i, el.nocc+b515)
				if fv215 != 0 {
					acc += fv214 * fv215
				}
			}
		}
	}
	return (1.0 / ((-1.0 * el.eps(i)) + (-1.0 * el.eps(j)) + el.eps(el.nocc+a) + el.eps(el.nocc+b))) * acc
}

// def_t2_2t2: - \frac{{t1^{ab515}_{jk762}} {V^{k762b}_{ib515}}}{{e_{a}} + {e_{b}} - {e_{i}} - {e_{j}}}
func (el *Elem) def_t2_2t2(i, j, a, b int) float64 {
	var acc float64
	for k762 := 0; k762 < el.nocc; k762++ {
		for b515 := 0; b515 < el.nvir; b515++ {
			fv216 := el.get_t2_1(j, k762, a, b515)
			if fv216 != 0 {
				fv217 := el.asym(k762, el.nocc+b, i, el.nocc+b515)
				if fv217 != 0 {
					acc += fv216 * fv217
				}
			}
		}
	}
	return (-1.0 * (1.0 / ((-1.0 * el.eps(i)) + (-1.0 * el.eps(j)) + el.eps(el.nocc+a) + el.eps(el.nocc+b)))) * acc
}

// def_t2_2t3: - \frac{{t1^{bb515}_{ik762}} {V^{k762a}_{jb515}}}{{e_{a}} + {e_{b}} - {e_{i}} - {e_{j}}}
func (el *Elem) def_t2_2t3(i, j, a, b int) float64 {
	var acc float64
	for k762 := 0; k762 < el.nocc; k762++ {
		for b515 := 0; b515 < el.nvir; b515++ {
			fv218 := el.get_t2_1(i, k762, b, b515)
			if fv218 != 0 {
				fv219 := el.asym(k762, el.nocc+a, j, el.nocc+b515)
				if fv219 != 0 {
					acc += fv218 * fv219
				}
			}
		}
	}
	return (-1.0 * (1.0 / ((-1.0 * el.eps(i)) + (-1.0 * el.eps(j)) + el.eps(el.nocc+a) + el.eps(el.nocc+b)))) * acc
}

// def_t2_2t4: - \frac{{t1^{ab}_{k762l762}} {V^{ij}_{k762l762}}}{2 {e_{a}} + 2 {e_{b}} - 2 {e_{i}} - 2 {e_{j}}}
func (el *Elem) def_t2_2t4(i, j, a, b int) float64 {
	var acc float64
	for k762 := 0; k762 < el.nocc; k762++ {
		for l762 := 0; l762 < el.nocc; l762++ {
			fv220 := el.get_t2_1(k762, l762, a, b)
			if fv220 != 0 {
				fv221 := el.asym(i, j, k762, l762)
				if fv221 != 0 {
					acc += fv220 * fv221
				}
			}
		}
	}
	return (-1.0 * (1.0 / ((-2.0 * el.eps(i)) + (-2.0 * el.eps(j)) + (2.0 * el.eps(el.nocc+a)) + (2.0 * el.eps(el.nocc+b))))) * acc
}

// def_t2_2t5: - \frac{{t1^{b515c515}_{ij}} {V^{ab}_{b515c515}}}{2 {e_{a}} + 2 {e_{b}} - 2 {e_{i}} - 2 {e_{j}}}
func (el *Elem) def_t2_2t5(i, j, a, b int) float64 {
	var acc float64
	for b515 := 0; b515 < el.nvir; b515++ {
		for c515 := 0; c515 < el.nvir; c515++ {
			fv222 := el.get_t2_1(i, j, b515, c515)
			if fv222 != 0 {
				fv223 := el.asym(el.nocc+a, el.nocc+b, el.nocc+b515, el.nocc+c515)
				if fv223 != 0 {
					acc += fv222 * fv223
				}
			}
		}
	}
	return (-1.0 * (1.0 / ((-2.0 * el.eps(i)) + (-2.0 * el.eps(j)) + (2.0 * el.eps(el.nocc+a)) + (2.0 * el.eps(el.nocc+b))))) * acc
}

func (el *Elem) def_t2_2g0(i, j, a, b int) float64 {
	return el.def_t2_2t0(i, j, a, b) +
		el.def_t2_2t1(i, j, a, b) +
		el.def_t2_2t2(i, j, a, b) +
		el.def_t2_2t3(i, j, a, b) +
		el.def_t2_2t4(i, j, a, b) +
		el.def_t2_2t5(i, j, a, b)
}

// def_t2_2 is adcgen's definition of intermediate t2_2[i,j,a,b].
func (el *Elem) def_t2_2(i, j, a, b int) float64 {
	var v float64
	// (1)
	v += el.def_t2_2g0(i, j, a, b)
	return v
}

// ---- t2eri_1 ----

func (el *Elem) get_t2eri_1(i, j, k, a int) float64 {
	return el.x_t2eri_1[(((i)*el.nocc+j)*el.nocc+k)*el.nvir+a]
}

func (el *Elem) build_t2eri_1() {
	el.x_t2eri_1 = make([]float64, el.nocc*el.nocc*el.nocc*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for k := 0; k < el.nocc; k++ {
				for a := 0; a < el.nvir; a++ {
					el.x_t2eri_1[(((i)*el.nocc+j)*el.nocc+k)*el.nvir+a] = el.def_t2eri_1(i, j, k, a)
				}
			}
		}
	})
}

// def_t2eri_1t0: {t1^{g514h514}_{ij}} {V^{ka}_{g514h514}}
func (el *Elem) def_t2eri_1t0(i, j, k, a int) float64 {
	var acc float64
	for g514 := 0; g514 < el.nvir; g514++ {
		for h514 := 0; h514 < el.nvir; h514++ {
			fv206 := el.get_t2_1(i, j, g514, h514)
			if fv206 != 0 {
				fv207 := el.asym(k, el.nocc+a, el.nocc+g514, el.nocc+h514)
				if fv207 != 0 {
					acc += fv206 * fv207
				}
			}
		}
	}
	return acc
}

func (el *Elem) def_t2eri_1g0(i, j, k, a int) float64 {
	return el.def_t2eri_1t0(i, j, k, a)
}

// def_t2eri_1 is adcgen's definition of intermediate t2eri_1[i,j,k,a].
func (el *Elem) def_t2eri_1(i, j, k, a int) float64 {
	var v float64
	// (1)
	v += el.def_t2eri_1g0(i, j, k, a)
	return v
}

// ---- t2eri_2 ----

func (el *Elem) get_t2eri_2(i, j, k, a int) float64 {
	return el.x_t2eri_2[(((i)*el.nocc+j)*el.nocc+k)*el.nvir+a]
}

func (el *Elem) build_t2eri_2() {
	el.x_t2eri_2 = make([]float64, el.nocc*el.nocc*el.nocc*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for k := 0; k < el.nocc; k++ {
				for a := 0; a < el.nvir; a++ {
					el.x_t2eri_2[(((i)*el.nocc+j)*el.nocc+k)*el.nvir+a] = el.def_t2eri_2(i, j, k, a)
				}
			}
		}
	})
}

// def_t2eri_2t0: - {t1^{af514}_{in761}} {V^{kn761}_{jf514}}
func (el *Elem) def_t2eri_2t0(i, j, k, a int) float64 {
	var acc float64
	for n761 := 0; n761 < el.nocc; n761++ {
		for f514 := 0; f514 < el.nvir; f514++ {
			fv203 := el.get_t2_1(i, n761, a, f514)
			if fv203 != 0 {
				fv204 := el.asym(k, n761, j, el.nocc+f514)
				if fv204 != 0 {
					acc += fv203 * fv204
				}
			}
		}
	}
	return -1.0 * acc
}

func (el *Elem) def_t2eri_2g0(i, j, k, a int) float64 {
	return el.def_t2eri_2t0(i, j, k, a)
}

// def_t2eri_2 is adcgen's definition of intermediate t2eri_2[i,j,k,a].
func (el *Elem) def_t2eri_2(i, j, k, a int) float64 {
	var v float64
	// (1)
	v += el.def_t2eri_2g0(i, j, k, a)
	return v
}

// ---- t2eri_3 ----

func (el *Elem) get_t2eri_3(i, j, a, b int) float64 {
	return el.x_t2eri_3[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b]
}

func (el *Elem) build_t2eri_3() {
	el.x_t2eri_3 = make([]float64, el.nocc*el.nocc*el.nvir*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for a := 0; a < el.nvir; a++ {
				for b := 0; b < el.nvir; b++ {
					el.x_t2eri_3[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b] = el.def_t2eri_3(i, j, a, b)
				}
			}
		}
	})
}

// def_t2eri_3t0: {t1^{ab}_{i762j762}} {V^{ij}_{i762j762}}
func (el *Elem) def_t2eri_3t0(i, j, a, b int) float64 {
	var acc float64
	for i762 := 0; i762 < el.nocc; i762++ {
		for j762 := 0; j762 < el.nocc; j762++ {
			fv210 := el.get_t2_1(i762, j762, a, b)
			if fv210 != 0 {
				fv211 := el.asym(i, j, i762, j762)
				if fv211 != 0 {
					acc += fv210 * fv211
				}
			}
		}
	}
	return acc
}

func (el *Elem) def_t2eri_3g0(i, j, a, b int) float64 {
	return el.def_t2eri_3t0(i, j, a, b)
}

// def_t2eri_3 is adcgen's definition of intermediate t2eri_3[i,j,a,b].
func (el *Elem) def_t2eri_3(i, j, a, b int) float64 {
	var v float64
	// (1)
	v += el.def_t2eri_3g0(i, j, a, b)
	return v
}

// ---- t2eri_4 ----

func (el *Elem) get_t2eri_4(i, j, a, b int) float64 {
	return el.x_t2eri_4[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b]
}

func (el *Elem) build_t2eri_4() {
	el.x_t2eri_4 = make([]float64, el.nocc*el.nocc*el.nvir*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for a := 0; a < el.nvir; a++ {
				for b := 0; b < el.nvir; b++ {
					el.x_t2eri_4[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b] = el.def_t2eri_4(i, j, a, b)
				}
			}
		}
	})
}

// def_t2eri_4t0: {t1^{aa515}_{jo761}} {V^{o761b}_{ia515}}
func (el *Elem) def_t2eri_4t0(i, j, a, b int) float64 {
	var acc float64
	for o761 := 0; o761 < el.nocc; o761++ {
		for a515 := 0; a515 < el.nvir; a515++ {
			fv208 := el.get_t2_1(j, o761, a, a515)
			if fv208 != 0 {
				fv209 := el.asym(o761, el.nocc+b, i, el.nocc+a515)
				if fv209 != 0 {
					acc += fv208 * fv209
				}
			}
		}
	}
	return acc
}

func (el *Elem) def_t2eri_4g0(i, j, a, b int) float64 {
	return el.def_t2eri_4t0(i, j, a, b)
}

// def_t2eri_4 is adcgen's definition of intermediate t2eri_4[i,j,a,b].
func (el *Elem) def_t2eri_4(i, j, a, b int) float64 {
	var v float64
	// (1)
	v += el.def_t2eri_4g0(i, j, a, b)
	return v
}

// ---- t2eri_A ----

func (el *Elem) get_t2eri_A(i, j, k, a int) float64 {
	return el.x_t2eri_A[(((i)*el.nocc+j)*el.nocc+k)*el.nvir+a]
}

func (el *Elem) build_t2eri_A() {
	el.x_t2eri_A = make([]float64, el.nocc*el.nocc*el.nocc*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for k := 0; k < el.nocc; k++ {
				for a := 0; a < el.nvir; a++ {
					el.x_t2eri_A[(((i)*el.nocc+j)*el.nocc+k)*el.nvir+a] = el.def_t2eri_A(i, j, k, a)
				}
			}
		}
	})
}

// def_t2eri_At0: \frac{{t2eri1^{ij}_{ka}}}{2}
func (el *Elem) def_t2eri_At0(i, j, k, a int) float64 {
	var acc float64
	fv200 := el.get_t2eri_1(i, j, k, a)
	if fv200 != 0 {
		acc += fv200
	}
	return 0.5 * acc
}

// def_t2eri_At1: - {t2eri2_{jika}}
func (el *Elem) def_t2eri_At1(i, j, k, a int) float64 {
	var acc float64
	fv201 := el.get_t2eri_2(j, i, k, a)
	if fv201 != 0 {
		acc += fv201
	}
	return -1.0 * acc
}

// def_t2eri_At2: {t2eri2_{ijka}}
func (el *Elem) def_t2eri_At2(i, j, k, a int) float64 {
	var acc float64
	fv202 := el.get_t2eri_2(i, j, k, a)
	if fv202 != 0 {
		acc += fv202
	}
	return acc
}

func (el *Elem) def_t2eri_Ag0(i, j, k, a int) float64 {
	return el.def_t2eri_At0(i, j, k, a) +
		el.def_t2eri_At1(i, j, k, a) +
		el.def_t2eri_At2(i, j, k, a)
}

// def_t2eri_A is adcgen's definition of intermediate t2eri_A[i,j,k,a].
func (el *Elem) def_t2eri_A(i, j, k, a int) float64 {
	var v float64
	// (1)
	v += el.def_t2eri_Ag0(i, j, k, a)
	return v
}
