// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

// Package tip holds adcgen-generated ISR secular-matrix element evaluators
// for triple ionization (tip, classes 3h | 4h1p | 5h2p).
//
// Generated with schemes adc2x, ci, strict:2; blocks B00<=2, B01<=1, B11<=1, B12<=1.
// Regenerate with
//
//	python3.12 scripts/codegen/generate_adc.py --variant tip --schemes adc2x,ci,strict:2 \
//	    --outdir internal/adc/isrgen/tip
//
// fidelity_test.go (generated) replays testdata/adcgen_ref.json, an independent
// numpy evaluation of adcgen's fully expanded expressions.
package tip
