// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package tip

// hhh,phhhh vanishes at order 0.

// b01o1t0: \delta_{j n} \delta_{k o} {V^{lm}_{ia}}
func (el *Elem) b01o1t0(i, j, k, a, l, m, n, o int) float64 {
	var acc float64
	var sv11 float64
	if j == n {
		if k == o {
			sv11 += 1
		}
	}
	if sv11 != 0 {
		fv12 := el.asym(l, m, i, el.nocc+a)
		if fv12 != 0 {
			acc += sv11 * fv12
		}
	}
	return acc
}

func (el *Elem) b01o1g0(i, j, k, a, l, m, n, o int) float64 {
	return el.b01o1t0(i, j, k, a, l, m, n, o)
}

// b01o1 is the order-1 part of block hhh,phhhh, <i,j,k|M|a,l,m,n,o>.
func (el *Elem) b01o1(i, j, k, a, l, m, n, o int) float64 {
	var v float64
	// (1 - P_ij - P_ik - P_jk - P_ln - P_lo - P_mn - P_mo + P_ijP_ik + P_ijP_jk + P_ijP_ln + P_ijP_lo + P_ijP_mn + P_ijP_mo + P_ikP_ln + P_ikP_lo + P_ikP_mn + P_ikP_mo + P_jkP_ln + P_jkP_lo + P_jkP_mn + P_jkP_mo + P_lnP_mo + P_loP_mn - P_ijP_ikP_ln - P_ijP_ikP_lo - P_ijP_ikP_mn - P_ijP_ikP_mo - P_ijP_jkP_ln - P_ijP_jkP_lo - P_ijP_jkP_mn - P_ijP_jkP_mo - P_ijP_lnP_mo - P_ijP_loP_mn - P_ikP_lnP_mo - P_ikP_loP_mn)
	v += el.b01o1g0(i, j, k, a, l, m, n, o)
	v -= el.b01o1g0(j, i, k, a, l, m, n, o)
	v -= el.b01o1g0(k, j, i, a, l, m, n, o)
	v -= el.b01o1g0(i, k, j, a, l, m, n, o)
	v -= el.b01o1g0(i, j, k, a, n, m, l, o)
	v -= el.b01o1g0(i, j, k, a, o, m, n, l)
	v -= el.b01o1g0(i, j, k, a, l, n, m, o)
	v -= el.b01o1g0(i, j, k, a, l, o, n, m)
	v += el.b01o1g0(j, k, i, a, l, m, n, o)
	v += el.b01o1g0(k, i, j, a, l, m, n, o)
	v += el.b01o1g0(j, i, k, a, n, m, l, o)
	v += el.b01o1g0(j, i, k, a, o, m, n, l)
	v += el.b01o1g0(j, i, k, a, l, n, m, o)
	v += el.b01o1g0(j, i, k, a, l, o, n, m)
	v += el.b01o1g0(k, j, i, a, n, m, l, o)
	v += el.b01o1g0(k, j, i, a, o, m, n, l)
	v += el.b01o1g0(k, j, i, a, l, n, m, o)
	v += el.b01o1g0(k, j, i, a, l, o, n, m)
	v += el.b01o1g0(i, k, j, a, n, m, l, o)
	v += el.b01o1g0(i, k, j, a, o, m, n, l)
	v += el.b01o1g0(i, k, j, a, l, n, m, o)
	v += el.b01o1g0(i, k, j, a, l, o, n, m)
	v += el.b01o1g0(i, j, k, a, n, o, l, m)
	v += el.b01o1g0(i, j, k, a, o, n, m, l)
	v -= el.b01o1g0(j, k, i, a, n, m, l, o)
	v -= el.b01o1g0(j, k, i, a, o, m, n, l)
	v -= el.b01o1g0(j, k, i, a, l, n, m, o)
	v -= el.b01o1g0(j, k, i, a, l, o, n, m)
	v -= el.b01o1g0(k, i, j, a, n, m, l, o)
	v -= el.b01o1g0(k, i, j, a, o, m, n, l)
	v -= el.b01o1g0(k, i, j, a, l, n, m, o)
	v -= el.b01o1g0(k, i, j, a, l, o, n, m)
	v -= el.b01o1g0(j, i, k, a, n, o, l, m)
	v -= el.b01o1g0(j, i, k, a, o, n, m, l)
	v -= el.b01o1g0(k, j, i, a, n, o, l, m)
	v -= el.b01o1g0(k, j, i, a, o, n, m, l)
	return v
}

// B01 is block hhh,phhhh of the secular matrix,
// <i,j,k|M|a,l,m,n,o>, summed over the orders the scheme keeps.
func (el *Elem) B01(i, j, k, a, l, m, n, o int) float64 {
	var v float64
	if el.maxOrder[1] >= 1 {
		v += el.b01o1(i, j, k, a, l, m, n, o)
	}
	return v
}
