// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package tip

// b00o0t0: \delta_{j n} \delta_{k m} {f^{i}_{l}}
func (el *Elem) b00o0t0(i, j, k, l, m, n int) float64 {
	var acc float64
	var sv1 float64
	fv2 := el.fock(i, l)
	if fv2 != 0 {
		if j == n {
			sv1 += fv2
		}
	}
	if sv1 != 0 {
		if k == m {
			acc += sv1
		}
	}
	return acc
}

func (el *Elem) b00o0g0(i, j, k, l, m, n int) float64 {
	return el.b00o0t0(i, j, k, l, m, n)
}

// b00o0 is the order-0 part of block hhh,hhh, <i,j,k|M|l,m,n>.
func (el *Elem) b00o0(i, j, k, l, m, n int) float64 {
	var v float64
	// (1 - P_ij - P_ik - P_jk - P_lm - P_ln + P_ijP_ik + P_ijP_jk + P_ijP_lm + P_ijP_ln + P_ikP_lm + P_ikP_ln + P_jkP_lm + P_jkP_ln - P_ijP_ikP_lm - P_ijP_ikP_ln - P_ijP_jkP_lm - P_ijP_jkP_ln)
	v += el.b00o0g0(i, j, k, l, m, n)
	v -= el.b00o0g0(j, i, k, l, m, n)
	v -= el.b00o0g0(k, j, i, l, m, n)
	v -= el.b00o0g0(i, k, j, l, m, n)
	v -= el.b00o0g0(i, j, k, m, l, n)
	v -= el.b00o0g0(i, j, k, n, m, l)
	v += el.b00o0g0(j, k, i, l, m, n)
	v += el.b00o0g0(k, i, j, l, m, n)
	v += el.b00o0g0(j, i, k, m, l, n)
	v += el.b00o0g0(j, i, k, n, m, l)
	v += el.b00o0g0(k, j, i, m, l, n)
	v += el.b00o0g0(k, j, i, n, m, l)
	v += el.b00o0g0(i, k, j, m, l, n)
	v += el.b00o0g0(i, k, j, n, m, l)
	v -= el.b00o0g0(j, k, i, m, l, n)
	v -= el.b00o0g0(j, k, i, n, m, l)
	v -= el.b00o0g0(k, i, j, m, l, n)
	v -= el.b00o0g0(k, i, j, n, m, l)
	return v
}

// b00o1t0: \delta_{k n} {V^{ij}_{lm}}
func (el *Elem) b00o1t0(i, j, k, l, m, n int) float64 {
	var acc float64
	fv3 := el.asym(i, j, l, m)
	if fv3 != 0 {
		if k == n {
			acc += fv3
		}
	}
	return acc
}

func (el *Elem) b00o1g0(i, j, k, l, m, n int) float64 {
	return el.b00o1t0(i, j, k, l, m, n)
}

// b00o1 is the order-1 part of block hhh,hhh, <i,j,k|M|l,m,n>.
func (el *Elem) b00o1(i, j, k, l, m, n int) float64 {
	var v float64
	// (1 - P_ik - P_jk - P_ln - P_mn + P_ikP_ln + P_ikP_mn + P_jkP_ln + P_jkP_mn)
	v += el.b00o1g0(i, j, k, l, m, n)
	v -= el.b00o1g0(k, j, i, l, m, n)
	v -= el.b00o1g0(i, k, j, l, m, n)
	v -= el.b00o1g0(i, j, k, n, m, l)
	v -= el.b00o1g0(i, j, k, l, n, m)
	v += el.b00o1g0(k, j, i, n, m, l)
	v += el.b00o1g0(k, j, i, l, n, m)
	v += el.b00o1g0(i, k, j, n, m, l)
	v += el.b00o1g0(i, k, j, l, n, m)
	return v
}

// b00o2t0: - \frac{\delta_{k n} {t1^{ab}_{ij}} {V^{lm}_{ab}}}{4}
func (el *Elem) b00o2t0(i, j, k, l, m, n int) float64 {
	var acc float64
	var sv4 float64
	for a := 0; a < el.nvir; a++ {
		for b := 0; b < el.nvir; b++ {
			fv5 := el.get_t2_1(i, j, a, b)
			if fv5 != 0 {
				fv6 := el.asym(l, m, el.nocc+a, el.nocc+b)
				if fv6 != 0 {
					sv4 += fv5 * fv6
				}
			}
		}
	}
	if sv4 != 0 {
		if k == n {
			acc += sv4
		}
	}
	return -0.25 * acc
}

func (el *Elem) b00o2g0(i, j, k, l, m, n int) float64 {
	return el.b00o2t0(i, j, k, l, m, n)
}

// b00o2t1: - \frac{\delta_{j n} \delta_{k m} {t1^{ab}_{io}} {V^{lo}_{ab}}}{4}
func (el *Elem) b00o2t1(i, j, k, l, m, n int) float64 {
	var acc float64
	var sv7 float64
	var sv8 float64
	for o := 0; o < el.nocc; o++ {
		for a := 0; a < el.nvir; a++ {
			for b := 0; b < el.nvir; b++ {
				fv9 := el.get_t2_1(i, o, a, b)
				if fv9 != 0 {
					fv10 := el.asym(l, o, el.nocc+a, el.nocc+b)
					if fv10 != 0 {
						sv8 += fv9 * fv10
					}
				}
			}
		}
	}
	if sv8 != 0 {
		if j == n {
			sv7 += sv8
		}
	}
	if sv7 != 0 {
		if k == m {
			acc += sv7
		}
	}
	return -0.25 * acc
}

func (el *Elem) b00o2g1(i, j, k, l, m, n int) float64 {
	return el.b00o2t1(i, j, k, l, m, n)
}

// b00o2 is the order-2 part of block hhh,hhh, <i,j,k|M|l,m,n>.
func (el *Elem) b00o2(i, j, k, l, m, n int) float64 {
	var v float64
	// (1 - P_ik - P_jk - P_ln - P_mn + P_ikP_ln + P_ikP_mn + P_jkP_ln + P_jkP_mn + P_ilP_jmP_kn + P_ilP_jnP_km + P_imP_jnP_kl + P_inP_jlP_km + P_inP_jmP_kl - P_ikP_ilP_jmP_kn - P_ikP_imP_jlP_kn - P_ikP_inP_jlP_km - P_ilP_jkP_jnP_km)
	v += el.b00o2g0(i, j, k, l, m, n)
	v -= el.b00o2g0(k, j, i, l, m, n)
	v -= el.b00o2g0(i, k, j, l, m, n)
	v -= el.b00o2g0(i, j, k, n, m, l)
	v -= el.b00o2g0(i, j, k, l, n, m)
	v += el.b00o2g0(k, j, i, n, m, l)
	v += el.b00o2g0(k, j, i, l, n, m)
	v += el.b00o2g0(i, k, j, n, m, l)
	v += el.b00o2g0(i, k, j, l, n, m)
	v += el.b00o2g0(l, m, n, i, j, k)
	v += el.b00o2g0(l, n, m, i, k, j)
	v += el.b00o2g0(m, n, l, k, i, j)
	v += el.b00o2g0(n, l, m, j, k, i)
	v += el.b00o2g0(n, m, l, k, j, i)
	v -= el.b00o2g0(n, m, l, i, j, k)
	v -= el.b00o2g0(n, l, m, j, i, k)
	v -= el.b00o2g0(m, l, n, j, k, i)
	v -= el.b00o2g0(l, m, n, i, k, j)
	// (1 - P_ij - P_ik - P_jk - P_lm - P_ln + P_ijP_ik + P_ijP_jk + P_ijP_lm + P_ijP_ln + P_ikP_lm + P_ikP_ln + P_jkP_lm + P_jkP_ln - P_ijP_ikP_lm - P_ijP_ikP_ln - P_ijP_jkP_lm - P_ijP_jkP_ln + P_ilP_jmP_kn + P_imP_jlP_kn + P_imP_jnP_kl + P_inP_jlP_km + P_inP_jmP_kl - P_ijP_ilP_jmP_kn - P_ijP_ilP_jnP_km - P_ijP_imP_jlP_kn - P_ijP_imP_jnP_kl - P_ijP_inP_jmP_kl - P_ikP_imP_jlP_kn - P_ikP_imP_jnP_kl - P_ikP_inP_jlP_km - P_ilP_jkP_jmP_kn + P_ijP_ikP_ilP_jmP_kn + P_ijP_ikP_ilP_jnP_km + P_ijP_ikP_imP_jlP_kn + P_ijP_imP_jkP_jnP_kl)
	v += el.b00o2g1(i, j, k, l, m, n)
	v -= el.b00o2g1(j, i, k, l, m, n)
	v -= el.b00o2g1(k, j, i, l, m, n)
	v -= el.b00o2g1(i, k, j, l, m, n)
	v -= el.b00o2g1(i, j, k, m, l, n)
	v -= el.b00o2g1(i, j, k, n, m, l)
	v += el.b00o2g1(j, k, i, l, m, n)
	v += el.b00o2g1(k, i, j, l, m, n)
	v += el.b00o2g1(j, i, k, m, l, n)
	v += el.b00o2g1(j, i, k, n, m, l)
	v += el.b00o2g1(k, j, i, m, l, n)
	v += el.b00o2g1(k, j, i, n, m, l)
	v += el.b00o2g1(i, k, j, m, l, n)
	v += el.b00o2g1(i, k, j, n, m, l)
	v -= el.b00o2g1(j, k, i, m, l, n)
	v -= el.b00o2g1(j, k, i, n, m, l)
	v -= el.b00o2g1(k, i, j, m, l, n)
	v -= el.b00o2g1(k, i, j, n, m, l)
	v += el.b00o2g1(l, m, n, i, j, k)
	v += el.b00o2g1(m, l, n, j, i, k)
	v += el.b00o2g1(m, n, l, k, i, j)
	v += el.b00o2g1(n, l, m, j, k, i)
	v += el.b00o2g1(n, m, l, k, j, i)
	v -= el.b00o2g1(m, l, n, i, j, k)
	v -= el.b00o2g1(n, l, m, i, k, j)
	v -= el.b00o2g1(l, m, n, j, i, k)
	v -= el.b00o2g1(n, m, l, k, i, j)
	v -= el.b00o2g1(m, n, l, k, j, i)
	v -= el.b00o2g1(n, l, m, j, i, k)
	v -= el.b00o2g1(l, n, m, k, i, j)
	v -= el.b00o2g1(m, l, n, j, k, i)
	v -= el.b00o2g1(l, n, m, i, j, k)
	v += el.b00o2g1(m, n, l, i, j, k)
	v += el.b00o2g1(n, m, l, i, k, j)
	v += el.b00o2g1(l, n, m, j, i, k)
	v += el.b00o2g1(l, m, n, k, i, j)
	return v
}

// B00 is block hhh,hhh of the secular matrix,
// <i,j,k|M|l,m,n>, summed over the orders the scheme keeps.
func (el *Elem) B00(i, j, k, l, m, n int) float64 {
	var v float64
	if el.maxOrder[0] >= 0 {
		v += el.b00o0(i, j, k, l, m, n)
	}
	if el.maxOrder[0] >= 1 {
		v += el.b00o1(i, j, k, l, m, n)
	}
	if el.maxOrder[0] >= 2 {
		v += el.b00o2(i, j, k, l, m, n)
	}
	return v
}
