// Package khci implements a generic k-hole configuration-interaction engine: N-k electron
// states of a closed-shell reference, spanned by the excitation classes
//
//	kh | (k+1)h1p | (k+2)h2p
//
// in spin-orbital determinants relative to the RHF reference. k = 1 is single
// ionization (1h | 2h1p | 3h2p, the SIP ADC(2,2) space), k = 2 double, k = 3 triple and
// k = 4 quadruple (4h | 5h1p | 6h2p).
//
// space.go is the configuration space; ci.go is the CI Hamiltonian H - E_HF over it.
//
// # Spin orbitals
//
// Occupied spatial orbital i carries spin orbitals 2i (alpha) and 2i+1 (beta), so the
// occupied spin orbitals are 0..2*NOcc-1 and fit a uint64 hole mask (NOcc <= 32).
// Virtual spatial orbital v carries relative spin orbitals 2v and 2v+1. Their absolute
// index is 2*NOcc + that, which puts every virtual above every occupied spin orbital.
// Spin orbital p has spatial orbital p>>1 and spin p&1. This is the convention of
// scripts/codegen/generate_adc.py and of the isrgen packages generated from it.
//
// # Phase convention
//
// Row r with holes i1 < i2 < ... < in and particles a1 < a2 (spin-orbital indices) is
//
//	|r> = c†_{a1} c†_{a2} c_{i1} c_{i2} ... c_{in} |Phi_0>,
//
// operators written left to right in ascending index order within each kind. This is
// adcgen's precursor-state operator string (excitation_operator(creation=virt,
// annihilation=occ, reverse_annihilation=False) with ascending target indices), so
// secular-matrix elements generated by adcgen and CI elements evaluated in this
// basis agree sign for sign. Det gives each row's canonical determinant and the sign
// relating the two.
//
// # Row order
//
// Rows are class-major (k first), which makes the main class a leading block as
// fano.Space requires. Within a class they are grouped by hole set: all rows sharing
// a hole mask are contiguous, in ascending particle-tuple order, and hole sets appear
// in ascending order of their sorted hole list. Grouping by hole set is what the CI
// applier walks: Slater-Condon couplings are organized by hole-set differences.
package khci

import (
	"fmt"
	"math/bits"
	"slices"

	"github.com/leiaSQ/ADCgo/internal/adc/parallel"
)

// VirKind classifies a virtual spatial orbital for the free-particle limit of the top
// class (a "free" orbital belongs to no atom; see fano.ParseConfigRule).
type VirKind uint8

const (
	// Compact virtuals are assigned to an atom.
	Compact VirKind = iota
	// Free virtuals are the diffuse / ghost-centre complement.
	Free
)

// Options defines a configuration space.
type Options struct {
	K    int // main-class hole count, 1..4
	NOcc int // doubly occupied spatial orbitals of the reference, 2*NOcc <= 64
	NVir int // virtual spatial orbitals

	// TwoMs is 2*Ms of the N-K electron states. AllMs keeps every Ms instead, for
	// combinatorial checks; the Hamiltonian conserves Ms, so a production space uses one.
	TwoMs int
	AllMs bool

	// OrbSym is the 0-based point-group irrep of every spatial orbital (occupied first,
	// length NOcc+NVir), with the direct product given by XOR (D2h and its subgroups).
	// Nil switches symmetry off. TargetIrrep is the irrep of the states: the XOR of the
	// irreps of all holes and particles.
	OrbSym      []int
	TargetIrrep int

	// MaxClass is the highest class as a hole count, K..K+2. Zero means K+2.
	MaxClass int

	// VirKind labels each virtual spatial orbital (length NVir). Nil means all Compact.
	// With LimitFree set, (K+2)h2p rows keep at most MaxFreeTop Free particles; 1 drops
	// continuum-continuum pairs. An explicit flag, not a sentinel:
	// a zero-valued MaxFreeTop must not silently mean "no free particles".
	VirKind    []VirKind
	LimitFree  bool
	MaxFreeTop int
}

// row is one configuration. p holds relative virtual spin-orbital indices, -1 unused.
type row struct {
	holes uint64
	p     [2]int16
}

// ptab is the particle-tuple table shared by every hole set of one block type
// (particle count, required particle spin sum, required particle irrep).
type ptab struct {
	m     int
	tups  [][2]int16 // allowed tuples, ascending
	pos1  []int32    // m == 1: tuple position of particle a, or -1
	pos2  []int32    // m == 2: tuple position of (a,b) at a*nv2+b, a < b, or -1
	count int
}

type block struct {
	start int
	tab   *ptab
}

// Space is a k-hole configuration space. It is immutable after construction and safe
// for concurrent reads.
type Space struct {
	opt  Options
	nso  int // occupied spin orbitals, 2*NOcc
	nv2  int // virtual spin orbitals, 2*NVir
	rows []row

	classStart []int // classStart[c-K] is the first row of class c; one extra end entry
	blocks     map[uint64]block

	// parent is non-nil for a restricted space: parent[r] is row r's index in the
	// parent, and parentToSub maps back (-1 when the parent row was dropped).
	parent      []int
	parentToSub []int32
	base        *Space // the unrestricted space the rows came from
}

// spin sign (+1 alpha, -1 beta) of a spin orbital.
func msOf(p int) int { return 1 - 2*(p&1) }

// NewSpace enumerates the configurations.
func NewSpace(o Options) (*Space, error) {
	if o.K < 1 || o.K > 4 {
		return nil, fmt.Errorf("khci: K=%d outside 1..4", o.K)
	}
	if o.NOcc < 1 || 2*o.NOcc > 64 {
		return nil, fmt.Errorf("khci: NOcc=%d outside 1..32 (the hole mask is a uint64)", o.NOcc)
	}
	if o.NVir < 0 || 2*o.NVir > 32767 {
		return nil, fmt.Errorf("khci: NVir=%d outside 0..16383", o.NVir)
	}
	if o.MaxClass == 0 {
		o.MaxClass = o.K + 2
	}
	if o.MaxClass < o.K || o.MaxClass > o.K+2 {
		return nil, fmt.Errorf("khci: MaxClass=%d outside K..K+2 = %d..%d", o.MaxClass, o.K, o.K+2)
	}
	if o.MaxClass > 2*o.NOcc {
		return nil, fmt.Errorf("khci: MaxClass=%d holes but only %d occupied spin orbitals",
			o.MaxClass, 2*o.NOcc)
	}
	if o.OrbSym != nil && len(o.OrbSym) != o.NOcc+o.NVir {
		return nil, fmt.Errorf("khci: OrbSym has %d entries, want NOcc+NVir = %d",
			len(o.OrbSym), o.NOcc+o.NVir)
	}
	if o.VirKind != nil && len(o.VirKind) != o.NVir {
		return nil, fmt.Errorf("khci: VirKind has %d entries, want NVir = %d", len(o.VirKind), o.NVir)
	}
	if o.LimitFree && (o.VirKind == nil || o.MaxFreeTop < 0 || o.MaxFreeTop > 2) {
		return nil, fmt.Errorf("khci: LimitFree needs VirKind and MaxFreeTop in 0..2 (got %d)",
			o.MaxFreeTop)
	}
	if !o.AllMs {
		// N - K electrons with N = 2*NOcc even: 2Ms has the parity of K.
		if (o.TwoMs-o.K)%2 != 0 {
			return nil, fmt.Errorf("khci: TwoMs=%d has the wrong parity for %d removed electrons",
				o.TwoMs, o.K)
		}
	}
	s := &Space{opt: o, nso: 2 * o.NOcc, nv2: 2 * o.NVir, blocks: map[uint64]block{}}
	s.enumerate()
	s.base = s
	return s, nil
}

func (s *Space) irrepOcc(p int) int {
	if s.opt.OrbSym == nil {
		return 0
	}
	return s.opt.OrbSym[p>>1]
}

func (s *Space) irrepVir(a int) int {
	if s.opt.OrbSym == nil {
		return 0
	}
	return s.opt.OrbSym[s.opt.NOcc+(a>>1)]
}

func (s *Space) isFree(a int) bool {
	return s.opt.VirKind != nil && s.opt.VirKind[a>>1] == Free
}

// tabKey identifies a particle table: particle count, required spin sum, required irrep.
type tabKey struct{ m, spin, irrep int }

func (s *Space) buildTab(k tabKey) *ptab {
	t := &ptab{m: k.m}
	ok := func(spin, irrep int) bool {
		return (s.opt.AllMs || spin == k.spin) && irrep == k.irrep
	}
	switch k.m {
	case 0:
		if ok(0, 0) {
			t.tups = append(t.tups, [2]int16{-1, -1})
		}
	case 1:
		t.pos1 = make([]int32, s.nv2)
		for a := range s.nv2 {
			t.pos1[a] = -1
			if ok(msOf(a), s.irrepVir(a)) {
				t.pos1[a] = int32(len(t.tups))
				t.tups = append(t.tups, [2]int16{int16(a), -1})
			}
		}
	case 2:
		t.pos2 = make([]int32, s.nv2*s.nv2)
		for i := range t.pos2 {
			t.pos2[i] = -1
		}
		for a := range s.nv2 {
			for b := a + 1; b < s.nv2; b++ {
				if !ok(msOf(a)+msOf(b), s.irrepVir(a)^s.irrepVir(b)) {
					continue
				}
				if s.opt.LimitFree {
					nf := 0
					if s.isFree(a) {
						nf++
					}
					if s.isFree(b) {
						nf++
					}
					if nf > s.opt.MaxFreeTop {
						continue
					}
				}
				t.pos2[a*s.nv2+b] = int32(len(t.tups))
				t.tups = append(t.tups, [2]int16{int16(a), int16(b)})
			}
		}
	}
	t.count = len(t.tups)
	return t
}

// holeSets returns every n-subset of the nso occupied spin orbitals as a mask, in
// ascending lexicographic order of the sorted hole list.
func holeSets(nso, n int) []uint64 {
	var out []uint64
	idx := make([]int, n)
	for i := range idx {
		idx[i] = i
	}
	if n > nso {
		return nil
	}
	for {
		var m uint64
		for _, p := range idx {
			m |= 1 << uint(p)
		}
		out = append(out, m)
		// advance to the next combination in lexicographic order
		i := n - 1
		for i >= 0 && idx[i] == nso-n+i {
			i--
		}
		if i < 0 {
			return out
		}
		idx[i]++
		for j := i + 1; j < n; j++ {
			idx[j] = idx[j-1] + 1
		}
	}
}

func (s *Space) enumerate() {
	K := s.opt.K
	tabs := map[tabKey]*ptab{}
	s.classStart = make([]int, 0, s.opt.MaxClass-K+2)
	total := 0
	type plan struct {
		sets  []uint64
		tabs  []*ptab
		start []int
	}
	plans := make([]plan, 0, s.opt.MaxClass-K+1)
	for c := K; c <= s.opt.MaxClass; c++ {
		m := c - K
		s.classStart = append(s.classStart, total)
		if m > 0 && s.nv2 == 0 {
			plans = append(plans, plan{})
			continue
		}
		sets := holeSets(s.nso, c)
		pl := plan{tabs: make([]*ptab, 0, len(sets)), start: make([]int, 0, len(sets))}
		for _, hm := range sets {
			spin, irrep := s.opt.TwoMs, s.opt.TargetIrrep
			for q := hm; q != 0; q &= q - 1 {
				p := bits.TrailingZeros64(q)
				spin += msOf(p) // the holes' spins are removed: particles must restore them
				irrep ^= s.irrepOcc(p)
			}
			key := tabKey{m, spin, irrep}
			if s.opt.AllMs {
				key.spin = 0
			}
			t, ok := tabs[key]
			if !ok {
				t = s.buildTab(key)
				tabs[key] = t
			}
			if t.count == 0 {
				continue
			}
			pl.sets = append(pl.sets, hm)
			pl.tabs = append(pl.tabs, t)
			pl.start = append(pl.start, total)
			s.blocks[hm] = block{start: total, tab: t}
			total += t.count
		}
		plans = append(plans, pl)
	}
	s.classStart = append(s.classStart, total)
	s.rows = make([]row, total)
	for _, pl := range plans {
		n := len(pl.sets)
		parallel.Chunks(n, parallel.ChunkWorkers(n), func(_, lo, hi int) {
			for i := lo; i < hi; i++ {
				r := pl.start[i]
				for _, tp := range pl.tabs[i].tups {
					s.rows[r] = row{holes: pl.sets[i], p: tp}
					r++
				}
			}
		})
	}
}

// Options returns the options the space was built with (MaxClass resolved).
func (s *Space) Options() Options { return s.opt }

// K is the main-class hole count.
func (s *Space) K() int { return s.opt.K }

// Size is the number of configurations.
func (s *Space) Size() int { return len(s.rows) }

// MainBlockSize is the number of kh (main-class) configurations; they come first.
func (s *Space) MainBlockSize() int { return s.ClassEnd(s.opt.K) }

// ClassStart and ClassEnd bound the rows of class c (a hole count, K..MaxClass).
func (s *Space) ClassStart(c int) int { return s.classBound(c) }
func (s *Space) ClassEnd(c int) int   { return s.classBound(c + 1) }

func (s *Space) classBound(c int) int {
	i := c - s.opt.K
	if i < 0 {
		return 0
	}
	if i >= len(s.classStart) {
		return len(s.rows)
	}
	return s.classStart[i]
}

// Class is row's hole count.
func (s *Space) Class(r int) int { return bits.OnesCount64(s.rows[r].holes) }

// HoleMask is row's occupied spin-orbital hole mask.
func (s *Space) HoleMask(r int) uint64 { return s.rows[r].holes }

// PartSO appends row's particles as relative virtual spin-orbital indices (ascending).
func (s *Space) PartSO(r int, dst []int) []int {
	for _, a := range s.rows[r].p {
		if a >= 0 {
			dst = append(dst, int(a))
		}
	}
	return dst
}

// Holes appends row's holes as SPATIAL occupied orbitals, ascending, a doubly
// emptied orbital appearing twice. This is the fano.Space contract that the scheme A
// selectors count against.
func (s *Space) Holes(r int, dst []int) []int {
	for q := s.rows[r].holes; q != 0; q &= q - 1 {
		dst = append(dst, bits.TrailingZeros64(q)>>1)
	}
	return dst
}

// Particles appends row's particles as SPATIAL virtual orbitals (0-based positions in
// the virtual block), ascending, a doubly filled orbital appearing twice.
func (s *Space) Particles(r int, dst []int) []int {
	for _, a := range s.rows[r].p {
		if a >= 0 {
			dst = append(dst, int(a)>>1)
		}
	}
	return dst
}

// Index returns the row of the configuration with this hole mask and these particles
// (relative virtual spin orbitals, any order), and whether it is in the space.
func (s *Space) Index(holes uint64, parts []int) (int, bool) {
	if s.parent != nil {
		pr, ok := s.base.Index(holes, parts)
		if !ok {
			return 0, false
		}
		sub := s.parentToSub[pr]
		return int(sub), sub >= 0
	}
	b, ok := s.blocks[holes]
	if !ok || len(parts) != b.tab.m {
		return 0, false
	}
	var pos int32
	switch b.tab.m {
	case 0:
		pos = 0
	case 1:
		a := parts[0]
		if a < 0 || a >= s.nv2 {
			return 0, false
		}
		pos = b.tab.pos1[a]
	case 2:
		a, c := parts[0], parts[1]
		if a > c {
			a, c = c, a
		}
		if a < 0 || c >= s.nv2 || a == c {
			return 0, false
		}
		pos = b.tab.pos2[a*s.nv2+c]
	}
	if pos < 0 {
		return 0, false
	}
	return b.start + int(pos), true
}

// Parent maps row r of a restricted space to the unrestricted space's row; for an
// unrestricted space it is the identity.
func (s *Space) Parent(r int) int {
	if s.parent == nil {
		return r
	}
	return s.parent[r]
}

// Restrict returns the sub-space spanned by the given rows, which must be ascending and
// distinct. Class bands stay contiguous because the parent order is kept, so the result
// is a Space in its own right (MainBlockSize, ClassStart, Index all work on it). Row
// indices of the result map back through Parent to the UNRESTRICTED space, also when s
// is itself restricted.
func (s *Space) Restrict(rows []int) (*Space, error) {
	for i, r := range rows {
		if r < 0 || r >= len(s.rows) {
			return nil, fmt.Errorf("khci: Restrict row %d outside 0..%d", r, len(s.rows)-1)
		}
		if i > 0 && r <= rows[i-1] {
			return nil, fmt.Errorf("khci: Restrict rows not strictly ascending at %d", i)
		}
	}
	out := &Space{opt: s.opt, nso: s.nso, nv2: s.nv2, base: s.base}
	out.rows = make([]row, len(rows))
	out.parent = make([]int, len(rows))
	out.parentToSub = make([]int32, len(s.base.rows))
	for i := range out.parentToSub {
		out.parentToSub[i] = -1
	}
	for i, r := range rows {
		out.rows[i] = s.rows[r]
		out.parent[i] = s.Parent(r)
		out.parentToSub[out.parent[i]] = int32(i)
	}
	out.classStart = make([]int, 0, len(s.classStart))
	for c := s.opt.K; c <= s.opt.MaxClass+1; c++ {
		out.classStart = append(out.classStart, sort32(out.rows, c))
	}
	return out, nil
}

// sort32 is the first index whose class is >= c (rows are class-major).
func sort32(rows []row, c int) int {
	lo, hi := 0, len(rows)
	for lo < hi {
		mid := (lo + hi) / 2
		if bits.OnesCount64(rows[mid].holes) < c {
			lo = mid + 1
		} else {
			hi = mid
		}
	}
	return lo
}

// Det is a row's determinant: the occupied spin orbitals of the reference that are
// still filled (as a mask), the particles as ABSOLUTE spin-orbital indices (ascending),
// and the sign with |row> = sign * |canonical determinant>, where the canonical
// determinant creates its occupied spin orbitals in ascending absolute order,
// c†_{p1} c†_{p2} ... |vac> with p1 < p2 < ....
func (s *Space) Det(r int) (occ uint64, parts []int, sign float64) {
	rw := s.rows[r]
	sign = 1
	full := uint64(1)<<uint(s.nso) - 1
	if s.nso == 64 {
		full = ^uint64(0)
	}
	occ = full
	// c_{i1} c_{i2} ... c_{in} acts right to left: the largest hole is removed first.
	// c_p on a canonical determinant gives (-1)^(number of filled orbitals below p).
	hs := make([]int, 0, 8)
	for q := rw.holes; q != 0; q &= q - 1 {
		hs = append(hs, bits.TrailingZeros64(q))
	}
	for j := len(hs) - 1; j >= 0; j-- {
		p := hs[j]
		below := bits.OnesCount64(occ & (uint64(1)<<uint(p) - 1))
		if below&1 == 1 {
			sign = -sign
		}
		occ &^= 1 << uint(p)
	}
	// c†_{a1} c†_{a2}: a2 is created first, then a1. Every remaining occupied spin
	// orbital lies below every virtual one; a created particle also counts for the
	// particles created before it that lie below it.
	nfilled := bits.OnesCount64(occ)
	var ps []int
	for _, a := range rw.p {
		if a >= 0 {
			ps = append(ps, s.nso+int(a))
		}
	}
	created := make([]int, 0, 2)
	for j := len(ps) - 1; j >= 0; j-- {
		x := ps[j]
		below := nfilled
		for _, y := range created {
			if y < x {
				below++
			}
		}
		if below&1 == 1 {
			sign = -sign
		}
		created = append(created, x)
	}
	slices.Sort(ps)
	return occ, ps, sign
}

// String summarizes the space for the run log.
func (s *Space) String() string {
	o := s.opt
	counts := make([]string, 0, o.MaxClass-o.K+1)
	for c := o.K; c <= o.MaxClass; c++ {
		counts = append(counts, fmt.Sprintf("%dh%dp=%d", c, c-o.K, s.ClassEnd(c)-s.ClassStart(c)))
	}
	ms := fmt.Sprintf("2Ms=%d", o.TwoMs)
	if o.AllMs {
		ms = "all Ms"
	}
	return fmt.Sprintf("khci space k=%d NOcc=%d NVir=%d %s irrep=%d: %v (total %d)",
		o.K, o.NOcc, o.NVir, ms, o.TargetIrrep, counts, len(s.rows))
}
