// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

// Package dip holds adcgen-generated ISR secular-matrix element evaluators
// for double ionization (dip, classes 2h | 3h1p | 4h2p).
//
// Generated with schemes adc2x, ci, strict:2; blocks B00<=2, B01<=1, B11<=1, B02<=1, B12<=1, B22<=1.
// Regenerate with
//
//	python3.12 scripts/codegen/generate_adc.py --variant dip --schemes adc2x,ci,strict:2 \
//	    --outdir internal/adc/isrgen/dip
//
// fidelity_test.go (generated) replays testdata/adcgen_ref.json, an independent
// numpy evaluation of adcgen's fully expanded expressions.
package dip
