// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package dip

// b11o0t0: \delta_{i l} \delta_{j m} \delta_{k n} {f^{a}_{b}}
func (el *Elem) b11o0t0(a, i, j, k, b, l, m, n int) float64 {
	var acc float64
	var sv9 float64
	if j == m {
		if k == n {
			sv9 += 1
		}
	}
	if sv9 != 0 {
		var sv10 float64
		fv11 := el.fock(el.nocc+a, el.nocc+b)
		if fv11 != 0 {
			if i == l {
				sv10 += fv11
			}
		}
		if sv10 != 0 {
			acc += sv9 * sv10
		}
	}
	return acc
}

func (el *Elem) b11o0g0(a, i, j, k, b, l, m, n int) float64 {
	return el.b11o0t0(a, i, j, k, b, l, m, n)
}

// b11o0t1: \delta_{a b} \delta_{j n} \delta_{k m} {f^{i}_{l}}
func (el *Elem) b11o0t1(a, i, j, k, b, l, m, n int) float64 {
	var acc float64
	var sv12 float64
	if j == n {
		if k == m {
			sv12 += 1
		}
	}
	if sv12 != 0 {
		var sv13 float64
		fv14 := el.fock(i, l)
		if fv14 != 0 {
			if a == b {
				sv13 += fv14
			}
		}
		if sv13 != 0 {
			acc += sv12 * sv13
		}
	}
	return acc
}

func (el *Elem) b11o0g1(a, i, j, k, b, l, m, n int) float64 {
	return el.b11o0t1(a, i, j, k, b, l, m, n)
}

// b11o0 is the order-0 part of block phhh,phhh, <a,i,j,k|M|b,l,m,n>.
func (el *Elem) b11o0(a, i, j, k, b, l, m, n int) float64 {
	var v float64
	// (1 - P_ij - P_ik - P_jk + P_ijP_ik + P_ijP_jk)
	v += el.b11o0g0(a, i, j, k, b, l, m, n)
	v -= el.b11o0g0(a, j, i, k, b, l, m, n)
	v -= el.b11o0g0(a, k, j, i, b, l, m, n)
	v -= el.b11o0g0(a, i, k, j, b, l, m, n)
	v += el.b11o0g0(a, j, k, i, b, l, m, n)
	v += el.b11o0g0(a, k, i, j, b, l, m, n)
	// (1 - P_ij - P_ik - P_jk - P_lm - P_ln + P_ijP_ik + P_ijP_jk + P_ijP_lm + P_ijP_ln + P_ikP_lm + P_ikP_ln + P_jkP_lm + P_jkP_ln - P_ijP_ikP_lm - P_ijP_ikP_ln - P_ijP_jkP_lm - P_ijP_jkP_ln)
	v += el.b11o0g1(a, i, j, k, b, l, m, n)
	v -= el.b11o0g1(a, j, i, k, b, l, m, n)
	v -= el.b11o0g1(a, k, j, i, b, l, m, n)
	v -= el.b11o0g1(a, i, k, j, b, l, m, n)
	v -= el.b11o0g1(a, i, j, k, b, m, l, n)
	v -= el.b11o0g1(a, i, j, k, b, n, m, l)
	v += el.b11o0g1(a, j, k, i, b, l, m, n)
	v += el.b11o0g1(a, k, i, j, b, l, m, n)
	v += el.b11o0g1(a, j, i, k, b, m, l, n)
	v += el.b11o0g1(a, j, i, k, b, n, m, l)
	v += el.b11o0g1(a, k, j, i, b, m, l, n)
	v += el.b11o0g1(a, k, j, i, b, n, m, l)
	v += el.b11o0g1(a, i, k, j, b, m, l, n)
	v += el.b11o0g1(a, i, k, j, b, n, m, l)
	v -= el.b11o0g1(a, j, k, i, b, m, l, n)
	v -= el.b11o0g1(a, j, k, i, b, n, m, l)
	v -= el.b11o0g1(a, k, i, j, b, m, l, n)
	v -= el.b11o0g1(a, k, i, j, b, n, m, l)
	return v
}

// b11o1t0: \delta_{j n} \delta_{k m} {V^{ib}_{la}}
func (el *Elem) b11o1t0(a, i, j, k, b, l, m, n int) float64 {
	var acc float64
	var sv15 float64
	if j == n {
		if k == m {
			sv15 += 1
		}
	}
	if sv15 != 0 {
		fv16 := el.asym(i, el.nocc+b, l, el.nocc+a)
		if fv16 != 0 {
			acc += sv15 * fv16
		}
	}
	return acc
}

func (el *Elem) b11o1g0(a, i, j, k, b, l, m, n int) float64 {
	return el.b11o1t0(a, i, j, k, b, l, m, n)
}

// b11o1t1: \delta_{a b} \delta_{k n} {V^{ij}_{lm}}
func (el *Elem) b11o1t1(a, i, j, k, b, l, m, n int) float64 {
	var acc float64
	var sv17 float64
	if a == b {
		if k == n {
			sv17 += 1
		}
	}
	if sv17 != 0 {
		fv18 := el.asym(i, j, l, m)
		if fv18 != 0 {
			acc += sv17 * fv18
		}
	}
	return acc
}

func (el *Elem) b11o1g1(a, i, j, k, b, l, m, n int) float64 {
	return el.b11o1t1(a, i, j, k, b, l, m, n)
}

// b11o1 is the order-1 part of block phhh,phhh, <a,i,j,k|M|b,l,m,n>.
func (el *Elem) b11o1(a, i, j, k, b, l, m, n int) float64 {
	var v float64
	// (1 - P_ij - P_ik - P_jk - P_lm - P_ln + P_ijP_ik + P_ijP_jk + P_ijP_lm + P_ijP_ln + P_ikP_lm + P_ikP_ln + P_jkP_lm + P_jkP_ln - P_ijP_ikP_lm - P_ijP_ikP_ln - P_ijP_jkP_lm - P_ijP_jkP_ln)
	v += el.b11o1g0(a, i, j, k, b, l, m, n)
	v -= el.b11o1g0(a, j, i, k, b, l, m, n)
	v -= el.b11o1g0(a, k, j, i, b, l, m, n)
	v -= el.b11o1g0(a, i, k, j, b, l, m, n)
	v -= el.b11o1g0(a, i, j, k, b, m, l, n)
	v -= el.b11o1g0(a, i, j, k, b, n, m, l)
	v += el.b11o1g0(a, j, k, i, b, l, m, n)
	v += el.b11o1g0(a, k, i, j, b, l, m, n)
	v += el.b11o1g0(a, j, i, k, b, m, l, n)
	v += el.b11o1g0(a, j, i, k, b, n, m, l)
	v += el.b11o1g0(a, k, j, i, b, m, l, n)
	v += el.b11o1g0(a, k, j, i, b, n, m, l)
	v += el.b11o1g0(a, i, k, j, b, m, l, n)
	v += el.b11o1g0(a, i, k, j, b, n, m, l)
	v -= el.b11o1g0(a, j, k, i, b, m, l, n)
	v -= el.b11o1g0(a, j, k, i, b, n, m, l)
	v -= el.b11o1g0(a, k, i, j, b, m, l, n)
	v -= el.b11o1g0(a, k, i, j, b, n, m, l)
	// (1 - P_ik - P_jk - P_ln - P_mn + P_ikP_ln + P_ikP_mn + P_jkP_ln + P_jkP_mn)
	v += el.b11o1g1(a, i, j, k, b, l, m, n)
	v -= el.b11o1g1(a, k, j, i, b, l, m, n)
	v -= el.b11o1g1(a, i, k, j, b, l, m, n)
	v -= el.b11o1g1(a, i, j, k, b, n, m, l)
	v -= el.b11o1g1(a, i, j, k, b, l, n, m)
	v += el.b11o1g1(a, k, j, i, b, n, m, l)
	v += el.b11o1g1(a, k, j, i, b, l, n, m)
	v += el.b11o1g1(a, i, k, j, b, n, m, l)
	v += el.b11o1g1(a, i, k, j, b, l, n, m)
	return v
}

// B11 is block phhh,phhh of the secular matrix,
// <a,i,j,k|M|b,l,m,n>, summed over the orders the scheme keeps.
func (el *Elem) B11(a, i, j, k, b, l, m, n int) float64 {
	var v float64
	if el.maxOrder[2] >= 0 {
		v += el.b11o0(a, i, j, k, b, l, m, n)
	}
	if el.maxOrder[2] >= 1 {
		v += el.b11o1(a, i, j, k, b, l, m, n)
	}
	return v
}
