// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package dip

// hh,pphhhh vanishes at order 0.

// hh,pphhhh vanishes at order 1.

// B02 is block hh,pphhhh of the secular matrix,
// <i,j|M|a,b,k,l,m,n>, summed over the orders the scheme keeps.
func (el *Elem) B02(i, j, a, b, k, l, m, n int) float64 {
	var v float64
	return v
}
