// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package dip

// phhh,pphhhh vanishes at order 0.

// b12o1t0: \delta_{i m} \delta_{j o} \delta_{k n} {V^{la}_{bc}}
func (el *Elem) b12o1t0(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv19 := el.asym(l, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv19 != 0 {
		if i == m {
			if j == o {
				if k == n {
					acc += fv19
				}
			}
		}
	}
	return acc
}

// b12o1t1: \delta_{i n} \delta_{j m} \delta_{k o} {V^{la}_{bc}}
func (el *Elem) b12o1t1(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv20 := el.asym(l, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv20 != 0 {
		if i == n {
			if j == m {
				if k == o {
					acc += fv20
				}
			}
		}
	}
	return acc
}

// b12o1t2: \delta_{i o} \delta_{j n} \delta_{k m} {V^{la}_{bc}}
func (el *Elem) b12o1t2(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv21 := el.asym(l, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv21 != 0 {
		if i == o {
			if j == n {
				if k == m {
					acc += fv21
				}
			}
		}
	}
	return acc
}

// b12o1t3: \delta_{a c} \delta_{j o} \delta_{k n} {V^{lm}_{ib}}
func (el *Elem) b12o1t3(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv22 := el.asym(l, m, i, el.nocc+b)
	if fv22 != 0 {
		if a == c {
			if j == o {
				if k == n {
					acc += fv22
				}
			}
		}
	}
	return acc
}

// b12o1t4: \delta_{a b} \delta_{j n} \delta_{k o} {V^{lm}_{ic}}
func (el *Elem) b12o1t4(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv23 := el.asym(l, m, i, el.nocc+c)
	if fv23 != 0 {
		if a == b {
			if j == n {
				if k == o {
					acc += fv23
				}
			}
		}
	}
	return acc
}

// b12o1t5: \delta_{a c} \delta_{i n} \delta_{k o} {V^{lm}_{jb}}
func (el *Elem) b12o1t5(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv24 := el.asym(l, m, j, el.nocc+b)
	if fv24 != 0 {
		if a == c {
			if i == n {
				if k == o {
					acc += fv24
				}
			}
		}
	}
	return acc
}

// b12o1t6: \delta_{a b} \delta_{i o} \delta_{k n} {V^{lm}_{jc}}
func (el *Elem) b12o1t6(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv25 := el.asym(l, m, j, el.nocc+c)
	if fv25 != 0 {
		if a == b {
			if i == o {
				if k == n {
					acc += fv25
				}
			}
		}
	}
	return acc
}

// b12o1t7: \delta_{a c} \delta_{i o} \delta_{j n} {V^{lm}_{kb}}
func (el *Elem) b12o1t7(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv26 := el.asym(l, m, k, el.nocc+b)
	if fv26 != 0 {
		if a == c {
			if i == o {
				if j == n {
					acc += fv26
				}
			}
		}
	}
	return acc
}

// b12o1t8: \delta_{a b} \delta_{i n} \delta_{j o} {V^{lm}_{kc}}
func (el *Elem) b12o1t8(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv27 := el.asym(l, m, k, el.nocc+c)
	if fv27 != 0 {
		if a == b {
			if i == n {
				if j == o {
					acc += fv27
				}
			}
		}
	}
	return acc
}

// b12o1t9: \delta_{a c} \delta_{j m} \delta_{k o} {V^{ln}_{ib}}
func (el *Elem) b12o1t9(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv28 := el.asym(l, n, i, el.nocc+b)
	if fv28 != 0 {
		if a == c {
			if j == m {
				if k == o {
					acc += fv28
				}
			}
		}
	}
	return acc
}

// b12o1t10: \delta_{a b} \delta_{j o} \delta_{k m} {V^{ln}_{ic}}
func (el *Elem) b12o1t10(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv29 := el.asym(l, n, i, el.nocc+c)
	if fv29 != 0 {
		if a == b {
			if j == o {
				if k == m {
					acc += fv29
				}
			}
		}
	}
	return acc
}

// b12o1t11: \delta_{a c} \delta_{i o} \delta_{k m} {V^{ln}_{jb}}
func (el *Elem) b12o1t11(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv30 := el.asym(l, n, j, el.nocc+b)
	if fv30 != 0 {
		if a == c {
			if i == o {
				if k == m {
					acc += fv30
				}
			}
		}
	}
	return acc
}

// b12o1t12: \delta_{a b} \delta_{i m} \delta_{k o} {V^{ln}_{jc}}
func (el *Elem) b12o1t12(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv31 := el.asym(l, n, j, el.nocc+c)
	if fv31 != 0 {
		if a == b {
			if i == m {
				if k == o {
					acc += fv31
				}
			}
		}
	}
	return acc
}

// b12o1t13: \delta_{a c} \delta_{i m} \delta_{j o} {V^{ln}_{kb}}
func (el *Elem) b12o1t13(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv32 := el.asym(l, n, k, el.nocc+b)
	if fv32 != 0 {
		if a == c {
			if i == m {
				if j == o {
					acc += fv32
				}
			}
		}
	}
	return acc
}

// b12o1t14: \delta_{a b} \delta_{i o} \delta_{j m} {V^{ln}_{kc}}
func (el *Elem) b12o1t14(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv33 := el.asym(l, n, k, el.nocc+c)
	if fv33 != 0 {
		if a == b {
			if i == o {
				if j == m {
					acc += fv33
				}
			}
		}
	}
	return acc
}

// b12o1t15: \delta_{a c} \delta_{j n} \delta_{k m} {V^{lo}_{ib}}
func (el *Elem) b12o1t15(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv34 := el.asym(l, o, i, el.nocc+b)
	if fv34 != 0 {
		if a == c {
			if j == n {
				if k == m {
					acc += fv34
				}
			}
		}
	}
	return acc
}

// b12o1t16: \delta_{a b} \delta_{j m} \delta_{k n} {V^{lo}_{ic}}
func (el *Elem) b12o1t16(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv35 := el.asym(l, o, i, el.nocc+c)
	if fv35 != 0 {
		if a == b {
			if j == m {
				if k == n {
					acc += fv35
				}
			}
		}
	}
	return acc
}

// b12o1t17: \delta_{a c} \delta_{i m} \delta_{k n} {V^{lo}_{jb}}
func (el *Elem) b12o1t17(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv36 := el.asym(l, o, j, el.nocc+b)
	if fv36 != 0 {
		if a == c {
			if i == m {
				if k == n {
					acc += fv36
				}
			}
		}
	}
	return acc
}

// b12o1t18: \delta_{a b} \delta_{i n} \delta_{k m} {V^{lo}_{jc}}
func (el *Elem) b12o1t18(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv37 := el.asym(l, o, j, el.nocc+c)
	if fv37 != 0 {
		if a == b {
			if i == n {
				if k == m {
					acc += fv37
				}
			}
		}
	}
	return acc
}

// b12o1t19: \delta_{a c} \delta_{i n} \delta_{j m} {V^{lo}_{kb}}
func (el *Elem) b12o1t19(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv38 := el.asym(l, o, k, el.nocc+b)
	if fv38 != 0 {
		if a == c {
			if i == n {
				if j == m {
					acc += fv38
				}
			}
		}
	}
	return acc
}

// b12o1t20: \delta_{a b} \delta_{i m} \delta_{j n} {V^{lo}_{kc}}
func (el *Elem) b12o1t20(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv39 := el.asym(l, o, k, el.nocc+c)
	if fv39 != 0 {
		if a == b {
			if i == m {
				if j == n {
					acc += fv39
				}
			}
		}
	}
	return acc
}

// b12o1t21: \delta_{i l} \delta_{j n} \delta_{k o} {V^{ma}_{bc}}
func (el *Elem) b12o1t21(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv40 := el.asym(m, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv40 != 0 {
		if i == l {
			if j == n {
				if k == o {
					acc += fv40
				}
			}
		}
	}
	return acc
}

// b12o1t22: \delta_{i n} \delta_{j o} \delta_{k l} {V^{ma}_{bc}}
func (el *Elem) b12o1t22(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv41 := el.asym(m, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv41 != 0 {
		if i == n {
			if j == o {
				if k == l {
					acc += fv41
				}
			}
		}
	}
	return acc
}

// b12o1t23: \delta_{i o} \delta_{j l} \delta_{k n} {V^{ma}_{bc}}
func (el *Elem) b12o1t23(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv42 := el.asym(m, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv42 != 0 {
		if i == o {
			if j == l {
				if k == n {
					acc += fv42
				}
			}
		}
	}
	return acc
}

// b12o1t24: \delta_{a c} \delta_{j o} \delta_{k l} {V^{mn}_{ib}}
func (el *Elem) b12o1t24(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv43 := el.asym(m, n, i, el.nocc+b)
	if fv43 != 0 {
		if a == c {
			if j == o {
				if k == l {
					acc += fv43
				}
			}
		}
	}
	return acc
}

// b12o1t25: \delta_{a b} \delta_{j l} \delta_{k o} {V^{mn}_{ic}}
func (el *Elem) b12o1t25(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv44 := el.asym(m, n, i, el.nocc+c)
	if fv44 != 0 {
		if a == b {
			if j == l {
				if k == o {
					acc += fv44
				}
			}
		}
	}
	return acc
}

// b12o1t26: \delta_{a c} \delta_{i l} \delta_{k o} {V^{mn}_{jb}}
func (el *Elem) b12o1t26(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv45 := el.asym(m, n, j, el.nocc+b)
	if fv45 != 0 {
		if a == c {
			if i == l {
				if k == o {
					acc += fv45
				}
			}
		}
	}
	return acc
}

// b12o1t27: \delta_{a b} \delta_{i o} \delta_{k l} {V^{mn}_{jc}}
func (el *Elem) b12o1t27(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv46 := el.asym(m, n, j, el.nocc+c)
	if fv46 != 0 {
		if a == b {
			if i == o {
				if k == l {
					acc += fv46
				}
			}
		}
	}
	return acc
}

// b12o1t28: \delta_{a c} \delta_{i o} \delta_{j l} {V^{mn}_{kb}}
func (el *Elem) b12o1t28(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv47 := el.asym(m, n, k, el.nocc+b)
	if fv47 != 0 {
		if a == c {
			if i == o {
				if j == l {
					acc += fv47
				}
			}
		}
	}
	return acc
}

// b12o1t29: \delta_{a b} \delta_{i l} \delta_{j o} {V^{mn}_{kc}}
func (el *Elem) b12o1t29(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv48 := el.asym(m, n, k, el.nocc+c)
	if fv48 != 0 {
		if a == b {
			if i == l {
				if j == o {
					acc += fv48
				}
			}
		}
	}
	return acc
}

// b12o1t30: \delta_{a c} \delta_{j l} \delta_{k n} {V^{mo}_{ib}}
func (el *Elem) b12o1t30(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv49 := el.asym(m, o, i, el.nocc+b)
	if fv49 != 0 {
		if a == c {
			if j == l {
				if k == n {
					acc += fv49
				}
			}
		}
	}
	return acc
}

// b12o1t31: \delta_{a b} \delta_{j n} \delta_{k l} {V^{mo}_{ic}}
func (el *Elem) b12o1t31(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv50 := el.asym(m, o, i, el.nocc+c)
	if fv50 != 0 {
		if a == b {
			if j == n {
				if k == l {
					acc += fv50
				}
			}
		}
	}
	return acc
}

// b12o1t32: \delta_{a c} \delta_{i n} \delta_{k l} {V^{mo}_{jb}}
func (el *Elem) b12o1t32(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv51 := el.asym(m, o, j, el.nocc+b)
	if fv51 != 0 {
		if a == c {
			if i == n {
				if k == l {
					acc += fv51
				}
			}
		}
	}
	return acc
}

// b12o1t33: \delta_{a b} \delta_{i l} \delta_{k n} {V^{mo}_{jc}}
func (el *Elem) b12o1t33(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv52 := el.asym(m, o, j, el.nocc+c)
	if fv52 != 0 {
		if a == b {
			if i == l {
				if k == n {
					acc += fv52
				}
			}
		}
	}
	return acc
}

// b12o1t34: \delta_{a c} \delta_{i l} \delta_{j n} {V^{mo}_{kb}}
func (el *Elem) b12o1t34(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv53 := el.asym(m, o, k, el.nocc+b)
	if fv53 != 0 {
		if a == c {
			if i == l {
				if j == n {
					acc += fv53
				}
			}
		}
	}
	return acc
}

// b12o1t35: \delta_{a b} \delta_{i n} \delta_{j l} {V^{mo}_{kc}}
func (el *Elem) b12o1t35(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv54 := el.asym(m, o, k, el.nocc+c)
	if fv54 != 0 {
		if a == b {
			if i == n {
				if j == l {
					acc += fv54
				}
			}
		}
	}
	return acc
}

// b12o1t36: \delta_{i l} \delta_{j o} \delta_{k m} {V^{na}_{bc}}
func (el *Elem) b12o1t36(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv55 := el.asym(n, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv55 != 0 {
		if i == l {
			if j == o {
				if k == m {
					acc += fv55
				}
			}
		}
	}
	return acc
}

// b12o1t37: \delta_{i m} \delta_{j l} \delta_{k o} {V^{na}_{bc}}
func (el *Elem) b12o1t37(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv56 := el.asym(n, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv56 != 0 {
		if i == m {
			if j == l {
				if k == o {
					acc += fv56
				}
			}
		}
	}
	return acc
}

// b12o1t38: \delta_{i o} \delta_{j m} \delta_{k l} {V^{na}_{bc}}
func (el *Elem) b12o1t38(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv57 := el.asym(n, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv57 != 0 {
		if i == o {
			if j == m {
				if k == l {
					acc += fv57
				}
			}
		}
	}
	return acc
}

// b12o1t39: \delta_{a c} \delta_{j m} \delta_{k l} {V^{no}_{ib}}
func (el *Elem) b12o1t39(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv58 := el.asym(n, o, i, el.nocc+b)
	if fv58 != 0 {
		if a == c {
			if j == m {
				if k == l {
					acc += fv58
				}
			}
		}
	}
	return acc
}

// b12o1t40: \delta_{a b} \delta_{j l} \delta_{k m} {V^{no}_{ic}}
func (el *Elem) b12o1t40(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv59 := el.asym(n, o, i, el.nocc+c)
	if fv59 != 0 {
		if a == b {
			if j == l {
				if k == m {
					acc += fv59
				}
			}
		}
	}
	return acc
}

// b12o1t41: \delta_{a c} \delta_{i l} \delta_{k m} {V^{no}_{jb}}
func (el *Elem) b12o1t41(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv60 := el.asym(n, o, j, el.nocc+b)
	if fv60 != 0 {
		if a == c {
			if i == l {
				if k == m {
					acc += fv60
				}
			}
		}
	}
	return acc
}

// b12o1t42: \delta_{a b} \delta_{i m} \delta_{k l} {V^{no}_{jc}}
func (el *Elem) b12o1t42(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv61 := el.asym(n, o, j, el.nocc+c)
	if fv61 != 0 {
		if a == b {
			if i == m {
				if k == l {
					acc += fv61
				}
			}
		}
	}
	return acc
}

// b12o1t43: \delta_{a c} \delta_{i m} \delta_{j l} {V^{no}_{kb}}
func (el *Elem) b12o1t43(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv62 := el.asym(n, o, k, el.nocc+b)
	if fv62 != 0 {
		if a == c {
			if i == m {
				if j == l {
					acc += fv62
				}
			}
		}
	}
	return acc
}

// b12o1t44: \delta_{a b} \delta_{i l} \delta_{j m} {V^{no}_{kc}}
func (el *Elem) b12o1t44(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv63 := el.asym(n, o, k, el.nocc+c)
	if fv63 != 0 {
		if a == b {
			if i == l {
				if j == m {
					acc += fv63
				}
			}
		}
	}
	return acc
}

// b12o1t45: \delta_{i l} \delta_{j m} \delta_{k n} {V^{oa}_{bc}}
func (el *Elem) b12o1t45(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv64 := el.asym(o, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv64 != 0 {
		if i == l {
			if j == m {
				if k == n {
					acc += fv64
				}
			}
		}
	}
	return acc
}

// b12o1t46: \delta_{i m} \delta_{j n} \delta_{k l} {V^{oa}_{bc}}
func (el *Elem) b12o1t46(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv65 := el.asym(o, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv65 != 0 {
		if i == m {
			if j == n {
				if k == l {
					acc += fv65
				}
			}
		}
	}
	return acc
}

// b12o1t47: \delta_{i n} \delta_{j l} \delta_{k m} {V^{oa}_{bc}}
func (el *Elem) b12o1t47(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv66 := el.asym(o, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv66 != 0 {
		if i == n {
			if j == l {
				if k == m {
					acc += fv66
				}
			}
		}
	}
	return acc
}

// b12o1t48: - \delta_{i m} \delta_{j n} \delta_{k o} {V^{la}_{bc}}
func (el *Elem) b12o1t48(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv67 := el.asym(l, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv67 != 0 {
		if i == m {
			if j == n {
				if k == o {
					acc += fv67
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t49: - \delta_{i n} \delta_{j o} \delta_{k m} {V^{la}_{bc}}
func (el *Elem) b12o1t49(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv68 := el.asym(l, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv68 != 0 {
		if i == n {
			if j == o {
				if k == m {
					acc += fv68
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t50: - \delta_{i o} \delta_{j m} \delta_{k n} {V^{la}_{bc}}
func (el *Elem) b12o1t50(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv69 := el.asym(l, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv69 != 0 {
		if i == o {
			if j == m {
				if k == n {
					acc += fv69
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t51: - \delta_{a c} \delta_{j n} \delta_{k o} {V^{lm}_{ib}}
func (el *Elem) b12o1t51(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv70 := el.asym(l, m, i, el.nocc+b)
	if fv70 != 0 {
		if a == c {
			if j == n {
				if k == o {
					acc += fv70
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t52: - \delta_{a b} \delta_{j o} \delta_{k n} {V^{lm}_{ic}}
func (el *Elem) b12o1t52(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv71 := el.asym(l, m, i, el.nocc+c)
	if fv71 != 0 {
		if a == b {
			if j == o {
				if k == n {
					acc += fv71
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t53: - \delta_{a c} \delta_{i o} \delta_{k n} {V^{lm}_{jb}}
func (el *Elem) b12o1t53(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv72 := el.asym(l, m, j, el.nocc+b)
	if fv72 != 0 {
		if a == c {
			if i == o {
				if k == n {
					acc += fv72
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t54: - \delta_{a b} \delta_{i n} \delta_{k o} {V^{lm}_{jc}}
func (el *Elem) b12o1t54(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv73 := el.asym(l, m, j, el.nocc+c)
	if fv73 != 0 {
		if a == b {
			if i == n {
				if k == o {
					acc += fv73
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t55: - \delta_{a c} \delta_{i n} \delta_{j o} {V^{lm}_{kb}}
func (el *Elem) b12o1t55(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv74 := el.asym(l, m, k, el.nocc+b)
	if fv74 != 0 {
		if a == c {
			if i == n {
				if j == o {
					acc += fv74
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t56: - \delta_{a b} \delta_{i o} \delta_{j n} {V^{lm}_{kc}}
func (el *Elem) b12o1t56(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv75 := el.asym(l, m, k, el.nocc+c)
	if fv75 != 0 {
		if a == b {
			if i == o {
				if j == n {
					acc += fv75
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t57: - \delta_{a c} \delta_{j o} \delta_{k m} {V^{ln}_{ib}}
func (el *Elem) b12o1t57(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv76 := el.asym(l, n, i, el.nocc+b)
	if fv76 != 0 {
		if a == c {
			if j == o {
				if k == m {
					acc += fv76
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t58: - \delta_{a b} \delta_{j m} \delta_{k o} {V^{ln}_{ic}}
func (el *Elem) b12o1t58(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv77 := el.asym(l, n, i, el.nocc+c)
	if fv77 != 0 {
		if a == b {
			if j == m {
				if k == o {
					acc += fv77
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t59: - \delta_{a c} \delta_{i m} \delta_{k o} {V^{ln}_{jb}}
func (el *Elem) b12o1t59(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv78 := el.asym(l, n, j, el.nocc+b)
	if fv78 != 0 {
		if a == c {
			if i == m {
				if k == o {
					acc += fv78
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t60: - \delta_{a b} \delta_{i o} \delta_{k m} {V^{ln}_{jc}}
func (el *Elem) b12o1t60(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv79 := el.asym(l, n, j, el.nocc+c)
	if fv79 != 0 {
		if a == b {
			if i == o {
				if k == m {
					acc += fv79
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t61: - \delta_{a c} \delta_{i o} \delta_{j m} {V^{ln}_{kb}}
func (el *Elem) b12o1t61(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv80 := el.asym(l, n, k, el.nocc+b)
	if fv80 != 0 {
		if a == c {
			if i == o {
				if j == m {
					acc += fv80
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t62: - \delta_{a b} \delta_{i m} \delta_{j o} {V^{ln}_{kc}}
func (el *Elem) b12o1t62(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv81 := el.asym(l, n, k, el.nocc+c)
	if fv81 != 0 {
		if a == b {
			if i == m {
				if j == o {
					acc += fv81
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t63: - \delta_{a c} \delta_{j m} \delta_{k n} {V^{lo}_{ib}}
func (el *Elem) b12o1t63(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv82 := el.asym(l, o, i, el.nocc+b)
	if fv82 != 0 {
		if a == c {
			if j == m {
				if k == n {
					acc += fv82
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t64: - \delta_{a b} \delta_{j n} \delta_{k m} {V^{lo}_{ic}}
func (el *Elem) b12o1t64(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv83 := el.asym(l, o, i, el.nocc+c)
	if fv83 != 0 {
		if a == b {
			if j == n {
				if k == m {
					acc += fv83
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t65: - \delta_{a c} \delta_{i n} \delta_{k m} {V^{lo}_{jb}}
func (el *Elem) b12o1t65(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv84 := el.asym(l, o, j, el.nocc+b)
	if fv84 != 0 {
		if a == c {
			if i == n {
				if k == m {
					acc += fv84
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t66: - \delta_{a b} \delta_{i m} \delta_{k n} {V^{lo}_{jc}}
func (el *Elem) b12o1t66(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv85 := el.asym(l, o, j, el.nocc+c)
	if fv85 != 0 {
		if a == b {
			if i == m {
				if k == n {
					acc += fv85
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t67: - \delta_{a c} \delta_{i m} \delta_{j n} {V^{lo}_{kb}}
func (el *Elem) b12o1t67(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv86 := el.asym(l, o, k, el.nocc+b)
	if fv86 != 0 {
		if a == c {
			if i == m {
				if j == n {
					acc += fv86
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t68: - \delta_{a b} \delta_{i n} \delta_{j m} {V^{lo}_{kc}}
func (el *Elem) b12o1t68(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv87 := el.asym(l, o, k, el.nocc+c)
	if fv87 != 0 {
		if a == b {
			if i == n {
				if j == m {
					acc += fv87
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t69: - \delta_{i l} \delta_{j o} \delta_{k n} {V^{ma}_{bc}}
func (el *Elem) b12o1t69(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv88 := el.asym(m, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv88 != 0 {
		if i == l {
			if j == o {
				if k == n {
					acc += fv88
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t70: - \delta_{i n} \delta_{j l} \delta_{k o} {V^{ma}_{bc}}
func (el *Elem) b12o1t70(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv89 := el.asym(m, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv89 != 0 {
		if i == n {
			if j == l {
				if k == o {
					acc += fv89
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t71: - \delta_{i o} \delta_{j n} \delta_{k l} {V^{ma}_{bc}}
func (el *Elem) b12o1t71(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv90 := el.asym(m, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv90 != 0 {
		if i == o {
			if j == n {
				if k == l {
					acc += fv90
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t72: - \delta_{a c} \delta_{j l} \delta_{k o} {V^{mn}_{ib}}
func (el *Elem) b12o1t72(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv91 := el.asym(m, n, i, el.nocc+b)
	if fv91 != 0 {
		if a == c {
			if j == l {
				if k == o {
					acc += fv91
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t73: - \delta_{a b} \delta_{j o} \delta_{k l} {V^{mn}_{ic}}
func (el *Elem) b12o1t73(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv92 := el.asym(m, n, i, el.nocc+c)
	if fv92 != 0 {
		if a == b {
			if j == o {
				if k == l {
					acc += fv92
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t74: - \delta_{a c} \delta_{i o} \delta_{k l} {V^{mn}_{jb}}
func (el *Elem) b12o1t74(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv93 := el.asym(m, n, j, el.nocc+b)
	if fv93 != 0 {
		if a == c {
			if i == o {
				if k == l {
					acc += fv93
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t75: - \delta_{a b} \delta_{i l} \delta_{k o} {V^{mn}_{jc}}
func (el *Elem) b12o1t75(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv94 := el.asym(m, n, j, el.nocc+c)
	if fv94 != 0 {
		if a == b {
			if i == l {
				if k == o {
					acc += fv94
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t76: - \delta_{a c} \delta_{i l} \delta_{j o} {V^{mn}_{kb}}
func (el *Elem) b12o1t76(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv95 := el.asym(m, n, k, el.nocc+b)
	if fv95 != 0 {
		if a == c {
			if i == l {
				if j == o {
					acc += fv95
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t77: - \delta_{a b} \delta_{i o} \delta_{j l} {V^{mn}_{kc}}
func (el *Elem) b12o1t77(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv96 := el.asym(m, n, k, el.nocc+c)
	if fv96 != 0 {
		if a == b {
			if i == o {
				if j == l {
					acc += fv96
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t78: - \delta_{a c} \delta_{j n} \delta_{k l} {V^{mo}_{ib}}
func (el *Elem) b12o1t78(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv97 := el.asym(m, o, i, el.nocc+b)
	if fv97 != 0 {
		if a == c {
			if j == n {
				if k == l {
					acc += fv97
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t79: - \delta_{a b} \delta_{j l} \delta_{k n} {V^{mo}_{ic}}
func (el *Elem) b12o1t79(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv98 := el.asym(m, o, i, el.nocc+c)
	if fv98 != 0 {
		if a == b {
			if j == l {
				if k == n {
					acc += fv98
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t80: - \delta_{a c} \delta_{i l} \delta_{k n} {V^{mo}_{jb}}
func (el *Elem) b12o1t80(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv99 := el.asym(m, o, j, el.nocc+b)
	if fv99 != 0 {
		if a == c {
			if i == l {
				if k == n {
					acc += fv99
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t81: - \delta_{a b} \delta_{i n} \delta_{k l} {V^{mo}_{jc}}
func (el *Elem) b12o1t81(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv100 := el.asym(m, o, j, el.nocc+c)
	if fv100 != 0 {
		if a == b {
			if i == n {
				if k == l {
					acc += fv100
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t82: - \delta_{a c} \delta_{i n} \delta_{j l} {V^{mo}_{kb}}
func (el *Elem) b12o1t82(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv101 := el.asym(m, o, k, el.nocc+b)
	if fv101 != 0 {
		if a == c {
			if i == n {
				if j == l {
					acc += fv101
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t83: - \delta_{a b} \delta_{i l} \delta_{j n} {V^{mo}_{kc}}
func (el *Elem) b12o1t83(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv102 := el.asym(m, o, k, el.nocc+c)
	if fv102 != 0 {
		if a == b {
			if i == l {
				if j == n {
					acc += fv102
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t84: - \delta_{i l} \delta_{j m} \delta_{k o} {V^{na}_{bc}}
func (el *Elem) b12o1t84(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv103 := el.asym(n, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv103 != 0 {
		if i == l {
			if j == m {
				if k == o {
					acc += fv103
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t85: - \delta_{i m} \delta_{j o} \delta_{k l} {V^{na}_{bc}}
func (el *Elem) b12o1t85(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv104 := el.asym(n, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv104 != 0 {
		if i == m {
			if j == o {
				if k == l {
					acc += fv104
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t86: - \delta_{i o} \delta_{j l} \delta_{k m} {V^{na}_{bc}}
func (el *Elem) b12o1t86(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv105 := el.asym(n, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv105 != 0 {
		if i == o {
			if j == l {
				if k == m {
					acc += fv105
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t87: - \delta_{a c} \delta_{j l} \delta_{k m} {V^{no}_{ib}}
func (el *Elem) b12o1t87(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv106 := el.asym(n, o, i, el.nocc+b)
	if fv106 != 0 {
		if a == c {
			if j == l {
				if k == m {
					acc += fv106
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t88: - \delta_{a b} \delta_{j m} \delta_{k l} {V^{no}_{ic}}
func (el *Elem) b12o1t88(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv107 := el.asym(n, o, i, el.nocc+c)
	if fv107 != 0 {
		if a == b {
			if j == m {
				if k == l {
					acc += fv107
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t89: - \delta_{a c} \delta_{i m} \delta_{k l} {V^{no}_{jb}}
func (el *Elem) b12o1t89(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv108 := el.asym(n, o, j, el.nocc+b)
	if fv108 != 0 {
		if a == c {
			if i == m {
				if k == l {
					acc += fv108
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t90: - \delta_{a b} \delta_{i l} \delta_{k m} {V^{no}_{jc}}
func (el *Elem) b12o1t90(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv109 := el.asym(n, o, j, el.nocc+c)
	if fv109 != 0 {
		if a == b {
			if i == l {
				if k == m {
					acc += fv109
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t91: - \delta_{a c} \delta_{i l} \delta_{j m} {V^{no}_{kb}}
func (el *Elem) b12o1t91(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv110 := el.asym(n, o, k, el.nocc+b)
	if fv110 != 0 {
		if a == c {
			if i == l {
				if j == m {
					acc += fv110
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t92: - \delta_{a b} \delta_{i m} \delta_{j l} {V^{no}_{kc}}
func (el *Elem) b12o1t92(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv111 := el.asym(n, o, k, el.nocc+c)
	if fv111 != 0 {
		if a == b {
			if i == m {
				if j == l {
					acc += fv111
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t93: - \delta_{i l} \delta_{j n} \delta_{k m} {V^{oa}_{bc}}
func (el *Elem) b12o1t93(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv112 := el.asym(o, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv112 != 0 {
		if i == l {
			if j == n {
				if k == m {
					acc += fv112
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t94: - \delta_{i m} \delta_{j l} \delta_{k n} {V^{oa}_{bc}}
func (el *Elem) b12o1t94(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv113 := el.asym(o, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv113 != 0 {
		if i == m {
			if j == l {
				if k == n {
					acc += fv113
				}
			}
		}
	}
	return -1.0 * acc
}

// b12o1t95: - \delta_{i n} \delta_{j m} \delta_{k l} {V^{oa}_{bc}}
func (el *Elem) b12o1t95(a, i, j, k, b, c, l, m, n, o int) float64 {
	var acc float64
	fv114 := el.asym(o, el.nocc+a, el.nocc+b, el.nocc+c)
	if fv114 != 0 {
		if i == n {
			if j == m {
				if k == l {
					acc += fv114
				}
			}
		}
	}
	return -1.0 * acc
}

func (el *Elem) b12o1g0(a, i, j, k, b, c, l, m, n, o int) float64 {
	return el.b12o1t0(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t1(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t2(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t3(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t4(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t5(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t6(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t7(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t8(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t9(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t10(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t11(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t12(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t13(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t14(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t15(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t16(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t17(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t18(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t19(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t20(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t21(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t22(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t23(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t24(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t25(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t26(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t27(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t28(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t29(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t30(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t31(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t32(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t33(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t34(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t35(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t36(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t37(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t38(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t39(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t40(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t41(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t42(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t43(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t44(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t45(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t46(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t47(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t48(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t49(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t50(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t51(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t52(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t53(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t54(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t55(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t56(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t57(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t58(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t59(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t60(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t61(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t62(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t63(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t64(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t65(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t66(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t67(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t68(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t69(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t70(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t71(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t72(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t73(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t74(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t75(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t76(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t77(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t78(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t79(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t80(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t81(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t82(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t83(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t84(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t85(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t86(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t87(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t88(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t89(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t90(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t91(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t92(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t93(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t94(a, i, j, k, b, c, l, m, n, o) +
		el.b12o1t95(a, i, j, k, b, c, l, m, n, o)
}

// b12o1 is the order-1 part of block phhh,pphhhh, <a,i,j,k|M|b,c,l,m,n,o>.
func (el *Elem) b12o1(a, i, j, k, b, c, l, m, n, o int) float64 {
	var v float64
	// (1)
	v += el.b12o1g0(a, i, j, k, b, c, l, m, n, o)
	return v
}

// B12 is block phhh,pphhhh of the secular matrix,
// <a,i,j,k|M|b,c,l,m,n,o>, summed over the orders the scheme keeps.
func (el *Elem) B12(a, i, j, k, b, c, l, m, n, o int) float64 {
	var v float64
	if el.maxOrder[4] >= 1 {
		v += el.b12o1(a, i, j, k, b, c, l, m, n, o)
	}
	return v
}
