// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package dip

// b00o0t0: \delta_{j k} {f^{i}_{l}}
func (el *Elem) b00o0t0(i, j, k, l int) float64 {
	var acc float64
	fv1 := el.fock(i, l)
	if fv1 != 0 {
		if j == k {
			acc += fv1
		}
	}
	return acc
}

func (el *Elem) b00o0g0(i, j, k, l int) float64 {
	return el.b00o0t0(i, j, k, l)
}

// b00o0 is the order-0 part of block hh,hh, <i,j|M|k,l>.
func (el *Elem) b00o0(i, j, k, l int) float64 {
	var v float64
	// (1 - P_ij - P_kl + P_ijP_kl)
	v += el.b00o0g0(i, j, k, l)
	v -= el.b00o0g0(j, i, k, l)
	v -= el.b00o0g0(i, j, l, k)
	v += el.b00o0g0(j, i, l, k)
	return v
}

// b00o1t0: {V^{ij}_{kl}}
func (el *Elem) b00o1t0(i, j, k, l int) float64 {
	var acc float64
	fv2 := el.asym(i, j, k, l)
	if fv2 != 0 {
		acc += fv2
	}
	return acc
}

func (el *Elem) b00o1g0(i, j, k, l int) float64 {
	return el.b00o1t0(i, j, k, l)
}

// b00o1 is the order-1 part of block hh,hh, <i,j|M|k,l>.
func (el *Elem) b00o1(i, j, k, l int) float64 {
	var v float64
	// (1)
	v += el.b00o1g0(i, j, k, l)
	return v
}

// b00o2t0: - \frac{{t1^{ab}_{ij}} {V^{kl}_{ab}}}{4}
func (el *Elem) b00o2t0(i, j, k, l int) float64 {
	var acc float64
	for a := 0; a < el.nvir; a++ {
		for b := 0; b < el.nvir; b++ {
			fv3 := el.get_t2_1(i, j, a, b)
			if fv3 != 0 {
				fv4 := el.asym(k, l, el.nocc+a, el.nocc+b)
				if fv4 != 0 {
					acc += fv3 * fv4
				}
			}
		}
	}
	return -0.25 * acc
}

func (el *Elem) b00o2g0(i, j, k, l int) float64 {
	return el.b00o2t0(i, j, k, l)
}

// b00o2t1: - \frac{\delta_{j k} {t1^{ab}_{im}} {V^{lm}_{ab}}}{4}
func (el *Elem) b00o2t1(i, j, k, l int) float64 {
	var acc float64
	var sv5 float64
	for m := 0; m < el.nocc; m++ {
		for a := 0; a < el.nvir; a++ {
			for b := 0; b < el.nvir; b++ {
				fv6 := el.get_t2_1(i, m, a, b)
				if fv6 != 0 {
					fv7 := el.asym(l, m, el.nocc+a, el.nocc+b)
					if fv7 != 0 {
						sv5 += fv6 * fv7
					}
				}
			}
		}
	}
	if sv5 != 0 {
		if j == k {
			acc += sv5
		}
	}
	return -0.25 * acc
}

func (el *Elem) b00o2g1(i, j, k, l int) float64 {
	return el.b00o2t1(i, j, k, l)
}

// b00o2 is the order-2 part of block hh,hh, <i,j|M|k,l>.
func (el *Elem) b00o2(i, j, k, l int) float64 {
	var v float64
	// (1 + P_ikP_jl)
	v += el.b00o2g0(i, j, k, l)
	v += el.b00o2g0(k, l, i, j)
	// (1 - P_ij - P_kl + P_ijP_kl + P_ikP_jl + P_ilP_jk - P_ijP_ikP_jl - P_ijP_ilP_jk)
	v += el.b00o2g1(i, j, k, l)
	v -= el.b00o2g1(j, i, k, l)
	v -= el.b00o2g1(i, j, l, k)
	v += el.b00o2g1(j, i, l, k)
	v += el.b00o2g1(k, l, i, j)
	v += el.b00o2g1(l, k, j, i)
	v -= el.b00o2g1(l, k, i, j)
	v -= el.b00o2g1(k, l, j, i)
	return v
}

// B00 is block hh,hh of the secular matrix,
// <i,j|M|k,l>, summed over the orders the scheme keeps.
func (el *Elem) B00(i, j, k, l int) float64 {
	var v float64
	if el.maxOrder[0] >= 0 {
		v += el.b00o0(i, j, k, l)
	}
	if el.maxOrder[0] >= 1 {
		v += el.b00o1(i, j, k, l)
	}
	if el.maxOrder[0] >= 2 {
		v += el.b00o2(i, j, k, l)
	}
	return v
}
