// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package dip

// hh,phhh vanishes at order 0.

// b01o1t0: \delta_{j m} {V^{kl}_{ia}}
func (el *Elem) b01o1t0(i, j, a, k, l, m int) float64 {
	var acc float64
	fv8 := el.asym(k, l, i, el.nocc+a)
	if fv8 != 0 {
		if j == m {
			acc += fv8
		}
	}
	return acc
}

func (el *Elem) b01o1g0(i, j, a, k, l, m int) float64 {
	return el.b01o1t0(i, j, a, k, l, m)
}

// b01o1 is the order-1 part of block hh,phhh, <i,j|M|a,k,l,m>.
func (el *Elem) b01o1(i, j, a, k, l, m int) float64 {
	var v float64
	// (1 - P_ij - P_km - P_lm + P_ijP_km + P_ijP_lm)
	v += el.b01o1g0(i, j, a, k, l, m)
	v -= el.b01o1g0(j, i, a, k, l, m)
	v -= el.b01o1g0(i, j, a, m, l, k)
	v -= el.b01o1g0(i, j, a, k, m, l)
	v += el.b01o1g0(j, i, a, m, l, k)
	v += el.b01o1g0(j, i, a, k, m, l)
	return v
}

// B01 is block hh,phhh of the secular matrix,
// <i,j|M|a,k,l,m>, summed over the orders the scheme keeps.
func (el *Elem) B01(i, j, a, k, l, m int) float64 {
	var v float64
	if el.maxOrder[1] >= 1 {
		v += el.b01o1(i, j, a, k, l, m)
	}
	return v
}
