// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package qip

// hhhh,phhhhh vanishes at order 0.

// b01o1t0: \delta_{j m} \delta_{k n} \delta_{l o} {V^{i1j1}_{ia}}
func (el *Elem) b01o1t0(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1969 := el.asym(i1, j1, i, el.nocc+a)
	if fv1969 != 0 {
		if j == m {
			if k == n {
				if l == o {
					acc += fv1969
				}
			}
		}
	}
	return acc
}

// b01o1t1: \delta_{j n} \delta_{k o} \delta_{l m} {V^{i1j1}_{ia}}
func (el *Elem) b01o1t1(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1970 := el.asym(i1, j1, i, el.nocc+a)
	if fv1970 != 0 {
		if j == n {
			if k == o {
				if l == m {
					acc += fv1970
				}
			}
		}
	}
	return acc
}

// b01o1t2: \delta_{j o} \delta_{k m} \delta_{l n} {V^{i1j1}_{ia}}
func (el *Elem) b01o1t2(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1971 := el.asym(i1, j1, i, el.nocc+a)
	if fv1971 != 0 {
		if j == o {
			if k == m {
				if l == n {
					acc += fv1971
				}
			}
		}
	}
	return acc
}

// b01o1t3: \delta_{i m} \delta_{k o} \delta_{l n} {V^{i1j1}_{ja}}
func (el *Elem) b01o1t3(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1972 := el.asym(i1, j1, j, el.nocc+a)
	if fv1972 != 0 {
		if i == m {
			if k == o {
				if l == n {
					acc += fv1972
				}
			}
		}
	}
	return acc
}

// b01o1t4: \delta_{i n} \delta_{k m} \delta_{l o} {V^{i1j1}_{ja}}
func (el *Elem) b01o1t4(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1973 := el.asym(i1, j1, j, el.nocc+a)
	if fv1973 != 0 {
		if i == n {
			if k == m {
				if l == o {
					acc += fv1973
				}
			}
		}
	}
	return acc
}

// b01o1t5: \delta_{i o} \delta_{k n} \delta_{l m} {V^{i1j1}_{ja}}
func (el *Elem) b01o1t5(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1974 := el.asym(i1, j1, j, el.nocc+a)
	if fv1974 != 0 {
		if i == o {
			if k == n {
				if l == m {
					acc += fv1974
				}
			}
		}
	}
	return acc
}

// b01o1t6: \delta_{i m} \delta_{j n} \delta_{l o} {V^{i1j1}_{ka}}
func (el *Elem) b01o1t6(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1975 := el.asym(i1, j1, k, el.nocc+a)
	if fv1975 != 0 {
		if i == m {
			if j == n {
				if l == o {
					acc += fv1975
				}
			}
		}
	}
	return acc
}

// b01o1t7: \delta_{i n} \delta_{j o} \delta_{l m} {V^{i1j1}_{ka}}
func (el *Elem) b01o1t7(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1976 := el.asym(i1, j1, k, el.nocc+a)
	if fv1976 != 0 {
		if i == n {
			if j == o {
				if l == m {
					acc += fv1976
				}
			}
		}
	}
	return acc
}

// b01o1t8: \delta_{i o} \delta_{j m} \delta_{l n} {V^{i1j1}_{ka}}
func (el *Elem) b01o1t8(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1977 := el.asym(i1, j1, k, el.nocc+a)
	if fv1977 != 0 {
		if i == o {
			if j == m {
				if l == n {
					acc += fv1977
				}
			}
		}
	}
	return acc
}

// b01o1t9: \delta_{i m} \delta_{j o} \delta_{k n} {V^{i1j1}_{la}}
func (el *Elem) b01o1t9(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1978 := el.asym(i1, j1, l, el.nocc+a)
	if fv1978 != 0 {
		if i == m {
			if j == o {
				if k == n {
					acc += fv1978
				}
			}
		}
	}
	return acc
}

// b01o1t10: \delta_{i n} \delta_{j m} \delta_{k o} {V^{i1j1}_{la}}
func (el *Elem) b01o1t10(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1979 := el.asym(i1, j1, l, el.nocc+a)
	if fv1979 != 0 {
		if i == n {
			if j == m {
				if k == o {
					acc += fv1979
				}
			}
		}
	}
	return acc
}

// b01o1t11: \delta_{i o} \delta_{j n} \delta_{k m} {V^{i1j1}_{la}}
func (el *Elem) b01o1t11(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1980 := el.asym(i1, j1, l, el.nocc+a)
	if fv1980 != 0 {
		if i == o {
			if j == n {
				if k == m {
					acc += fv1980
				}
			}
		}
	}
	return acc
}

// b01o1t12: \delta_{j j1} \delta_{k n} \delta_{l o} {V^{mi1}_{ia}}
func (el *Elem) b01o1t12(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1981 := el.asym(m, i1, i, el.nocc+a)
	if fv1981 != 0 {
		if j == j1 {
			if k == n {
				if l == o {
					acc += fv1981
				}
			}
		}
	}
	return acc
}

// b01o1t13: \delta_{j n} \delta_{k o} \delta_{l j1} {V^{mi1}_{ia}}
func (el *Elem) b01o1t13(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1982 := el.asym(m, i1, i, el.nocc+a)
	if fv1982 != 0 {
		if j == n {
			if k == o {
				if l == j1 {
					acc += fv1982
				}
			}
		}
	}
	return acc
}

// b01o1t14: \delta_{j o} \delta_{k j1} \delta_{l n} {V^{mi1}_{ia}}
func (el *Elem) b01o1t14(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1983 := el.asym(m, i1, i, el.nocc+a)
	if fv1983 != 0 {
		if j == o {
			if k == j1 {
				if l == n {
					acc += fv1983
				}
			}
		}
	}
	return acc
}

// b01o1t15: \delta_{i j1} \delta_{k o} \delta_{l n} {V^{mi1}_{ja}}
func (el *Elem) b01o1t15(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1984 := el.asym(m, i1, j, el.nocc+a)
	if fv1984 != 0 {
		if i == j1 {
			if k == o {
				if l == n {
					acc += fv1984
				}
			}
		}
	}
	return acc
}

// b01o1t16: \delta_{i n} \delta_{k j1} \delta_{l o} {V^{mi1}_{ja}}
func (el *Elem) b01o1t16(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1985 := el.asym(m, i1, j, el.nocc+a)
	if fv1985 != 0 {
		if i == n {
			if k == j1 {
				if l == o {
					acc += fv1985
				}
			}
		}
	}
	return acc
}

// b01o1t17: \delta_{i o} \delta_{k n} \delta_{l j1} {V^{mi1}_{ja}}
func (el *Elem) b01o1t17(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1986 := el.asym(m, i1, j, el.nocc+a)
	if fv1986 != 0 {
		if i == o {
			if k == n {
				if l == j1 {
					acc += fv1986
				}
			}
		}
	}
	return acc
}

// b01o1t18: \delta_{i j1} \delta_{j n} \delta_{l o} {V^{mi1}_{ka}}
func (el *Elem) b01o1t18(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1987 := el.asym(m, i1, k, el.nocc+a)
	if fv1987 != 0 {
		if i == j1 {
			if j == n {
				if l == o {
					acc += fv1987
				}
			}
		}
	}
	return acc
}

// b01o1t19: \delta_{i n} \delta_{j o} \delta_{l j1} {V^{mi1}_{ka}}
func (el *Elem) b01o1t19(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1988 := el.asym(m, i1, k, el.nocc+a)
	if fv1988 != 0 {
		if i == n {
			if j == o {
				if l == j1 {
					acc += fv1988
				}
			}
		}
	}
	return acc
}

// b01o1t20: \delta_{i o} \delta_{j j1} \delta_{l n} {V^{mi1}_{ka}}
func (el *Elem) b01o1t20(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1989 := el.asym(m, i1, k, el.nocc+a)
	if fv1989 != 0 {
		if i == o {
			if j == j1 {
				if l == n {
					acc += fv1989
				}
			}
		}
	}
	return acc
}

// b01o1t21: \delta_{i j1} \delta_{j o} \delta_{k n} {V^{mi1}_{la}}
func (el *Elem) b01o1t21(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1990 := el.asym(m, i1, l, el.nocc+a)
	if fv1990 != 0 {
		if i == j1 {
			if j == o {
				if k == n {
					acc += fv1990
				}
			}
		}
	}
	return acc
}

// b01o1t22: \delta_{i n} \delta_{j j1} \delta_{k o} {V^{mi1}_{la}}
func (el *Elem) b01o1t22(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1991 := el.asym(m, i1, l, el.nocc+a)
	if fv1991 != 0 {
		if i == n {
			if j == j1 {
				if k == o {
					acc += fv1991
				}
			}
		}
	}
	return acc
}

// b01o1t23: \delta_{i o} \delta_{j n} \delta_{k j1} {V^{mi1}_{la}}
func (el *Elem) b01o1t23(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1992 := el.asym(m, i1, l, el.nocc+a)
	if fv1992 != 0 {
		if i == o {
			if j == n {
				if k == j1 {
					acc += fv1992
				}
			}
		}
	}
	return acc
}

// b01o1t24: \delta_{j i1} \delta_{k o} \delta_{l n} {V^{mj1}_{ia}}
func (el *Elem) b01o1t24(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1993 := el.asym(m, j1, i, el.nocc+a)
	if fv1993 != 0 {
		if j == i1 {
			if k == o {
				if l == n {
					acc += fv1993
				}
			}
		}
	}
	return acc
}

// b01o1t25: \delta_{j n} \delta_{k i1} \delta_{l o} {V^{mj1}_{ia}}
func (el *Elem) b01o1t25(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1994 := el.asym(m, j1, i, el.nocc+a)
	if fv1994 != 0 {
		if j == n {
			if k == i1 {
				if l == o {
					acc += fv1994
				}
			}
		}
	}
	return acc
}

// b01o1t26: \delta_{j o} \delta_{k n} \delta_{l i1} {V^{mj1}_{ia}}
func (el *Elem) b01o1t26(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1995 := el.asym(m, j1, i, el.nocc+a)
	if fv1995 != 0 {
		if j == o {
			if k == n {
				if l == i1 {
					acc += fv1995
				}
			}
		}
	}
	return acc
}

// b01o1t27: \delta_{i i1} \delta_{k n} \delta_{l o} {V^{mj1}_{ja}}
func (el *Elem) b01o1t27(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1996 := el.asym(m, j1, j, el.nocc+a)
	if fv1996 != 0 {
		if i == i1 {
			if k == n {
				if l == o {
					acc += fv1996
				}
			}
		}
	}
	return acc
}

// b01o1t28: \delta_{i n} \delta_{k o} \delta_{l i1} {V^{mj1}_{ja}}
func (el *Elem) b01o1t28(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1997 := el.asym(m, j1, j, el.nocc+a)
	if fv1997 != 0 {
		if i == n {
			if k == o {
				if l == i1 {
					acc += fv1997
				}
			}
		}
	}
	return acc
}

// b01o1t29: \delta_{i o} \delta_{k i1} \delta_{l n} {V^{mj1}_{ja}}
func (el *Elem) b01o1t29(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1998 := el.asym(m, j1, j, el.nocc+a)
	if fv1998 != 0 {
		if i == o {
			if k == i1 {
				if l == n {
					acc += fv1998
				}
			}
		}
	}
	return acc
}

// b01o1t30: \delta_{i i1} \delta_{j o} \delta_{l n} {V^{mj1}_{ka}}
func (el *Elem) b01o1t30(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv1999 := el.asym(m, j1, k, el.nocc+a)
	if fv1999 != 0 {
		if i == i1 {
			if j == o {
				if l == n {
					acc += fv1999
				}
			}
		}
	}
	return acc
}

// b01o1t31: \delta_{i n} \delta_{j i1} \delta_{l o} {V^{mj1}_{ka}}
func (el *Elem) b01o1t31(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2000 := el.asym(m, j1, k, el.nocc+a)
	if fv2000 != 0 {
		if i == n {
			if j == i1 {
				if l == o {
					acc += fv2000
				}
			}
		}
	}
	return acc
}

// b01o1t32: \delta_{i o} \delta_{j n} \delta_{l i1} {V^{mj1}_{ka}}
func (el *Elem) b01o1t32(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2001 := el.asym(m, j1, k, el.nocc+a)
	if fv2001 != 0 {
		if i == o {
			if j == n {
				if l == i1 {
					acc += fv2001
				}
			}
		}
	}
	return acc
}

// b01o1t33: \delta_{i i1} \delta_{j n} \delta_{k o} {V^{mj1}_{la}}
func (el *Elem) b01o1t33(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2002 := el.asym(m, j1, l, el.nocc+a)
	if fv2002 != 0 {
		if i == i1 {
			if j == n {
				if k == o {
					acc += fv2002
				}
			}
		}
	}
	return acc
}

// b01o1t34: \delta_{i n} \delta_{j o} \delta_{k i1} {V^{mj1}_{la}}
func (el *Elem) b01o1t34(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2003 := el.asym(m, j1, l, el.nocc+a)
	if fv2003 != 0 {
		if i == n {
			if j == o {
				if k == i1 {
					acc += fv2003
				}
			}
		}
	}
	return acc
}

// b01o1t35: \delta_{i o} \delta_{j i1} \delta_{k n} {V^{mj1}_{la}}
func (el *Elem) b01o1t35(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2004 := el.asym(m, j1, l, el.nocc+a)
	if fv2004 != 0 {
		if i == o {
			if j == i1 {
				if k == n {
					acc += fv2004
				}
			}
		}
	}
	return acc
}

// b01o1t36: \delta_{j i1} \delta_{k j1} \delta_{l o} {V^{mn}_{ia}}
func (el *Elem) b01o1t36(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2005 := el.asym(m, n, i, el.nocc+a)
	if fv2005 != 0 {
		if j == i1 {
			if k == j1 {
				if l == o {
					acc += fv2005
				}
			}
		}
	}
	return acc
}

// b01o1t37: \delta_{j j1} \delta_{k o} \delta_{l i1} {V^{mn}_{ia}}
func (el *Elem) b01o1t37(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2006 := el.asym(m, n, i, el.nocc+a)
	if fv2006 != 0 {
		if j == j1 {
			if k == o {
				if l == i1 {
					acc += fv2006
				}
			}
		}
	}
	return acc
}

// b01o1t38: \delta_{j o} \delta_{k i1} \delta_{l j1} {V^{mn}_{ia}}
func (el *Elem) b01o1t38(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2007 := el.asym(m, n, i, el.nocc+a)
	if fv2007 != 0 {
		if j == o {
			if k == i1 {
				if l == j1 {
					acc += fv2007
				}
			}
		}
	}
	return acc
}

// b01o1t39: \delta_{i i1} \delta_{k o} \delta_{l j1} {V^{mn}_{ja}}
func (el *Elem) b01o1t39(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2008 := el.asym(m, n, j, el.nocc+a)
	if fv2008 != 0 {
		if i == i1 {
			if k == o {
				if l == j1 {
					acc += fv2008
				}
			}
		}
	}
	return acc
}

// b01o1t40: \delta_{i j1} \delta_{k i1} \delta_{l o} {V^{mn}_{ja}}
func (el *Elem) b01o1t40(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2009 := el.asym(m, n, j, el.nocc+a)
	if fv2009 != 0 {
		if i == j1 {
			if k == i1 {
				if l == o {
					acc += fv2009
				}
			}
		}
	}
	return acc
}

// b01o1t41: \delta_{i o} \delta_{k j1} \delta_{l i1} {V^{mn}_{ja}}
func (el *Elem) b01o1t41(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2010 := el.asym(m, n, j, el.nocc+a)
	if fv2010 != 0 {
		if i == o {
			if k == j1 {
				if l == i1 {
					acc += fv2010
				}
			}
		}
	}
	return acc
}

// b01o1t42: \delta_{i i1} \delta_{j j1} \delta_{l o} {V^{mn}_{ka}}
func (el *Elem) b01o1t42(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2011 := el.asym(m, n, k, el.nocc+a)
	if fv2011 != 0 {
		if i == i1 {
			if j == j1 {
				if l == o {
					acc += fv2011
				}
			}
		}
	}
	return acc
}

// b01o1t43: \delta_{i j1} \delta_{j o} \delta_{l i1} {V^{mn}_{ka}}
func (el *Elem) b01o1t43(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2012 := el.asym(m, n, k, el.nocc+a)
	if fv2012 != 0 {
		if i == j1 {
			if j == o {
				if l == i1 {
					acc += fv2012
				}
			}
		}
	}
	return acc
}

// b01o1t44: \delta_{i o} \delta_{j i1} \delta_{l j1} {V^{mn}_{ka}}
func (el *Elem) b01o1t44(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2013 := el.asym(m, n, k, el.nocc+a)
	if fv2013 != 0 {
		if i == o {
			if j == i1 {
				if l == j1 {
					acc += fv2013
				}
			}
		}
	}
	return acc
}

// b01o1t45: \delta_{i i1} \delta_{j o} \delta_{k j1} {V^{mn}_{la}}
func (el *Elem) b01o1t45(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2014 := el.asym(m, n, l, el.nocc+a)
	if fv2014 != 0 {
		if i == i1 {
			if j == o {
				if k == j1 {
					acc += fv2014
				}
			}
		}
	}
	return acc
}

// b01o1t46: \delta_{i j1} \delta_{j i1} \delta_{k o} {V^{mn}_{la}}
func (el *Elem) b01o1t46(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2015 := el.asym(m, n, l, el.nocc+a)
	if fv2015 != 0 {
		if i == j1 {
			if j == i1 {
				if k == o {
					acc += fv2015
				}
			}
		}
	}
	return acc
}

// b01o1t47: \delta_{i o} \delta_{j j1} \delta_{k i1} {V^{mn}_{la}}
func (el *Elem) b01o1t47(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2016 := el.asym(m, n, l, el.nocc+a)
	if fv2016 != 0 {
		if i == o {
			if j == j1 {
				if k == i1 {
					acc += fv2016
				}
			}
		}
	}
	return acc
}

// b01o1t48: \delta_{j i1} \delta_{k n} \delta_{l j1} {V^{mo}_{ia}}
func (el *Elem) b01o1t48(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2017 := el.asym(m, o, i, el.nocc+a)
	if fv2017 != 0 {
		if j == i1 {
			if k == n {
				if l == j1 {
					acc += fv2017
				}
			}
		}
	}
	return acc
}

// b01o1t49: \delta_{j j1} \delta_{k i1} \delta_{l n} {V^{mo}_{ia}}
func (el *Elem) b01o1t49(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2018 := el.asym(m, o, i, el.nocc+a)
	if fv2018 != 0 {
		if j == j1 {
			if k == i1 {
				if l == n {
					acc += fv2018
				}
			}
		}
	}
	return acc
}

// b01o1t50: \delta_{j n} \delta_{k j1} \delta_{l i1} {V^{mo}_{ia}}
func (el *Elem) b01o1t50(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2019 := el.asym(m, o, i, el.nocc+a)
	if fv2019 != 0 {
		if j == n {
			if k == j1 {
				if l == i1 {
					acc += fv2019
				}
			}
		}
	}
	return acc
}

// b01o1t51: \delta_{i i1} \delta_{k j1} \delta_{l n} {V^{mo}_{ja}}
func (el *Elem) b01o1t51(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2020 := el.asym(m, o, j, el.nocc+a)
	if fv2020 != 0 {
		if i == i1 {
			if k == j1 {
				if l == n {
					acc += fv2020
				}
			}
		}
	}
	return acc
}

// b01o1t52: \delta_{i j1} \delta_{k n} \delta_{l i1} {V^{mo}_{ja}}
func (el *Elem) b01o1t52(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2021 := el.asym(m, o, j, el.nocc+a)
	if fv2021 != 0 {
		if i == j1 {
			if k == n {
				if l == i1 {
					acc += fv2021
				}
			}
		}
	}
	return acc
}

// b01o1t53: \delta_{i n} \delta_{k i1} \delta_{l j1} {V^{mo}_{ja}}
func (el *Elem) b01o1t53(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2022 := el.asym(m, o, j, el.nocc+a)
	if fv2022 != 0 {
		if i == n {
			if k == i1 {
				if l == j1 {
					acc += fv2022
				}
			}
		}
	}
	return acc
}

// b01o1t54: \delta_{i i1} \delta_{j n} \delta_{l j1} {V^{mo}_{ka}}
func (el *Elem) b01o1t54(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2023 := el.asym(m, o, k, el.nocc+a)
	if fv2023 != 0 {
		if i == i1 {
			if j == n {
				if l == j1 {
					acc += fv2023
				}
			}
		}
	}
	return acc
}

// b01o1t55: \delta_{i j1} \delta_{j i1} \delta_{l n} {V^{mo}_{ka}}
func (el *Elem) b01o1t55(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2024 := el.asym(m, o, k, el.nocc+a)
	if fv2024 != 0 {
		if i == j1 {
			if j == i1 {
				if l == n {
					acc += fv2024
				}
			}
		}
	}
	return acc
}

// b01o1t56: \delta_{i n} \delta_{j j1} \delta_{l i1} {V^{mo}_{ka}}
func (el *Elem) b01o1t56(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2025 := el.asym(m, o, k, el.nocc+a)
	if fv2025 != 0 {
		if i == n {
			if j == j1 {
				if l == i1 {
					acc += fv2025
				}
			}
		}
	}
	return acc
}

// b01o1t57: \delta_{i i1} \delta_{j j1} \delta_{k n} {V^{mo}_{la}}
func (el *Elem) b01o1t57(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2026 := el.asym(m, o, l, el.nocc+a)
	if fv2026 != 0 {
		if i == i1 {
			if j == j1 {
				if k == n {
					acc += fv2026
				}
			}
		}
	}
	return acc
}

// b01o1t58: \delta_{i j1} \delta_{j n} \delta_{k i1} {V^{mo}_{la}}
func (el *Elem) b01o1t58(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2027 := el.asym(m, o, l, el.nocc+a)
	if fv2027 != 0 {
		if i == j1 {
			if j == n {
				if k == i1 {
					acc += fv2027
				}
			}
		}
	}
	return acc
}

// b01o1t59: \delta_{i n} \delta_{j i1} \delta_{k j1} {V^{mo}_{la}}
func (el *Elem) b01o1t59(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2028 := el.asym(m, o, l, el.nocc+a)
	if fv2028 != 0 {
		if i == n {
			if j == i1 {
				if k == j1 {
					acc += fv2028
				}
			}
		}
	}
	return acc
}

// b01o1t60: \delta_{j j1} \delta_{k o} \delta_{l m} {V^{ni1}_{ia}}
func (el *Elem) b01o1t60(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2029 := el.asym(n, i1, i, el.nocc+a)
	if fv2029 != 0 {
		if j == j1 {
			if k == o {
				if l == m {
					acc += fv2029
				}
			}
		}
	}
	return acc
}

// b01o1t61: \delta_{j m} \delta_{k j1} \delta_{l o} {V^{ni1}_{ia}}
func (el *Elem) b01o1t61(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2030 := el.asym(n, i1, i, el.nocc+a)
	if fv2030 != 0 {
		if j == m {
			if k == j1 {
				if l == o {
					acc += fv2030
				}
			}
		}
	}
	return acc
}

// b01o1t62: \delta_{j o} \delta_{k m} \delta_{l j1} {V^{ni1}_{ia}}
func (el *Elem) b01o1t62(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2031 := el.asym(n, i1, i, el.nocc+a)
	if fv2031 != 0 {
		if j == o {
			if k == m {
				if l == j1 {
					acc += fv2031
				}
			}
		}
	}
	return acc
}

// b01o1t63: \delta_{i j1} \delta_{k m} \delta_{l o} {V^{ni1}_{ja}}
func (el *Elem) b01o1t63(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2032 := el.asym(n, i1, j, el.nocc+a)
	if fv2032 != 0 {
		if i == j1 {
			if k == m {
				if l == o {
					acc += fv2032
				}
			}
		}
	}
	return acc
}

// b01o1t64: \delta_{i m} \delta_{k o} \delta_{l j1} {V^{ni1}_{ja}}
func (el *Elem) b01o1t64(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2033 := el.asym(n, i1, j, el.nocc+a)
	if fv2033 != 0 {
		if i == m {
			if k == o {
				if l == j1 {
					acc += fv2033
				}
			}
		}
	}
	return acc
}

// b01o1t65: \delta_{i o} \delta_{k j1} \delta_{l m} {V^{ni1}_{ja}}
func (el *Elem) b01o1t65(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2034 := el.asym(n, i1, j, el.nocc+a)
	if fv2034 != 0 {
		if i == o {
			if k == j1 {
				if l == m {
					acc += fv2034
				}
			}
		}
	}
	return acc
}

// b01o1t66: \delta_{i j1} \delta_{j o} \delta_{l m} {V^{ni1}_{ka}}
func (el *Elem) b01o1t66(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2035 := el.asym(n, i1, k, el.nocc+a)
	if fv2035 != 0 {
		if i == j1 {
			if j == o {
				if l == m {
					acc += fv2035
				}
			}
		}
	}
	return acc
}

// b01o1t67: \delta_{i m} \delta_{j j1} \delta_{l o} {V^{ni1}_{ka}}
func (el *Elem) b01o1t67(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2036 := el.asym(n, i1, k, el.nocc+a)
	if fv2036 != 0 {
		if i == m {
			if j == j1 {
				if l == o {
					acc += fv2036
				}
			}
		}
	}
	return acc
}

// b01o1t68: \delta_{i o} \delta_{j m} \delta_{l j1} {V^{ni1}_{ka}}
func (el *Elem) b01o1t68(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2037 := el.asym(n, i1, k, el.nocc+a)
	if fv2037 != 0 {
		if i == o {
			if j == m {
				if l == j1 {
					acc += fv2037
				}
			}
		}
	}
	return acc
}

// b01o1t69: \delta_{i j1} \delta_{j m} \delta_{k o} {V^{ni1}_{la}}
func (el *Elem) b01o1t69(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2038 := el.asym(n, i1, l, el.nocc+a)
	if fv2038 != 0 {
		if i == j1 {
			if j == m {
				if k == o {
					acc += fv2038
				}
			}
		}
	}
	return acc
}

// b01o1t70: \delta_{i m} \delta_{j o} \delta_{k j1} {V^{ni1}_{la}}
func (el *Elem) b01o1t70(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2039 := el.asym(n, i1, l, el.nocc+a)
	if fv2039 != 0 {
		if i == m {
			if j == o {
				if k == j1 {
					acc += fv2039
				}
			}
		}
	}
	return acc
}

// b01o1t71: \delta_{i o} \delta_{j j1} \delta_{k m} {V^{ni1}_{la}}
func (el *Elem) b01o1t71(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2040 := el.asym(n, i1, l, el.nocc+a)
	if fv2040 != 0 {
		if i == o {
			if j == j1 {
				if k == m {
					acc += fv2040
				}
			}
		}
	}
	return acc
}

// b01o1t72: \delta_{j i1} \delta_{k m} \delta_{l o} {V^{nj1}_{ia}}
func (el *Elem) b01o1t72(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2041 := el.asym(n, j1, i, el.nocc+a)
	if fv2041 != 0 {
		if j == i1 {
			if k == m {
				if l == o {
					acc += fv2041
				}
			}
		}
	}
	return acc
}

// b01o1t73: \delta_{j m} \delta_{k o} \delta_{l i1} {V^{nj1}_{ia}}
func (el *Elem) b01o1t73(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2042 := el.asym(n, j1, i, el.nocc+a)
	if fv2042 != 0 {
		if j == m {
			if k == o {
				if l == i1 {
					acc += fv2042
				}
			}
		}
	}
	return acc
}

// b01o1t74: \delta_{j o} \delta_{k i1} \delta_{l m} {V^{nj1}_{ia}}
func (el *Elem) b01o1t74(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2043 := el.asym(n, j1, i, el.nocc+a)
	if fv2043 != 0 {
		if j == o {
			if k == i1 {
				if l == m {
					acc += fv2043
				}
			}
		}
	}
	return acc
}

// b01o1t75: \delta_{i i1} \delta_{k o} \delta_{l m} {V^{nj1}_{ja}}
func (el *Elem) b01o1t75(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2044 := el.asym(n, j1, j, el.nocc+a)
	if fv2044 != 0 {
		if i == i1 {
			if k == o {
				if l == m {
					acc += fv2044
				}
			}
		}
	}
	return acc
}

// b01o1t76: \delta_{i m} \delta_{k i1} \delta_{l o} {V^{nj1}_{ja}}
func (el *Elem) b01o1t76(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2045 := el.asym(n, j1, j, el.nocc+a)
	if fv2045 != 0 {
		if i == m {
			if k == i1 {
				if l == o {
					acc += fv2045
				}
			}
		}
	}
	return acc
}

// b01o1t77: \delta_{i o} \delta_{k m} \delta_{l i1} {V^{nj1}_{ja}}
func (el *Elem) b01o1t77(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2046 := el.asym(n, j1, j, el.nocc+a)
	if fv2046 != 0 {
		if i == o {
			if k == m {
				if l == i1 {
					acc += fv2046
				}
			}
		}
	}
	return acc
}

// b01o1t78: \delta_{i i1} \delta_{j m} \delta_{l o} {V^{nj1}_{ka}}
func (el *Elem) b01o1t78(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2047 := el.asym(n, j1, k, el.nocc+a)
	if fv2047 != 0 {
		if i == i1 {
			if j == m {
				if l == o {
					acc += fv2047
				}
			}
		}
	}
	return acc
}

// b01o1t79: \delta_{i m} \delta_{j o} \delta_{l i1} {V^{nj1}_{ka}}
func (el *Elem) b01o1t79(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2048 := el.asym(n, j1, k, el.nocc+a)
	if fv2048 != 0 {
		if i == m {
			if j == o {
				if l == i1 {
					acc += fv2048
				}
			}
		}
	}
	return acc
}

// b01o1t80: \delta_{i o} \delta_{j i1} \delta_{l m} {V^{nj1}_{ka}}
func (el *Elem) b01o1t80(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2049 := el.asym(n, j1, k, el.nocc+a)
	if fv2049 != 0 {
		if i == o {
			if j == i1 {
				if l == m {
					acc += fv2049
				}
			}
		}
	}
	return acc
}

// b01o1t81: \delta_{i i1} \delta_{j o} \delta_{k m} {V^{nj1}_{la}}
func (el *Elem) b01o1t81(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2050 := el.asym(n, j1, l, el.nocc+a)
	if fv2050 != 0 {
		if i == i1 {
			if j == o {
				if k == m {
					acc += fv2050
				}
			}
		}
	}
	return acc
}

// b01o1t82: \delta_{i m} \delta_{j i1} \delta_{k o} {V^{nj1}_{la}}
func (el *Elem) b01o1t82(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2051 := el.asym(n, j1, l, el.nocc+a)
	if fv2051 != 0 {
		if i == m {
			if j == i1 {
				if k == o {
					acc += fv2051
				}
			}
		}
	}
	return acc
}

// b01o1t83: \delta_{i o} \delta_{j m} \delta_{k i1} {V^{nj1}_{la}}
func (el *Elem) b01o1t83(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2052 := el.asym(n, j1, l, el.nocc+a)
	if fv2052 != 0 {
		if i == o {
			if j == m {
				if k == i1 {
					acc += fv2052
				}
			}
		}
	}
	return acc
}

// b01o1t84: \delta_{j i1} \delta_{k j1} \delta_{l m} {V^{no}_{ia}}
func (el *Elem) b01o1t84(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2053 := el.asym(n, o, i, el.nocc+a)
	if fv2053 != 0 {
		if j == i1 {
			if k == j1 {
				if l == m {
					acc += fv2053
				}
			}
		}
	}
	return acc
}

// b01o1t85: \delta_{j j1} \delta_{k m} \delta_{l i1} {V^{no}_{ia}}
func (el *Elem) b01o1t85(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2054 := el.asym(n, o, i, el.nocc+a)
	if fv2054 != 0 {
		if j == j1 {
			if k == m {
				if l == i1 {
					acc += fv2054
				}
			}
		}
	}
	return acc
}

// b01o1t86: \delta_{j m} \delta_{k i1} \delta_{l j1} {V^{no}_{ia}}
func (el *Elem) b01o1t86(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2055 := el.asym(n, o, i, el.nocc+a)
	if fv2055 != 0 {
		if j == m {
			if k == i1 {
				if l == j1 {
					acc += fv2055
				}
			}
		}
	}
	return acc
}

// b01o1t87: \delta_{i i1} \delta_{k m} \delta_{l j1} {V^{no}_{ja}}
func (el *Elem) b01o1t87(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2056 := el.asym(n, o, j, el.nocc+a)
	if fv2056 != 0 {
		if i == i1 {
			if k == m {
				if l == j1 {
					acc += fv2056
				}
			}
		}
	}
	return acc
}

// b01o1t88: \delta_{i j1} \delta_{k i1} \delta_{l m} {V^{no}_{ja}}
func (el *Elem) b01o1t88(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2057 := el.asym(n, o, j, el.nocc+a)
	if fv2057 != 0 {
		if i == j1 {
			if k == i1 {
				if l == m {
					acc += fv2057
				}
			}
		}
	}
	return acc
}

// b01o1t89: \delta_{i m} \delta_{k j1} \delta_{l i1} {V^{no}_{ja}}
func (el *Elem) b01o1t89(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2058 := el.asym(n, o, j, el.nocc+a)
	if fv2058 != 0 {
		if i == m {
			if k == j1 {
				if l == i1 {
					acc += fv2058
				}
			}
		}
	}
	return acc
}

// b01o1t90: \delta_{i i1} \delta_{j j1} \delta_{l m} {V^{no}_{ka}}
func (el *Elem) b01o1t90(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2059 := el.asym(n, o, k, el.nocc+a)
	if fv2059 != 0 {
		if i == i1 {
			if j == j1 {
				if l == m {
					acc += fv2059
				}
			}
		}
	}
	return acc
}

// b01o1t91: \delta_{i j1} \delta_{j m} \delta_{l i1} {V^{no}_{ka}}
func (el *Elem) b01o1t91(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2060 := el.asym(n, o, k, el.nocc+a)
	if fv2060 != 0 {
		if i == j1 {
			if j == m {
				if l == i1 {
					acc += fv2060
				}
			}
		}
	}
	return acc
}

// b01o1t92: \delta_{i m} \delta_{j i1} \delta_{l j1} {V^{no}_{ka}}
func (el *Elem) b01o1t92(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2061 := el.asym(n, o, k, el.nocc+a)
	if fv2061 != 0 {
		if i == m {
			if j == i1 {
				if l == j1 {
					acc += fv2061
				}
			}
		}
	}
	return acc
}

// b01o1t93: \delta_{i i1} \delta_{j m} \delta_{k j1} {V^{no}_{la}}
func (el *Elem) b01o1t93(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2062 := el.asym(n, o, l, el.nocc+a)
	if fv2062 != 0 {
		if i == i1 {
			if j == m {
				if k == j1 {
					acc += fv2062
				}
			}
		}
	}
	return acc
}

// b01o1t94: \delta_{i j1} \delta_{j i1} \delta_{k m} {V^{no}_{la}}
func (el *Elem) b01o1t94(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2063 := el.asym(n, o, l, el.nocc+a)
	if fv2063 != 0 {
		if i == j1 {
			if j == i1 {
				if k == m {
					acc += fv2063
				}
			}
		}
	}
	return acc
}

// b01o1t95: \delta_{i m} \delta_{j j1} \delta_{k i1} {V^{no}_{la}}
func (el *Elem) b01o1t95(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2064 := el.asym(n, o, l, el.nocc+a)
	if fv2064 != 0 {
		if i == m {
			if j == j1 {
				if k == i1 {
					acc += fv2064
				}
			}
		}
	}
	return acc
}

// b01o1t96: \delta_{j j1} \delta_{k m} \delta_{l n} {V^{oi1}_{ia}}
func (el *Elem) b01o1t96(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2065 := el.asym(o, i1, i, el.nocc+a)
	if fv2065 != 0 {
		if j == j1 {
			if k == m {
				if l == n {
					acc += fv2065
				}
			}
		}
	}
	return acc
}

// b01o1t97: \delta_{j m} \delta_{k n} \delta_{l j1} {V^{oi1}_{ia}}
func (el *Elem) b01o1t97(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2066 := el.asym(o, i1, i, el.nocc+a)
	if fv2066 != 0 {
		if j == m {
			if k == n {
				if l == j1 {
					acc += fv2066
				}
			}
		}
	}
	return acc
}

// b01o1t98: \delta_{j n} \delta_{k j1} \delta_{l m} {V^{oi1}_{ia}}
func (el *Elem) b01o1t98(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2067 := el.asym(o, i1, i, el.nocc+a)
	if fv2067 != 0 {
		if j == n {
			if k == j1 {
				if l == m {
					acc += fv2067
				}
			}
		}
	}
	return acc
}

// b01o1t99: \delta_{i j1} \delta_{k n} \delta_{l m} {V^{oi1}_{ja}}
func (el *Elem) b01o1t99(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2068 := el.asym(o, i1, j, el.nocc+a)
	if fv2068 != 0 {
		if i == j1 {
			if k == n {
				if l == m {
					acc += fv2068
				}
			}
		}
	}
	return acc
}

// b01o1t100: \delta_{i m} \delta_{k j1} \delta_{l n} {V^{oi1}_{ja}}
func (el *Elem) b01o1t100(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2069 := el.asym(o, i1, j, el.nocc+a)
	if fv2069 != 0 {
		if i == m {
			if k == j1 {
				if l == n {
					acc += fv2069
				}
			}
		}
	}
	return acc
}

// b01o1t101: \delta_{i n} \delta_{k m} \delta_{l j1} {V^{oi1}_{ja}}
func (el *Elem) b01o1t101(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2070 := el.asym(o, i1, j, el.nocc+a)
	if fv2070 != 0 {
		if i == n {
			if k == m {
				if l == j1 {
					acc += fv2070
				}
			}
		}
	}
	return acc
}

// b01o1t102: \delta_{i j1} \delta_{j m} \delta_{l n} {V^{oi1}_{ka}}
func (el *Elem) b01o1t102(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2071 := el.asym(o, i1, k, el.nocc+a)
	if fv2071 != 0 {
		if i == j1 {
			if j == m {
				if l == n {
					acc += fv2071
				}
			}
		}
	}
	return acc
}

// b01o1t103: \delta_{i m} \delta_{j n} \delta_{l j1} {V^{oi1}_{ka}}
func (el *Elem) b01o1t103(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2072 := el.asym(o, i1, k, el.nocc+a)
	if fv2072 != 0 {
		if i == m {
			if j == n {
				if l == j1 {
					acc += fv2072
				}
			}
		}
	}
	return acc
}

// b01o1t104: \delta_{i n} \delta_{j j1} \delta_{l m} {V^{oi1}_{ka}}
func (el *Elem) b01o1t104(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2073 := el.asym(o, i1, k, el.nocc+a)
	if fv2073 != 0 {
		if i == n {
			if j == j1 {
				if l == m {
					acc += fv2073
				}
			}
		}
	}
	return acc
}

// b01o1t105: \delta_{i j1} \delta_{j n} \delta_{k m} {V^{oi1}_{la}}
func (el *Elem) b01o1t105(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2074 := el.asym(o, i1, l, el.nocc+a)
	if fv2074 != 0 {
		if i == j1 {
			if j == n {
				if k == m {
					acc += fv2074
				}
			}
		}
	}
	return acc
}

// b01o1t106: \delta_{i m} \delta_{j j1} \delta_{k n} {V^{oi1}_{la}}
func (el *Elem) b01o1t106(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2075 := el.asym(o, i1, l, el.nocc+a)
	if fv2075 != 0 {
		if i == m {
			if j == j1 {
				if k == n {
					acc += fv2075
				}
			}
		}
	}
	return acc
}

// b01o1t107: \delta_{i n} \delta_{j m} \delta_{k j1} {V^{oi1}_{la}}
func (el *Elem) b01o1t107(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2076 := el.asym(o, i1, l, el.nocc+a)
	if fv2076 != 0 {
		if i == n {
			if j == m {
				if k == j1 {
					acc += fv2076
				}
			}
		}
	}
	return acc
}

// b01o1t108: \delta_{j i1} \delta_{k n} \delta_{l m} {V^{oj1}_{ia}}
func (el *Elem) b01o1t108(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2077 := el.asym(o, j1, i, el.nocc+a)
	if fv2077 != 0 {
		if j == i1 {
			if k == n {
				if l == m {
					acc += fv2077
				}
			}
		}
	}
	return acc
}

// b01o1t109: \delta_{j m} \delta_{k i1} \delta_{l n} {V^{oj1}_{ia}}
func (el *Elem) b01o1t109(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2078 := el.asym(o, j1, i, el.nocc+a)
	if fv2078 != 0 {
		if j == m {
			if k == i1 {
				if l == n {
					acc += fv2078
				}
			}
		}
	}
	return acc
}

// b01o1t110: \delta_{j n} \delta_{k m} \delta_{l i1} {V^{oj1}_{ia}}
func (el *Elem) b01o1t110(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2079 := el.asym(o, j1, i, el.nocc+a)
	if fv2079 != 0 {
		if j == n {
			if k == m {
				if l == i1 {
					acc += fv2079
				}
			}
		}
	}
	return acc
}

// b01o1t111: \delta_{i i1} \delta_{k m} \delta_{l n} {V^{oj1}_{ja}}
func (el *Elem) b01o1t111(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2080 := el.asym(o, j1, j, el.nocc+a)
	if fv2080 != 0 {
		if i == i1 {
			if k == m {
				if l == n {
					acc += fv2080
				}
			}
		}
	}
	return acc
}

// b01o1t112: \delta_{i m} \delta_{k n} \delta_{l i1} {V^{oj1}_{ja}}
func (el *Elem) b01o1t112(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2081 := el.asym(o, j1, j, el.nocc+a)
	if fv2081 != 0 {
		if i == m {
			if k == n {
				if l == i1 {
					acc += fv2081
				}
			}
		}
	}
	return acc
}

// b01o1t113: \delta_{i n} \delta_{k i1} \delta_{l m} {V^{oj1}_{ja}}
func (el *Elem) b01o1t113(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2082 := el.asym(o, j1, j, el.nocc+a)
	if fv2082 != 0 {
		if i == n {
			if k == i1 {
				if l == m {
					acc += fv2082
				}
			}
		}
	}
	return acc
}

// b01o1t114: \delta_{i i1} \delta_{j n} \delta_{l m} {V^{oj1}_{ka}}
func (el *Elem) b01o1t114(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2083 := el.asym(o, j1, k, el.nocc+a)
	if fv2083 != 0 {
		if i == i1 {
			if j == n {
				if l == m {
					acc += fv2083
				}
			}
		}
	}
	return acc
}

// b01o1t115: \delta_{i m} \delta_{j i1} \delta_{l n} {V^{oj1}_{ka}}
func (el *Elem) b01o1t115(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2084 := el.asym(o, j1, k, el.nocc+a)
	if fv2084 != 0 {
		if i == m {
			if j == i1 {
				if l == n {
					acc += fv2084
				}
			}
		}
	}
	return acc
}

// b01o1t116: \delta_{i n} \delta_{j m} \delta_{l i1} {V^{oj1}_{ka}}
func (el *Elem) b01o1t116(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2085 := el.asym(o, j1, k, el.nocc+a)
	if fv2085 != 0 {
		if i == n {
			if j == m {
				if l == i1 {
					acc += fv2085
				}
			}
		}
	}
	return acc
}

// b01o1t117: \delta_{i i1} \delta_{j m} \delta_{k n} {V^{oj1}_{la}}
func (el *Elem) b01o1t117(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2086 := el.asym(o, j1, l, el.nocc+a)
	if fv2086 != 0 {
		if i == i1 {
			if j == m {
				if k == n {
					acc += fv2086
				}
			}
		}
	}
	return acc
}

// b01o1t118: \delta_{i m} \delta_{j n} \delta_{k i1} {V^{oj1}_{la}}
func (el *Elem) b01o1t118(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2087 := el.asym(o, j1, l, el.nocc+a)
	if fv2087 != 0 {
		if i == m {
			if j == n {
				if k == i1 {
					acc += fv2087
				}
			}
		}
	}
	return acc
}

// b01o1t119: \delta_{i n} \delta_{j i1} \delta_{k m} {V^{oj1}_{la}}
func (el *Elem) b01o1t119(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2088 := el.asym(o, j1, l, el.nocc+a)
	if fv2088 != 0 {
		if i == n {
			if j == i1 {
				if k == m {
					acc += fv2088
				}
			}
		}
	}
	return acc
}

// b01o1t120: - \delta_{j m} \delta_{k o} \delta_{l n} {V^{i1j1}_{ia}}
func (el *Elem) b01o1t120(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2089 := el.asym(i1, j1, i, el.nocc+a)
	if fv2089 != 0 {
		if j == m {
			if k == o {
				if l == n {
					acc += fv2089
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t121: - \delta_{j n} \delta_{k m} \delta_{l o} {V^{i1j1}_{ia}}
func (el *Elem) b01o1t121(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2090 := el.asym(i1, j1, i, el.nocc+a)
	if fv2090 != 0 {
		if j == n {
			if k == m {
				if l == o {
					acc += fv2090
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t122: - \delta_{j o} \delta_{k n} \delta_{l m} {V^{i1j1}_{ia}}
func (el *Elem) b01o1t122(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2091 := el.asym(i1, j1, i, el.nocc+a)
	if fv2091 != 0 {
		if j == o {
			if k == n {
				if l == m {
					acc += fv2091
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t123: - \delta_{i m} \delta_{k n} \delta_{l o} {V^{i1j1}_{ja}}
func (el *Elem) b01o1t123(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2092 := el.asym(i1, j1, j, el.nocc+a)
	if fv2092 != 0 {
		if i == m {
			if k == n {
				if l == o {
					acc += fv2092
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t124: - \delta_{i n} \delta_{k o} \delta_{l m} {V^{i1j1}_{ja}}
func (el *Elem) b01o1t124(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2093 := el.asym(i1, j1, j, el.nocc+a)
	if fv2093 != 0 {
		if i == n {
			if k == o {
				if l == m {
					acc += fv2093
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t125: - \delta_{i o} \delta_{k m} \delta_{l n} {V^{i1j1}_{ja}}
func (el *Elem) b01o1t125(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2094 := el.asym(i1, j1, j, el.nocc+a)
	if fv2094 != 0 {
		if i == o {
			if k == m {
				if l == n {
					acc += fv2094
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t126: - \delta_{i m} \delta_{j o} \delta_{l n} {V^{i1j1}_{ka}}
func (el *Elem) b01o1t126(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2095 := el.asym(i1, j1, k, el.nocc+a)
	if fv2095 != 0 {
		if i == m {
			if j == o {
				if l == n {
					acc += fv2095
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t127: - \delta_{i n} \delta_{j m} \delta_{l o} {V^{i1j1}_{ka}}
func (el *Elem) b01o1t127(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2096 := el.asym(i1, j1, k, el.nocc+a)
	if fv2096 != 0 {
		if i == n {
			if j == m {
				if l == o {
					acc += fv2096
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t128: - \delta_{i o} \delta_{j n} \delta_{l m} {V^{i1j1}_{ka}}
func (el *Elem) b01o1t128(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2097 := el.asym(i1, j1, k, el.nocc+a)
	if fv2097 != 0 {
		if i == o {
			if j == n {
				if l == m {
					acc += fv2097
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t129: - \delta_{i m} \delta_{j n} \delta_{k o} {V^{i1j1}_{la}}
func (el *Elem) b01o1t129(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2098 := el.asym(i1, j1, l, el.nocc+a)
	if fv2098 != 0 {
		if i == m {
			if j == n {
				if k == o {
					acc += fv2098
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t130: - \delta_{i n} \delta_{j o} \delta_{k m} {V^{i1j1}_{la}}
func (el *Elem) b01o1t130(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2099 := el.asym(i1, j1, l, el.nocc+a)
	if fv2099 != 0 {
		if i == n {
			if j == o {
				if k == m {
					acc += fv2099
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t131: - \delta_{i o} \delta_{j m} \delta_{k n} {V^{i1j1}_{la}}
func (el *Elem) b01o1t131(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2100 := el.asym(i1, j1, l, el.nocc+a)
	if fv2100 != 0 {
		if i == o {
			if j == m {
				if k == n {
					acc += fv2100
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t132: - \delta_{j j1} \delta_{k o} \delta_{l n} {V^{mi1}_{ia}}
func (el *Elem) b01o1t132(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2101 := el.asym(m, i1, i, el.nocc+a)
	if fv2101 != 0 {
		if j == j1 {
			if k == o {
				if l == n {
					acc += fv2101
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t133: - \delta_{j n} \delta_{k j1} \delta_{l o} {V^{mi1}_{ia}}
func (el *Elem) b01o1t133(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2102 := el.asym(m, i1, i, el.nocc+a)
	if fv2102 != 0 {
		if j == n {
			if k == j1 {
				if l == o {
					acc += fv2102
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t134: - \delta_{j o} \delta_{k n} \delta_{l j1} {V^{mi1}_{ia}}
func (el *Elem) b01o1t134(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2103 := el.asym(m, i1, i, el.nocc+a)
	if fv2103 != 0 {
		if j == o {
			if k == n {
				if l == j1 {
					acc += fv2103
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t135: - \delta_{i j1} \delta_{k n} \delta_{l o} {V^{mi1}_{ja}}
func (el *Elem) b01o1t135(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2104 := el.asym(m, i1, j, el.nocc+a)
	if fv2104 != 0 {
		if i == j1 {
			if k == n {
				if l == o {
					acc += fv2104
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t136: - \delta_{i n} \delta_{k o} \delta_{l j1} {V^{mi1}_{ja}}
func (el *Elem) b01o1t136(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2105 := el.asym(m, i1, j, el.nocc+a)
	if fv2105 != 0 {
		if i == n {
			if k == o {
				if l == j1 {
					acc += fv2105
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t137: - \delta_{i o} \delta_{k j1} \delta_{l n} {V^{mi1}_{ja}}
func (el *Elem) b01o1t137(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2106 := el.asym(m, i1, j, el.nocc+a)
	if fv2106 != 0 {
		if i == o {
			if k == j1 {
				if l == n {
					acc += fv2106
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t138: - \delta_{i j1} \delta_{j o} \delta_{l n} {V^{mi1}_{ka}}
func (el *Elem) b01o1t138(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2107 := el.asym(m, i1, k, el.nocc+a)
	if fv2107 != 0 {
		if i == j1 {
			if j == o {
				if l == n {
					acc += fv2107
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t139: - \delta_{i n} \delta_{j j1} \delta_{l o} {V^{mi1}_{ka}}
func (el *Elem) b01o1t139(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2108 := el.asym(m, i1, k, el.nocc+a)
	if fv2108 != 0 {
		if i == n {
			if j == j1 {
				if l == o {
					acc += fv2108
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t140: - \delta_{i o} \delta_{j n} \delta_{l j1} {V^{mi1}_{ka}}
func (el *Elem) b01o1t140(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2109 := el.asym(m, i1, k, el.nocc+a)
	if fv2109 != 0 {
		if i == o {
			if j == n {
				if l == j1 {
					acc += fv2109
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t141: - \delta_{i j1} \delta_{j n} \delta_{k o} {V^{mi1}_{la}}
func (el *Elem) b01o1t141(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2110 := el.asym(m, i1, l, el.nocc+a)
	if fv2110 != 0 {
		if i == j1 {
			if j == n {
				if k == o {
					acc += fv2110
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t142: - \delta_{i n} \delta_{j o} \delta_{k j1} {V^{mi1}_{la}}
func (el *Elem) b01o1t142(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2111 := el.asym(m, i1, l, el.nocc+a)
	if fv2111 != 0 {
		if i == n {
			if j == o {
				if k == j1 {
					acc += fv2111
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t143: - \delta_{i o} \delta_{j j1} \delta_{k n} {V^{mi1}_{la}}
func (el *Elem) b01o1t143(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2112 := el.asym(m, i1, l, el.nocc+a)
	if fv2112 != 0 {
		if i == o {
			if j == j1 {
				if k == n {
					acc += fv2112
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t144: - \delta_{j i1} \delta_{k n} \delta_{l o} {V^{mj1}_{ia}}
func (el *Elem) b01o1t144(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2113 := el.asym(m, j1, i, el.nocc+a)
	if fv2113 != 0 {
		if j == i1 {
			if k == n {
				if l == o {
					acc += fv2113
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t145: - \delta_{j n} \delta_{k o} \delta_{l i1} {V^{mj1}_{ia}}
func (el *Elem) b01o1t145(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2114 := el.asym(m, j1, i, el.nocc+a)
	if fv2114 != 0 {
		if j == n {
			if k == o {
				if l == i1 {
					acc += fv2114
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t146: - \delta_{j o} \delta_{k i1} \delta_{l n} {V^{mj1}_{ia}}
func (el *Elem) b01o1t146(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2115 := el.asym(m, j1, i, el.nocc+a)
	if fv2115 != 0 {
		if j == o {
			if k == i1 {
				if l == n {
					acc += fv2115
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t147: - \delta_{i i1} \delta_{k o} \delta_{l n} {V^{mj1}_{ja}}
func (el *Elem) b01o1t147(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2116 := el.asym(m, j1, j, el.nocc+a)
	if fv2116 != 0 {
		if i == i1 {
			if k == o {
				if l == n {
					acc += fv2116
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t148: - \delta_{i n} \delta_{k i1} \delta_{l o} {V^{mj1}_{ja}}
func (el *Elem) b01o1t148(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2117 := el.asym(m, j1, j, el.nocc+a)
	if fv2117 != 0 {
		if i == n {
			if k == i1 {
				if l == o {
					acc += fv2117
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t149: - \delta_{i o} \delta_{k n} \delta_{l i1} {V^{mj1}_{ja}}
func (el *Elem) b01o1t149(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2118 := el.asym(m, j1, j, el.nocc+a)
	if fv2118 != 0 {
		if i == o {
			if k == n {
				if l == i1 {
					acc += fv2118
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t150: - \delta_{i i1} \delta_{j n} \delta_{l o} {V^{mj1}_{ka}}
func (el *Elem) b01o1t150(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2119 := el.asym(m, j1, k, el.nocc+a)
	if fv2119 != 0 {
		if i == i1 {
			if j == n {
				if l == o {
					acc += fv2119
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t151: - \delta_{i n} \delta_{j o} \delta_{l i1} {V^{mj1}_{ka}}
func (el *Elem) b01o1t151(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2120 := el.asym(m, j1, k, el.nocc+a)
	if fv2120 != 0 {
		if i == n {
			if j == o {
				if l == i1 {
					acc += fv2120
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t152: - \delta_{i o} \delta_{j i1} \delta_{l n} {V^{mj1}_{ka}}
func (el *Elem) b01o1t152(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2121 := el.asym(m, j1, k, el.nocc+a)
	if fv2121 != 0 {
		if i == o {
			if j == i1 {
				if l == n {
					acc += fv2121
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t153: - \delta_{i i1} \delta_{j o} \delta_{k n} {V^{mj1}_{la}}
func (el *Elem) b01o1t153(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2122 := el.asym(m, j1, l, el.nocc+a)
	if fv2122 != 0 {
		if i == i1 {
			if j == o {
				if k == n {
					acc += fv2122
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t154: - \delta_{i n} \delta_{j i1} \delta_{k o} {V^{mj1}_{la}}
func (el *Elem) b01o1t154(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2123 := el.asym(m, j1, l, el.nocc+a)
	if fv2123 != 0 {
		if i == n {
			if j == i1 {
				if k == o {
					acc += fv2123
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t155: - \delta_{i o} \delta_{j n} \delta_{k i1} {V^{mj1}_{la}}
func (el *Elem) b01o1t155(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2124 := el.asym(m, j1, l, el.nocc+a)
	if fv2124 != 0 {
		if i == o {
			if j == n {
				if k == i1 {
					acc += fv2124
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t156: - \delta_{j i1} \delta_{k o} \delta_{l j1} {V^{mn}_{ia}}
func (el *Elem) b01o1t156(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2125 := el.asym(m, n, i, el.nocc+a)
	if fv2125 != 0 {
		if j == i1 {
			if k == o {
				if l == j1 {
					acc += fv2125
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t157: - \delta_{j j1} \delta_{k i1} \delta_{l o} {V^{mn}_{ia}}
func (el *Elem) b01o1t157(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2126 := el.asym(m, n, i, el.nocc+a)
	if fv2126 != 0 {
		if j == j1 {
			if k == i1 {
				if l == o {
					acc += fv2126
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t158: - \delta_{j o} \delta_{k j1} \delta_{l i1} {V^{mn}_{ia}}
func (el *Elem) b01o1t158(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2127 := el.asym(m, n, i, el.nocc+a)
	if fv2127 != 0 {
		if j == o {
			if k == j1 {
				if l == i1 {
					acc += fv2127
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t159: - \delta_{i i1} \delta_{k j1} \delta_{l o} {V^{mn}_{ja}}
func (el *Elem) b01o1t159(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2128 := el.asym(m, n, j, el.nocc+a)
	if fv2128 != 0 {
		if i == i1 {
			if k == j1 {
				if l == o {
					acc += fv2128
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t160: - \delta_{i j1} \delta_{k o} \delta_{l i1} {V^{mn}_{ja}}
func (el *Elem) b01o1t160(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2129 := el.asym(m, n, j, el.nocc+a)
	if fv2129 != 0 {
		if i == j1 {
			if k == o {
				if l == i1 {
					acc += fv2129
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t161: - \delta_{i o} \delta_{k i1} \delta_{l j1} {V^{mn}_{ja}}
func (el *Elem) b01o1t161(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2130 := el.asym(m, n, j, el.nocc+a)
	if fv2130 != 0 {
		if i == o {
			if k == i1 {
				if l == j1 {
					acc += fv2130
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t162: - \delta_{i i1} \delta_{j o} \delta_{l j1} {V^{mn}_{ka}}
func (el *Elem) b01o1t162(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2131 := el.asym(m, n, k, el.nocc+a)
	if fv2131 != 0 {
		if i == i1 {
			if j == o {
				if l == j1 {
					acc += fv2131
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t163: - \delta_{i j1} \delta_{j i1} \delta_{l o} {V^{mn}_{ka}}
func (el *Elem) b01o1t163(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2132 := el.asym(m, n, k, el.nocc+a)
	if fv2132 != 0 {
		if i == j1 {
			if j == i1 {
				if l == o {
					acc += fv2132
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t164: - \delta_{i o} \delta_{j j1} \delta_{l i1} {V^{mn}_{ka}}
func (el *Elem) b01o1t164(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2133 := el.asym(m, n, k, el.nocc+a)
	if fv2133 != 0 {
		if i == o {
			if j == j1 {
				if l == i1 {
					acc += fv2133
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t165: - \delta_{i i1} \delta_{j j1} \delta_{k o} {V^{mn}_{la}}
func (el *Elem) b01o1t165(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2134 := el.asym(m, n, l, el.nocc+a)
	if fv2134 != 0 {
		if i == i1 {
			if j == j1 {
				if k == o {
					acc += fv2134
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t166: - \delta_{i j1} \delta_{j o} \delta_{k i1} {V^{mn}_{la}}
func (el *Elem) b01o1t166(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2135 := el.asym(m, n, l, el.nocc+a)
	if fv2135 != 0 {
		if i == j1 {
			if j == o {
				if k == i1 {
					acc += fv2135
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t167: - \delta_{i o} \delta_{j i1} \delta_{k j1} {V^{mn}_{la}}
func (el *Elem) b01o1t167(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2136 := el.asym(m, n, l, el.nocc+a)
	if fv2136 != 0 {
		if i == o {
			if j == i1 {
				if k == j1 {
					acc += fv2136
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t168: - \delta_{j i1} \delta_{k j1} \delta_{l n} {V^{mo}_{ia}}
func (el *Elem) b01o1t168(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2137 := el.asym(m, o, i, el.nocc+a)
	if fv2137 != 0 {
		if j == i1 {
			if k == j1 {
				if l == n {
					acc += fv2137
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t169: - \delta_{j j1} \delta_{k n} \delta_{l i1} {V^{mo}_{ia}}
func (el *Elem) b01o1t169(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2138 := el.asym(m, o, i, el.nocc+a)
	if fv2138 != 0 {
		if j == j1 {
			if k == n {
				if l == i1 {
					acc += fv2138
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t170: - \delta_{j n} \delta_{k i1} \delta_{l j1} {V^{mo}_{ia}}
func (el *Elem) b01o1t170(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2139 := el.asym(m, o, i, el.nocc+a)
	if fv2139 != 0 {
		if j == n {
			if k == i1 {
				if l == j1 {
					acc += fv2139
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t171: - \delta_{i i1} \delta_{k n} \delta_{l j1} {V^{mo}_{ja}}
func (el *Elem) b01o1t171(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2140 := el.asym(m, o, j, el.nocc+a)
	if fv2140 != 0 {
		if i == i1 {
			if k == n {
				if l == j1 {
					acc += fv2140
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t172: - \delta_{i j1} \delta_{k i1} \delta_{l n} {V^{mo}_{ja}}
func (el *Elem) b01o1t172(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2141 := el.asym(m, o, j, el.nocc+a)
	if fv2141 != 0 {
		if i == j1 {
			if k == i1 {
				if l == n {
					acc += fv2141
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t173: - \delta_{i n} \delta_{k j1} \delta_{l i1} {V^{mo}_{ja}}
func (el *Elem) b01o1t173(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2142 := el.asym(m, o, j, el.nocc+a)
	if fv2142 != 0 {
		if i == n {
			if k == j1 {
				if l == i1 {
					acc += fv2142
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t174: - \delta_{i i1} \delta_{j j1} \delta_{l n} {V^{mo}_{ka}}
func (el *Elem) b01o1t174(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2143 := el.asym(m, o, k, el.nocc+a)
	if fv2143 != 0 {
		if i == i1 {
			if j == j1 {
				if l == n {
					acc += fv2143
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t175: - \delta_{i j1} \delta_{j n} \delta_{l i1} {V^{mo}_{ka}}
func (el *Elem) b01o1t175(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2144 := el.asym(m, o, k, el.nocc+a)
	if fv2144 != 0 {
		if i == j1 {
			if j == n {
				if l == i1 {
					acc += fv2144
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t176: - \delta_{i n} \delta_{j i1} \delta_{l j1} {V^{mo}_{ka}}
func (el *Elem) b01o1t176(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2145 := el.asym(m, o, k, el.nocc+a)
	if fv2145 != 0 {
		if i == n {
			if j == i1 {
				if l == j1 {
					acc += fv2145
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t177: - \delta_{i i1} \delta_{j n} \delta_{k j1} {V^{mo}_{la}}
func (el *Elem) b01o1t177(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2146 := el.asym(m, o, l, el.nocc+a)
	if fv2146 != 0 {
		if i == i1 {
			if j == n {
				if k == j1 {
					acc += fv2146
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t178: - \delta_{i j1} \delta_{j i1} \delta_{k n} {V^{mo}_{la}}
func (el *Elem) b01o1t178(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2147 := el.asym(m, o, l, el.nocc+a)
	if fv2147 != 0 {
		if i == j1 {
			if j == i1 {
				if k == n {
					acc += fv2147
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t179: - \delta_{i n} \delta_{j j1} \delta_{k i1} {V^{mo}_{la}}
func (el *Elem) b01o1t179(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2148 := el.asym(m, o, l, el.nocc+a)
	if fv2148 != 0 {
		if i == n {
			if j == j1 {
				if k == i1 {
					acc += fv2148
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t180: - \delta_{j j1} \delta_{k m} \delta_{l o} {V^{ni1}_{ia}}
func (el *Elem) b01o1t180(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2149 := el.asym(n, i1, i, el.nocc+a)
	if fv2149 != 0 {
		if j == j1 {
			if k == m {
				if l == o {
					acc += fv2149
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t181: - \delta_{j m} \delta_{k o} \delta_{l j1} {V^{ni1}_{ia}}
func (el *Elem) b01o1t181(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2150 := el.asym(n, i1, i, el.nocc+a)
	if fv2150 != 0 {
		if j == m {
			if k == o {
				if l == j1 {
					acc += fv2150
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t182: - \delta_{j o} \delta_{k j1} \delta_{l m} {V^{ni1}_{ia}}
func (el *Elem) b01o1t182(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2151 := el.asym(n, i1, i, el.nocc+a)
	if fv2151 != 0 {
		if j == o {
			if k == j1 {
				if l == m {
					acc += fv2151
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t183: - \delta_{i j1} \delta_{k o} \delta_{l m} {V^{ni1}_{ja}}
func (el *Elem) b01o1t183(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2152 := el.asym(n, i1, j, el.nocc+a)
	if fv2152 != 0 {
		if i == j1 {
			if k == o {
				if l == m {
					acc += fv2152
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t184: - \delta_{i m} \delta_{k j1} \delta_{l o} {V^{ni1}_{ja}}
func (el *Elem) b01o1t184(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2153 := el.asym(n, i1, j, el.nocc+a)
	if fv2153 != 0 {
		if i == m {
			if k == j1 {
				if l == o {
					acc += fv2153
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t185: - \delta_{i o} \delta_{k m} \delta_{l j1} {V^{ni1}_{ja}}
func (el *Elem) b01o1t185(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2154 := el.asym(n, i1, j, el.nocc+a)
	if fv2154 != 0 {
		if i == o {
			if k == m {
				if l == j1 {
					acc += fv2154
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t186: - \delta_{i j1} \delta_{j m} \delta_{l o} {V^{ni1}_{ka}}
func (el *Elem) b01o1t186(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2155 := el.asym(n, i1, k, el.nocc+a)
	if fv2155 != 0 {
		if i == j1 {
			if j == m {
				if l == o {
					acc += fv2155
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t187: - \delta_{i m} \delta_{j o} \delta_{l j1} {V^{ni1}_{ka}}
func (el *Elem) b01o1t187(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2156 := el.asym(n, i1, k, el.nocc+a)
	if fv2156 != 0 {
		if i == m {
			if j == o {
				if l == j1 {
					acc += fv2156
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t188: - \delta_{i o} \delta_{j j1} \delta_{l m} {V^{ni1}_{ka}}
func (el *Elem) b01o1t188(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2157 := el.asym(n, i1, k, el.nocc+a)
	if fv2157 != 0 {
		if i == o {
			if j == j1 {
				if l == m {
					acc += fv2157
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t189: - \delta_{i j1} \delta_{j o} \delta_{k m} {V^{ni1}_{la}}
func (el *Elem) b01o1t189(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2158 := el.asym(n, i1, l, el.nocc+a)
	if fv2158 != 0 {
		if i == j1 {
			if j == o {
				if k == m {
					acc += fv2158
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t190: - \delta_{i m} \delta_{j j1} \delta_{k o} {V^{ni1}_{la}}
func (el *Elem) b01o1t190(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2159 := el.asym(n, i1, l, el.nocc+a)
	if fv2159 != 0 {
		if i == m {
			if j == j1 {
				if k == o {
					acc += fv2159
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t191: - \delta_{i o} \delta_{j m} \delta_{k j1} {V^{ni1}_{la}}
func (el *Elem) b01o1t191(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2160 := el.asym(n, i1, l, el.nocc+a)
	if fv2160 != 0 {
		if i == o {
			if j == m {
				if k == j1 {
					acc += fv2160
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t192: - \delta_{j i1} \delta_{k o} \delta_{l m} {V^{nj1}_{ia}}
func (el *Elem) b01o1t192(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2161 := el.asym(n, j1, i, el.nocc+a)
	if fv2161 != 0 {
		if j == i1 {
			if k == o {
				if l == m {
					acc += fv2161
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t193: - \delta_{j m} \delta_{k i1} \delta_{l o} {V^{nj1}_{ia}}
func (el *Elem) b01o1t193(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2162 := el.asym(n, j1, i, el.nocc+a)
	if fv2162 != 0 {
		if j == m {
			if k == i1 {
				if l == o {
					acc += fv2162
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t194: - \delta_{j o} \delta_{k m} \delta_{l i1} {V^{nj1}_{ia}}
func (el *Elem) b01o1t194(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2163 := el.asym(n, j1, i, el.nocc+a)
	if fv2163 != 0 {
		if j == o {
			if k == m {
				if l == i1 {
					acc += fv2163
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t195: - \delta_{i i1} \delta_{k m} \delta_{l o} {V^{nj1}_{ja}}
func (el *Elem) b01o1t195(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2164 := el.asym(n, j1, j, el.nocc+a)
	if fv2164 != 0 {
		if i == i1 {
			if k == m {
				if l == o {
					acc += fv2164
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t196: - \delta_{i m} \delta_{k o} \delta_{l i1} {V^{nj1}_{ja}}
func (el *Elem) b01o1t196(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2165 := el.asym(n, j1, j, el.nocc+a)
	if fv2165 != 0 {
		if i == m {
			if k == o {
				if l == i1 {
					acc += fv2165
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t197: - \delta_{i o} \delta_{k i1} \delta_{l m} {V^{nj1}_{ja}}
func (el *Elem) b01o1t197(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2166 := el.asym(n, j1, j, el.nocc+a)
	if fv2166 != 0 {
		if i == o {
			if k == i1 {
				if l == m {
					acc += fv2166
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t198: - \delta_{i i1} \delta_{j o} \delta_{l m} {V^{nj1}_{ka}}
func (el *Elem) b01o1t198(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2167 := el.asym(n, j1, k, el.nocc+a)
	if fv2167 != 0 {
		if i == i1 {
			if j == o {
				if l == m {
					acc += fv2167
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t199: - \delta_{i m} \delta_{j i1} \delta_{l o} {V^{nj1}_{ka}}
func (el *Elem) b01o1t199(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2168 := el.asym(n, j1, k, el.nocc+a)
	if fv2168 != 0 {
		if i == m {
			if j == i1 {
				if l == o {
					acc += fv2168
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t200: - \delta_{i o} \delta_{j m} \delta_{l i1} {V^{nj1}_{ka}}
func (el *Elem) b01o1t200(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2169 := el.asym(n, j1, k, el.nocc+a)
	if fv2169 != 0 {
		if i == o {
			if j == m {
				if l == i1 {
					acc += fv2169
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t201: - \delta_{i i1} \delta_{j m} \delta_{k o} {V^{nj1}_{la}}
func (el *Elem) b01o1t201(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2170 := el.asym(n, j1, l, el.nocc+a)
	if fv2170 != 0 {
		if i == i1 {
			if j == m {
				if k == o {
					acc += fv2170
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t202: - \delta_{i m} \delta_{j o} \delta_{k i1} {V^{nj1}_{la}}
func (el *Elem) b01o1t202(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2171 := el.asym(n, j1, l, el.nocc+a)
	if fv2171 != 0 {
		if i == m {
			if j == o {
				if k == i1 {
					acc += fv2171
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t203: - \delta_{i o} \delta_{j i1} \delta_{k m} {V^{nj1}_{la}}
func (el *Elem) b01o1t203(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2172 := el.asym(n, j1, l, el.nocc+a)
	if fv2172 != 0 {
		if i == o {
			if j == i1 {
				if k == m {
					acc += fv2172
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t204: - \delta_{j i1} \delta_{k m} \delta_{l j1} {V^{no}_{ia}}
func (el *Elem) b01o1t204(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2173 := el.asym(n, o, i, el.nocc+a)
	if fv2173 != 0 {
		if j == i1 {
			if k == m {
				if l == j1 {
					acc += fv2173
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t205: - \delta_{j j1} \delta_{k i1} \delta_{l m} {V^{no}_{ia}}
func (el *Elem) b01o1t205(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2174 := el.asym(n, o, i, el.nocc+a)
	if fv2174 != 0 {
		if j == j1 {
			if k == i1 {
				if l == m {
					acc += fv2174
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t206: - \delta_{j m} \delta_{k j1} \delta_{l i1} {V^{no}_{ia}}
func (el *Elem) b01o1t206(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2175 := el.asym(n, o, i, el.nocc+a)
	if fv2175 != 0 {
		if j == m {
			if k == j1 {
				if l == i1 {
					acc += fv2175
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t207: - \delta_{i i1} \delta_{k j1} \delta_{l m} {V^{no}_{ja}}
func (el *Elem) b01o1t207(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2176 := el.asym(n, o, j, el.nocc+a)
	if fv2176 != 0 {
		if i == i1 {
			if k == j1 {
				if l == m {
					acc += fv2176
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t208: - \delta_{i j1} \delta_{k m} \delta_{l i1} {V^{no}_{ja}}
func (el *Elem) b01o1t208(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2177 := el.asym(n, o, j, el.nocc+a)
	if fv2177 != 0 {
		if i == j1 {
			if k == m {
				if l == i1 {
					acc += fv2177
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t209: - \delta_{i m} \delta_{k i1} \delta_{l j1} {V^{no}_{ja}}
func (el *Elem) b01o1t209(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2178 := el.asym(n, o, j, el.nocc+a)
	if fv2178 != 0 {
		if i == m {
			if k == i1 {
				if l == j1 {
					acc += fv2178
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t210: - \delta_{i i1} \delta_{j m} \delta_{l j1} {V^{no}_{ka}}
func (el *Elem) b01o1t210(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2179 := el.asym(n, o, k, el.nocc+a)
	if fv2179 != 0 {
		if i == i1 {
			if j == m {
				if l == j1 {
					acc += fv2179
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t211: - \delta_{i j1} \delta_{j i1} \delta_{l m} {V^{no}_{ka}}
func (el *Elem) b01o1t211(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2180 := el.asym(n, o, k, el.nocc+a)
	if fv2180 != 0 {
		if i == j1 {
			if j == i1 {
				if l == m {
					acc += fv2180
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t212: - \delta_{i m} \delta_{j j1} \delta_{l i1} {V^{no}_{ka}}
func (el *Elem) b01o1t212(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2181 := el.asym(n, o, k, el.nocc+a)
	if fv2181 != 0 {
		if i == m {
			if j == j1 {
				if l == i1 {
					acc += fv2181
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t213: - \delta_{i i1} \delta_{j j1} \delta_{k m} {V^{no}_{la}}
func (el *Elem) b01o1t213(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2182 := el.asym(n, o, l, el.nocc+a)
	if fv2182 != 0 {
		if i == i1 {
			if j == j1 {
				if k == m {
					acc += fv2182
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t214: - \delta_{i j1} \delta_{j m} \delta_{k i1} {V^{no}_{la}}
func (el *Elem) b01o1t214(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2183 := el.asym(n, o, l, el.nocc+a)
	if fv2183 != 0 {
		if i == j1 {
			if j == m {
				if k == i1 {
					acc += fv2183
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t215: - \delta_{i m} \delta_{j i1} \delta_{k j1} {V^{no}_{la}}
func (el *Elem) b01o1t215(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2184 := el.asym(n, o, l, el.nocc+a)
	if fv2184 != 0 {
		if i == m {
			if j == i1 {
				if k == j1 {
					acc += fv2184
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t216: - \delta_{j j1} \delta_{k n} \delta_{l m} {V^{oi1}_{ia}}
func (el *Elem) b01o1t216(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2185 := el.asym(o, i1, i, el.nocc+a)
	if fv2185 != 0 {
		if j == j1 {
			if k == n {
				if l == m {
					acc += fv2185
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t217: - \delta_{j m} \delta_{k j1} \delta_{l n} {V^{oi1}_{ia}}
func (el *Elem) b01o1t217(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2186 := el.asym(o, i1, i, el.nocc+a)
	if fv2186 != 0 {
		if j == m {
			if k == j1 {
				if l == n {
					acc += fv2186
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t218: - \delta_{j n} \delta_{k m} \delta_{l j1} {V^{oi1}_{ia}}
func (el *Elem) b01o1t218(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2187 := el.asym(o, i1, i, el.nocc+a)
	if fv2187 != 0 {
		if j == n {
			if k == m {
				if l == j1 {
					acc += fv2187
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t219: - \delta_{i j1} \delta_{k m} \delta_{l n} {V^{oi1}_{ja}}
func (el *Elem) b01o1t219(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2188 := el.asym(o, i1, j, el.nocc+a)
	if fv2188 != 0 {
		if i == j1 {
			if k == m {
				if l == n {
					acc += fv2188
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t220: - \delta_{i m} \delta_{k n} \delta_{l j1} {V^{oi1}_{ja}}
func (el *Elem) b01o1t220(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2189 := el.asym(o, i1, j, el.nocc+a)
	if fv2189 != 0 {
		if i == m {
			if k == n {
				if l == j1 {
					acc += fv2189
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t221: - \delta_{i n} \delta_{k j1} \delta_{l m} {V^{oi1}_{ja}}
func (el *Elem) b01o1t221(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2190 := el.asym(o, i1, j, el.nocc+a)
	if fv2190 != 0 {
		if i == n {
			if k == j1 {
				if l == m {
					acc += fv2190
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t222: - \delta_{i j1} \delta_{j n} \delta_{l m} {V^{oi1}_{ka}}
func (el *Elem) b01o1t222(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2191 := el.asym(o, i1, k, el.nocc+a)
	if fv2191 != 0 {
		if i == j1 {
			if j == n {
				if l == m {
					acc += fv2191
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t223: - \delta_{i m} \delta_{j j1} \delta_{l n} {V^{oi1}_{ka}}
func (el *Elem) b01o1t223(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2192 := el.asym(o, i1, k, el.nocc+a)
	if fv2192 != 0 {
		if i == m {
			if j == j1 {
				if l == n {
					acc += fv2192
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t224: - \delta_{i n} \delta_{j m} \delta_{l j1} {V^{oi1}_{ka}}
func (el *Elem) b01o1t224(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2193 := el.asym(o, i1, k, el.nocc+a)
	if fv2193 != 0 {
		if i == n {
			if j == m {
				if l == j1 {
					acc += fv2193
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t225: - \delta_{i j1} \delta_{j m} \delta_{k n} {V^{oi1}_{la}}
func (el *Elem) b01o1t225(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2194 := el.asym(o, i1, l, el.nocc+a)
	if fv2194 != 0 {
		if i == j1 {
			if j == m {
				if k == n {
					acc += fv2194
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t226: - \delta_{i m} \delta_{j n} \delta_{k j1} {V^{oi1}_{la}}
func (el *Elem) b01o1t226(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2195 := el.asym(o, i1, l, el.nocc+a)
	if fv2195 != 0 {
		if i == m {
			if j == n {
				if k == j1 {
					acc += fv2195
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t227: - \delta_{i n} \delta_{j j1} \delta_{k m} {V^{oi1}_{la}}
func (el *Elem) b01o1t227(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2196 := el.asym(o, i1, l, el.nocc+a)
	if fv2196 != 0 {
		if i == n {
			if j == j1 {
				if k == m {
					acc += fv2196
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t228: - \delta_{j i1} \delta_{k m} \delta_{l n} {V^{oj1}_{ia}}
func (el *Elem) b01o1t228(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2197 := el.asym(o, j1, i, el.nocc+a)
	if fv2197 != 0 {
		if j == i1 {
			if k == m {
				if l == n {
					acc += fv2197
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t229: - \delta_{j m} \delta_{k n} \delta_{l i1} {V^{oj1}_{ia}}
func (el *Elem) b01o1t229(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2198 := el.asym(o, j1, i, el.nocc+a)
	if fv2198 != 0 {
		if j == m {
			if k == n {
				if l == i1 {
					acc += fv2198
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t230: - \delta_{j n} \delta_{k i1} \delta_{l m} {V^{oj1}_{ia}}
func (el *Elem) b01o1t230(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2199 := el.asym(o, j1, i, el.nocc+a)
	if fv2199 != 0 {
		if j == n {
			if k == i1 {
				if l == m {
					acc += fv2199
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t231: - \delta_{i i1} \delta_{k n} \delta_{l m} {V^{oj1}_{ja}}
func (el *Elem) b01o1t231(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2200 := el.asym(o, j1, j, el.nocc+a)
	if fv2200 != 0 {
		if i == i1 {
			if k == n {
				if l == m {
					acc += fv2200
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t232: - \delta_{i m} \delta_{k i1} \delta_{l n} {V^{oj1}_{ja}}
func (el *Elem) b01o1t232(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2201 := el.asym(o, j1, j, el.nocc+a)
	if fv2201 != 0 {
		if i == m {
			if k == i1 {
				if l == n {
					acc += fv2201
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t233: - \delta_{i n} \delta_{k m} \delta_{l i1} {V^{oj1}_{ja}}
func (el *Elem) b01o1t233(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2202 := el.asym(o, j1, j, el.nocc+a)
	if fv2202 != 0 {
		if i == n {
			if k == m {
				if l == i1 {
					acc += fv2202
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t234: - \delta_{i i1} \delta_{j m} \delta_{l n} {V^{oj1}_{ka}}
func (el *Elem) b01o1t234(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2203 := el.asym(o, j1, k, el.nocc+a)
	if fv2203 != 0 {
		if i == i1 {
			if j == m {
				if l == n {
					acc += fv2203
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t235: - \delta_{i m} \delta_{j n} \delta_{l i1} {V^{oj1}_{ka}}
func (el *Elem) b01o1t235(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2204 := el.asym(o, j1, k, el.nocc+a)
	if fv2204 != 0 {
		if i == m {
			if j == n {
				if l == i1 {
					acc += fv2204
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t236: - \delta_{i n} \delta_{j i1} \delta_{l m} {V^{oj1}_{ka}}
func (el *Elem) b01o1t236(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2205 := el.asym(o, j1, k, el.nocc+a)
	if fv2205 != 0 {
		if i == n {
			if j == i1 {
				if l == m {
					acc += fv2205
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t237: - \delta_{i i1} \delta_{j n} \delta_{k m} {V^{oj1}_{la}}
func (el *Elem) b01o1t237(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2206 := el.asym(o, j1, l, el.nocc+a)
	if fv2206 != 0 {
		if i == i1 {
			if j == n {
				if k == m {
					acc += fv2206
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t238: - \delta_{i m} \delta_{j i1} \delta_{k n} {V^{oj1}_{la}}
func (el *Elem) b01o1t238(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2207 := el.asym(o, j1, l, el.nocc+a)
	if fv2207 != 0 {
		if i == m {
			if j == i1 {
				if k == n {
					acc += fv2207
				}
			}
		}
	}
	return -1.0 * acc
}

// b01o1t239: - \delta_{i n} \delta_{j m} \delta_{k i1} {V^{oj1}_{la}}
func (el *Elem) b01o1t239(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var acc float64
	fv2208 := el.asym(o, j1, l, el.nocc+a)
	if fv2208 != 0 {
		if i == n {
			if j == m {
				if k == i1 {
					acc += fv2208
				}
			}
		}
	}
	return -1.0 * acc
}

func (el *Elem) b01o1g0(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	return el.b01o1t0(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t1(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t2(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t3(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t4(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t5(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t6(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t7(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t8(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t9(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t10(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t11(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t12(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t13(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t14(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t15(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t16(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t17(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t18(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t19(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t20(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t21(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t22(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t23(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t24(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t25(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t26(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t27(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t28(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t29(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t30(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t31(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t32(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t33(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t34(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t35(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t36(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t37(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t38(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t39(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t40(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t41(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t42(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t43(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t44(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t45(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t46(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t47(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t48(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t49(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t50(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t51(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t52(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t53(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t54(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t55(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t56(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t57(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t58(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t59(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t60(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t61(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t62(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t63(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t64(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t65(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t66(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t67(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t68(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t69(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t70(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t71(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t72(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t73(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t74(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t75(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t76(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t77(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t78(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t79(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t80(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t81(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t82(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t83(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t84(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t85(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t86(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t87(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t88(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t89(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t90(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t91(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t92(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t93(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t94(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t95(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t96(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t97(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t98(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t99(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t100(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t101(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t102(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t103(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t104(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t105(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t106(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t107(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t108(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t109(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t110(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t111(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t112(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t113(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t114(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t115(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t116(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t117(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t118(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t119(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t120(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t121(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t122(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t123(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t124(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t125(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t126(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t127(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t128(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t129(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t130(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t131(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t132(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t133(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t134(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t135(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t136(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t137(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t138(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t139(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t140(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t141(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t142(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t143(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t144(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t145(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t146(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t147(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t148(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t149(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t150(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t151(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t152(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t153(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t154(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t155(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t156(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t157(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t158(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t159(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t160(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t161(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t162(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t163(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t164(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t165(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t166(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t167(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t168(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t169(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t170(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t171(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t172(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t173(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t174(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t175(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t176(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t177(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t178(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t179(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t180(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t181(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t182(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t183(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t184(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t185(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t186(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t187(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t188(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t189(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t190(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t191(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t192(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t193(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t194(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t195(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t196(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t197(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t198(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t199(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t200(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t201(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t202(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t203(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t204(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t205(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t206(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t207(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t208(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t209(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t210(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t211(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t212(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t213(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t214(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t215(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t216(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t217(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t218(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t219(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t220(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t221(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t222(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t223(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t224(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t225(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t226(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t227(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t228(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t229(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t230(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t231(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t232(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t233(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t234(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t235(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t236(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t237(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t238(i, j, k, l, a, m, n, o, i1, j1) +
		el.b01o1t239(i, j, k, l, a, m, n, o, i1, j1)
}

// b01o1 is the order-1 part of block hhhh,phhhhh, <i,j,k,l|M|a,m,n,o,i1,j1>.
func (el *Elem) b01o1(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var v float64
	// (1)
	v += el.b01o1g0(i, j, k, l, a, m, n, o, i1, j1)
	return v
}

// B01 is block hhhh,phhhhh of the secular matrix,
// <i,j,k,l|M|a,m,n,o,i1,j1>, summed over the orders the scheme keeps.
func (el *Elem) B01(i, j, k, l, a, m, n, o, i1, j1 int) float64 {
	var v float64
	if el.maxOrder[1] >= 1 {
		v += el.b01o1(i, j, k, l, a, m, n, o, i1, j1)
	}
	return v
}
