// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package qip

import "github.com/leiaSQ/ADCgo/internal/adc/parallel"

// itmdStore holds the dense intermediate tensors, row-major over their
// indices (occupied extent el.nocc, virtual extent el.nvir).
type itmdStore struct {
	x_t2_1 []float64 // t2_1[i,j,a,b]
}

// buildItmds fills every intermediate in dependency order.
func (el *Elem) buildItmds() {
	el.build_t2_1()
}

// ---- t2_1 ----

func (el *Elem) get_t2_1(i, j, a, b int) float64 {
	return el.x_t2_1[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b]
}

func (el *Elem) build_t2_1() {
	el.x_t2_1 = make([]float64, el.nocc*el.nocc*el.nvir*el.nvir)
	parallel.HeavyRows(el.nocc, func(i int) {
		for j := 0; j < el.nocc; j++ {
			for a := 0; a < el.nvir; a++ {
				for b := 0; b < el.nvir; b++ {
					el.x_t2_1[(((i)*el.nocc+j)*el.nvir+a)*el.nvir+b] = el.def_t2_1(i, j, a, b)
				}
			}
		}
	})
}

// def_t2_1t0: \frac{{V^{ab}_{ij}}}{{e_{a}} + {e_{b}} - {e_{i}} - {e_{j}}}
func (el *Elem) def_t2_1t0(i, j, a, b int) float64 {
	var acc float64
	fv4129 := el.asym(el.nocc+a, el.nocc+b, i, j)
	if fv4129 != 0 {
		acc += fv4129
	}
	return (1.0 / ((-1.0 * el.eps(i)) + (-1.0 * el.eps(j)) + el.eps(el.nocc+a) + el.eps(el.nocc+b))) * acc
}

func (el *Elem) def_t2_1g0(i, j, a, b int) float64 {
	return el.def_t2_1t0(i, j, a, b)
}

// def_t2_1 is adcgen's definition of intermediate t2_1[i,j,a,b].
func (el *Elem) def_t2_1(i, j, a, b int) float64 {
	var v float64
	// (1)
	v += el.def_t2_1g0(i, j, a, b)
	return v
}
