// Code generated by adcgen pipeline (scripts/codegen/generate_adc.py). DO NOT EDIT.

package qip

import (
	"fmt"
	"math/bits"
	"slices"

	"github.com/leiaSQ/ADCgo/backend"
	"github.com/leiaSQ/ADCgo/internal/adc/integrals"
	"github.com/leiaSQ/ADCgo/internal/adc/khci"
	"github.com/leiaSQ/ADCgo/internal/adc/parallel"
)

// Variant is the ionization variant these evaluators were generated for.
const Variant = "qip"

// K is the main-class hole count: classes are Kh | (K+1)h1p | (K+2)h2p.
const K = 4

// GeneratedOrders is the highest order generated per block, indexed as
// B00, B01, B11, B02, B12, B22 (-1: not generated).
var GeneratedOrders = [6]int{2, 1, 1, -1, -1, -1}

// Schemes maps each scheme name to its per-block maximum order (-1: the block
// is absent in that scheme).
var Schemes = map[string][6]int{
	"adc2x":    [6]int{2, 1, 1, -1, -1, -1},
	"ci":       [6]int{1, 1, 1, -1, -1, -1},
	"strict:2": [6]int{2, 1, 0, -1, -1, -1},
}

// Derivation times of this generation (adcgen, seconds per block):
//	B00         338.0 s
//	B01          32.2 s
//	B11         279.9 s

// Elem evaluates secular-matrix elements in the spin-orbital basis adcgen
// derives them in: spin orbital p has spatial orbital p>>1 and spin p&1,
// occupied spin orbitals are 0..nocc-1 and virtual a is absolute nocc+a. It
// assumes a CANONICAL Hartree-Fock reference (diagonal Fock matrix), which is
// what the generated expressions were simplified for. Intermediates are built
// once in New; afterwards Elem only reads shared state and is safe for
// concurrent use.
type Elem struct {
	ints     *integrals.Store
	orbEps   []float64 // spatial orbital energies
	nocc     int       // occupied spin orbitals
	nvir     int       // virtual spin orbitals
	scheme   string
	maxOrder [6]int
	itmdStore
}

// New builds the evaluator for a closed-shell reference with noccSpatial doubly
// occupied orbitals, truncated to the named scheme.
func New(ints *integrals.Store, eps []float64, noccSpatial int, scheme string) (*Elem, error) {
	mo, ok := Schemes[scheme]
	if !ok {
		names := make([]string, 0, len(Schemes))
		for n := range Schemes {
			names = append(names, n)
		}
		slices.Sort(names)
		return nil, fmt.Errorf("%s: scheme %q not generated (have %v)", Variant, scheme, names)
	}
	if 2*noccSpatial < K+2 && mo[5] >= 0 {
		return nil, fmt.Errorf("%s: %d occupied spin orbitals cannot hold %d holes",
			Variant, 2*noccSpatial, K+2)
	}
	el := &Elem{
		ints:     ints,
		orbEps:   eps,
		nocc:     2 * noccSpatial,
		nvir:     2 * ints.NVir(),
		scheme:   scheme,
		maxOrder: mo,
	}
	el.buildItmds()
	return el, nil
}

// Scheme is the scheme the evaluator was built for.
func (el *Elem) Scheme() string { return el.scheme }

// eps is the orbital energy of absolute spin orbital p.
func (el *Elem) eps(p int) float64 { return el.orbEps[p>>1] }

// fock is the canonical Fock matrix f_pq = eps_p delta_pq.
func (el *Elem) fock(p, q int) float64 {
	if p != q {
		return 0
	}
	return el.orbEps[p>>1]
}

// asym is <pq||rs> over absolute spin orbitals: <pq|rs> - <pq|sr>, with
// <pq|rs> = (pr|qs) delta(sp,sr) delta(sq,ss).
func (el *Elem) asym(p, q, r, s int) float64 {
	var v float64
	if p&1 == r&1 && q&1 == s&1 {
		v = el.ints.Eri(p>>1, r>>1, q>>1, s>>1)
	}
	if p&1 == s&1 && q&1 == r&1 {
		v -= el.ints.Eri(p>>1, s>>1, q>>1, r>>1)
	}
	return v
}

// nonzero marks the blocks with at least one non-vanishing generated order. A block a
// scheme enables can still vanish at every generated order (kh/(k+2)h2p starts at
// second order, so the ci scheme's B02 is identically zero).
var nonzero = [6]bool{true, true, true, false, false, false}

// blockOf maps (bra class, ket class), bra <= ket, to the block index.
var blockOf = [3][3]int{{0, 1, 3}, {-1, 2, 4}, {-1, -1, 5}}

// Element is <r|M|c> for rows r, c of a khci.Space with the same K. Rows follow
// the khci phase convention, which is adcgen's; the lower triangle uses the
// symmetry of M. A block the scheme leaves out is zero.
func (el *Elem) Element(sp *khci.Space, r, c int) float64 {
	cr, cc := sp.Class(r)-K, sp.Class(c)-K
	if cr > cc {
		r, c = c, r
		cr, cc = cc, cr
	}
	b := blockOf[cr][cc]
	if el.maxOrder[b] < 0 || !nonzero[b] {
		return 0
	}
	var buf [16]int
	a := buf[:0]
	a = appendRow(a, sp, r)
	a = appendRow(a, sp, c)
	return el.block(b, a)
}

// appendRow appends a row's target indices in adcgen order: particles
// (relative virtual spin orbitals), then holes (spin orbitals), ascending.
func appendRow(a []int, sp *khci.Space, r int) []int {
	a = sp.PartSO(r, a)
	for q := sp.HoleMask(r); q != 0; q &= q - 1 {
		a = append(a, bits.TrailingZeros64(q))
	}
	return a
}

func (el *Elem) block(b int, a []int) float64 {
	switch b {
	case 0:
		return el.B00(a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7])
	case 1:
		return el.B01(a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9])
	case 2:
		return el.B11(a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10], a[11])
	}
	panic(fmt.Sprintf("%s: block %d requested but not generated", Variant, b))
}

// BuildDense assembles the full matrix over sp, rows in parallel (each worker
// owns its rows).
func (el *Elem) BuildDense(sp *khci.Space) backend.Mat {
	n := sp.Size()
	m := backend.NewMat(n, n)
	parallel.HeavyRows(n, func(r int) {
		for c := range n {
			m.Data[r*n+c] = el.Element(sp, r, c)
		}
	})
	return m
}

// orderPart evaluates the order-th part of a block by name at the block's target
// indices (bra particles, bra holes, ket particles, ket holes). ok is false for
// an order that vanishes identically or was not generated. It serves the adcgen
// fidelity test.
func (el *Elem) orderPart(block string, order int, idx []int) (v float64, ok bool) {
	switch {
	case block == "B00" && order == 0:
		return el.b00o0(idx[0], idx[1], idx[2], idx[3], idx[4], idx[5], idx[6], idx[7]), true
	case block == "B00" && order == 1:
		return el.b00o1(idx[0], idx[1], idx[2], idx[3], idx[4], idx[5], idx[6], idx[7]), true
	case block == "B00" && order == 2:
		return el.b00o2(idx[0], idx[1], idx[2], idx[3], idx[4], idx[5], idx[6], idx[7]), true
	case block == "B01" && order == 1:
		return el.b01o1(idx[0], idx[1], idx[2], idx[3], idx[4], idx[5], idx[6], idx[7], idx[8], idx[9]), true
	case block == "B11" && order == 0:
		return el.b11o0(idx[0], idx[1], idx[2], idx[3], idx[4], idx[5], idx[6], idx[7], idx[8], idx[9], idx[10], idx[11]), true
	case block == "B11" && order == 1:
		return el.b11o1(idx[0], idx[1], idx[2], idx[3], idx[4], idx[5], idx[6], idx[7], idx[8], idx[9], idx[10], idx[11]), true
	}
	return 0, false
}
